from __future__ import annotations

from enum import IntEnum, StrEnum


class ExitCode(IntEnum):
    PASS = 0
    SCHEMA = 10
    DIGEST = 11
    PROTOCOL = 12
    SECURITY = 13
    ENVIRONMENT = 14
    EVIDENCE = 15
    INTERNAL = 20


class FailClass(StrEnum):
    # v2.8 stable externally reported classes.  Detailed classes below remain
    # internal diagnostic categories and are never used to turn a block into a
    # pass.
    EVIDENCE = "EVIDENCE"
    SECURITY_PRIVACY = "SECURITY_PRIVACY"
    EGRESS = "EGRESS"
    DUAL_RESIDENT = "DUAL_RESIDENT"
    PROTOCOL = "PROTOCOL"
    IDENTITY = "IDENTITY"
    PROVENANCE = "PROVENANCE"
    POLICY_TRUST = "POLICY_TRUST"
    ATTESTATION = "ATTESTATION"
    PRODUCT_GATE = "PRODUCT_GATE"
    INDEPENDENT_VERIFY = "INDEPENDENT_VERIFY"
    PREFLIGHT = "PREFLIGHT"
    SCHEDULE = "SCHEDULE"
    ENVIRONMENT_MEMORY = "ENVIRONMENT_MEMORY"
    MEASUREMENT = "MEASUREMENT"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    DIGEST_MISMATCH = "DIGEST_MISMATCH"
    ORPHAN_EVIDENCE = "ORPHAN_EVIDENCE"
    DUPLICATE_EVIDENCE = "DUPLICATE_EVIDENCE"
    FINAL_GATE_STALE = "FINAL_GATE_STALE"
    TERMINAL_STATUS_MISMATCH = "TERMINAL_STATUS_MISMATCH"
    FINAL_GATE_COUNT_INVALID = "FINAL_GATE_COUNT_INVALID"
    EVENT_AFTER_TERMINAL = "EVENT_AFTER_TERMINAL"
    RAW_SERIALIZATION_ALLOWED = "RAW_SERIALIZATION_ALLOWED"
    RAW_COPY_ALLOWED = "RAW_COPY_ALLOWED"
    RAW_REUSE = "RAW_REUSE"
    RAW_BINDING_MISMATCH = "RAW_BINDING_MISMATCH"
    MODEL_MANIFEST_MISMATCH = "MODEL_MANIFEST_MISMATCH"
    MODEL_PATH_UNSAFE = "MODEL_PATH_UNSAFE"
    MODEL_SWAP = "MODEL_SWAP"
    MODEL_IDENTITY_MISSING = "MODEL_IDENTITY_MISSING"
    UNAPPROVED_MODEL = "UNAPPROVED_MODEL"
    FSM_SEQUENCE_INVALID = "FSM_SEQUENCE_INVALID"
    FIRST_CHUNK_EMPTY = "FIRST_CHUNK_EMPTY"
    FSM_DUPLICATE_EVENT = "FSM_DUPLICATE_EVENT"
    FSM_SEQ_INVALID = "FSM_SEQ_INVALID"
    FSM_CLOCK_INVALID = "FSM_CLOCK_INVALID"
    STDOUT_PARTIAL_TAIL = "STDOUT_PARTIAL_TAIL"
    STDERR_TAIL_UNSCANNED = "STDERR_TAIL_UNSCANNED"
    EVENT_TOO_LARGE = "EVENT_TOO_LARGE"
    RSS_INVALID = "RSS_INVALID"
    SAMPLER_ERROR = "SAMPLER_ERROR"
    SAMPLER_GAP = "SAMPLER_GAP"
    COOLDOWN_INVALID = "COOLDOWN_INVALID"
    THERMAL_INVALID = "THERMAL_INVALID"
    LPM_INVALID = "LPM_INVALID"
    SCHEDULE_DIGEST_MISMATCH = "SCHEDULE_DIGEST_MISMATCH"
    WARMUP_INCLUDED = "WARMUP_INCLUDED"
    DUAL_IDENTITY_COLLISION = "DUAL_IDENTITY_COLLISION"
    DUAL_OVERLAP_MISSING = "DUAL_OVERLAP_MISSING"
    DUAL_INFERENCE_MISSING = "DUAL_INFERENCE_MISSING"
    EGRESS_RECEIPT_INVALID = "EGRESS_RECEIPT_INVALID"
    SENSITIVE_LOG_FINDING = "SENSITIVE_LOG_FINDING"
    RAW_SCAN_FORGED = "RAW_SCAN_FORGED"
    POLICY_INCOMPLETE = "POLICY_INCOMPLETE"
    POLICY_NOT_PREREGISTERED = "POLICY_NOT_PREREGISTERED"
    BASE_FULL_SHA_UNRESOLVED = "BASE_FULL_SHA_UNRESOLVED"
    SOURCE_TREE_MISMATCH = "SOURCE_TREE_MISMATCH"
    DIRTY_TREE = "DIRTY_TREE"
    BASE_NOT_APPROVED = "BASE_NOT_APPROVED"
    PATCH_SCOPE_MISMATCH = "PATCH_SCOPE_MISMATCH"
    PROCESS_LEAK = "PROCESS_LEAK"
    MEMORY_MARK_MISSING = "MEMORY_MARK_MISSING"
    RSS_SCOPE_INVALID = "RSS_SCOPE_INVALID"
    METAL_EVIDENCE_INVALID = "METAL_EVIDENCE_INVALID"
    DUAL_NOT_CORESIDENT = "DUAL_NOT_CORESIDENT"
    POLICY_BYPASS = "POLICY_BYPASS"
    LIVE_VERIFY_TRUSTS_PRODUCER = "LIVE_VERIFY_TRUSTS_PRODUCER"
    VERIFIER_NOT_INDEPENDENT = "VERIFIER_NOT_INDEPENDENT"
    RAW_CONTAINER_UNSAFE = "RAW_CONTAINER_UNSAFE"
    RAW_BUFFER_NOT_DESTROYED = "RAW_BUFFER_NOT_DESTROYED"
    FORBIDDEN_REPAIR = "FORBIDDEN_REPAIR"
    FINAL_BEFORE_DLP = "FINAL_BEFORE_DLP"
    EARLY_RETURN_UNTERMINALIZED = "EARLY_RETURN_UNTERMINALIZED"
    WORKER_CLOSE_INVALID = "WORKER_CLOSE_INVALID"
    TRAILING_BYTES_UNACCOUNTED = "TRAILING_BYTES_UNACCOUNTED"
    SAMPLER_EVIDENCE_INVALID = "SAMPLER_EVIDENCE_INVALID"
    ENVIRONMENT_INVALID = "ENVIRONMENT_INVALID"
    NETWORK_PROBE_ALLOWED = "NETWORK_PROBE_ALLOWED"
    SUBPROCESS_EGRESS_ALLOWED = "SUBPROCESS_EGRESS_ALLOWED"
    CI_NOT_GREEN = "CI_NOT_GREEN"
    INTEGRATION_FAKE_ONLY = "INTEGRATION_FAKE_ONLY"
    MUTATION_GAP = "MUTATION_GAP"
    ROUTE_DIFF_FAIL = "ROUTE_DIFF_FAIL"
    M3_START_BLOCKED = "M3_START_BLOCKED"
    CLI_BYPASS_PRESENT = "CLI_BYPASS_PRESENT"
    INDEPENDENT_VERIFY_FAIL = "INDEPENDENT_VERIFY_FAIL"
    PREMATURE_G1_CLAIM = "PREMATURE_G1_CLAIM"
    INTERNAL_VERIFIER_ERROR = "INTERNAL_VERIFIER_ERROR"


_DEFAULT_EXIT: dict[FailClass, ExitCode] = {
    FailClass.EVIDENCE: ExitCode.EVIDENCE,
    FailClass.SECURITY_PRIVACY: ExitCode.SECURITY,
    FailClass.EGRESS: ExitCode.SECURITY,
    FailClass.DUAL_RESIDENT: ExitCode.ENVIRONMENT,
    FailClass.PROTOCOL: ExitCode.PROTOCOL,
    FailClass.IDENTITY: ExitCode.DIGEST,
    FailClass.PROVENANCE: ExitCode.DIGEST,
    FailClass.POLICY_TRUST: ExitCode.SCHEMA,
    FailClass.ATTESTATION: ExitCode.DIGEST,
    FailClass.PRODUCT_GATE: ExitCode.PROTOCOL,
    FailClass.INDEPENDENT_VERIFY: ExitCode.EVIDENCE,
    FailClass.PREFLIGHT: ExitCode.PROTOCOL,
    FailClass.SCHEDULE: ExitCode.PROTOCOL,
    FailClass.ENVIRONMENT_MEMORY: ExitCode.ENVIRONMENT,
    FailClass.MEASUREMENT: ExitCode.ENVIRONMENT,
    FailClass.SCHEMA_INVALID: ExitCode.SCHEMA,
    FailClass.POLICY_INCOMPLETE: ExitCode.SCHEMA,
    FailClass.MODEL_IDENTITY_MISSING: ExitCode.SCHEMA,
    FailClass.MODEL_PATH_UNSAFE: ExitCode.SCHEMA,
    FailClass.DIGEST_MISMATCH: ExitCode.DIGEST,
    FailClass.RAW_BINDING_MISMATCH: ExitCode.DIGEST,
    FailClass.MODEL_MANIFEST_MISMATCH: ExitCode.DIGEST,
    FailClass.MODEL_SWAP: ExitCode.DIGEST,
    FailClass.SCHEDULE_DIGEST_MISMATCH: ExitCode.DIGEST,
    FailClass.FSM_SEQUENCE_INVALID: ExitCode.PROTOCOL,
    FailClass.FSM_DUPLICATE_EVENT: ExitCode.PROTOCOL,
    FailClass.FSM_SEQ_INVALID: ExitCode.PROTOCOL,
    FailClass.FSM_CLOCK_INVALID: ExitCode.PROTOCOL,
    FailClass.STDOUT_PARTIAL_TAIL: ExitCode.PROTOCOL,
    FailClass.EVENT_TOO_LARGE: ExitCode.PROTOCOL,
    FailClass.FIRST_CHUNK_EMPTY: ExitCode.PROTOCOL,
    FailClass.SENSITIVE_LOG_FINDING: ExitCode.SECURITY,
    FailClass.RAW_SCAN_FORGED: ExitCode.SECURITY,
    FailClass.EGRESS_RECEIPT_INVALID: ExitCode.SECURITY,
    FailClass.NETWORK_PROBE_ALLOWED: ExitCode.SECURITY,
    FailClass.SUBPROCESS_EGRESS_ALLOWED: ExitCode.SECURITY,
    FailClass.RSS_INVALID: ExitCode.ENVIRONMENT,
    FailClass.SAMPLER_ERROR: ExitCode.ENVIRONMENT,
    FailClass.SAMPLER_GAP: ExitCode.ENVIRONMENT,
    FailClass.THERMAL_INVALID: ExitCode.ENVIRONMENT,
    FailClass.LPM_INVALID: ExitCode.ENVIRONMENT,
    FailClass.METAL_EVIDENCE_INVALID: ExitCode.ENVIRONMENT,
    FailClass.ORPHAN_EVIDENCE: ExitCode.EVIDENCE,
    FailClass.DUPLICATE_EVIDENCE: ExitCode.EVIDENCE,
    FailClass.DUAL_OVERLAP_MISSING: ExitCode.EVIDENCE,
    FailClass.DUAL_INFERENCE_MISSING: ExitCode.EVIDENCE,
    FailClass.INTERNAL_VERIFIER_ERROR: ExitCode.INTERNAL,
}


class GateError(RuntimeError):
    """Stable, non-sensitive failure returned by every gate."""

    def __init__(
        self,
        fail_class: FailClass | str,
        detail_id: str = "UNSPECIFIED",
        *,
        exit_code: ExitCode | int | None = None,
    ) -> None:
        self.fail_class = FailClass(fail_class)
        self.detail_id = detail_id
        self.exit_code = ExitCode(exit_code or _DEFAULT_EXIT.get(self.fail_class, ExitCode.PROTOCOL))
        super().__init__(f"{self.fail_class.value}:{self.detail_id}")

    def as_safe_dict(self) -> dict[str, object]:
        return {
            "status": "BLOCKED",
            "fail_class": self.fail_class.value,
            "detail_id": self.detail_id,
            "exit_code": int(self.exit_code),
        }
