#!/usr/bin/env bash
set -euo pipefail

BFF_SECRET_SCHEMA_V1_OK=0
BFF_SECRET_EMPTY_STRING_BLOCK_OK=0
BFF_SECRET_FORMAT_OK=0

finish() {
  echo "BFF_SECRET_SCHEMA_V1_OK=${BFF_SECRET_SCHEMA_V1_OK}"
  echo "BFF_SECRET_EMPTY_STRING_BLOCK_OK=${BFF_SECRET_EMPTY_STRING_BLOCK_OK}"
  echo "BFF_SECRET_FORMAT_OK=${BFF_SECRET_FORMAT_OK}"
}
trap finish EXIT

# meta-only: 값 출력 금지
# Required keys
REQ_DATABASE_URL="${DATABASE_URL:-}"
REQ_EXPORT_SIGN_SECRET="${EXPORT_SIGN_SECRET:-}"

# 1) 존재/빈 값 차단
if [ -z "$REQ_DATABASE_URL" ] || [ -z "$REQ_EXPORT_SIGN_SECRET" ]; then
  echo "ERROR_CODE=SECRET_MISSING_OR_EMPTY"
  exit 1
fi
BFF_SECRET_EMPTY_STRING_BLOCK_OK=1
BFF_SECRET_SCHEMA_V1_OK=1

# 2) 형식 검사
case "$REQ_DATABASE_URL" in
  postgres://*|postgresql://*) ;;
  *) echo "ERROR_CODE=DATABASE_URL_FORMAT_INVALID"; exit 1;;
esac

# 최소 길이(값 자체는 출력 금지)
if [ "${#REQ_EXPORT_SIGN_SECRET}" -lt 16 ]; then
  echo "ERROR_CODE=EXPORT_SIGN_SECRET_TOO_SHORT"
  exit 1
fi

BFF_SECRET_FORMAT_OK=1
exit 0
