#!/usr/bin/env bash
set -euo pipefail

WORKSPACE_FS_SANDBOX_V1_OK=0
WORKSPACE_FS_SANDBOX_TRAVERSAL_BLOCK_OK=0
WORKSPACE_FS_SANDBOX_ABS_BLOCK_OK=0
WORKSPACE_FS_SANDBOX_SYMLINK_BLOCK_OK=0
WORKSPACE_FS_SANDBOX_WRITE_NEWFILE_BLOCK_OK=0

cleanup() {
  echo "WORKSPACE_FS_SANDBOX_V1_OK=${WORKSPACE_FS_SANDBOX_V1_OK}"
  echo "WORKSPACE_FS_SANDBOX_TRAVERSAL_BLOCK_OK=${WORKSPACE_FS_SANDBOX_TRAVERSAL_BLOCK_OK}"
  echo "WORKSPACE_FS_SANDBOX_ABS_BLOCK_OK=${WORKSPACE_FS_SANDBOX_ABS_BLOCK_OK}"
  echo "WORKSPACE_FS_SANDBOX_SYMLINK_BLOCK_OK=${WORKSPACE_FS_SANDBOX_SYMLINK_BLOCK_OK}"
  echo "WORKSPACE_FS_SANDBOX_WRITE_NEWFILE_BLOCK_OK=${WORKSPACE_FS_SANDBOX_WRITE_NEWFILE_BLOCK_OK}"

  if [[ "$WORKSPACE_FS_SANDBOX_V1_OK" == "1" ]] && \
     [[ "$WORKSPACE_FS_SANDBOX_TRAVERSAL_BLOCK_OK" == "1" ]] && \
     [[ "$WORKSPACE_FS_SANDBOX_ABS_BLOCK_OK" == "1" ]] && \
     [[ "$WORKSPACE_FS_SANDBOX_SYMLINK_BLOCK_OK" == "1" ]] && \
     [[ "$WORKSPACE_FS_SANDBOX_WRITE_NEWFILE_BLOCK_OK" == "1" ]]; then
    exit 0
  fi
  exit 1
}
trap cleanup EXIT

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

command -v node >/dev/null 2>&1 || { echo "BLOCK: node not found"; exit 1; }

OUT="$(node scripts/agent/workspace_fs_sandbox_selftest.cjs 2>&1)" || { echo "BLOCK: sandbox selftest failed"; echo "$OUT"; exit 1; }

echo "$OUT" | grep -nE '^WORKSPACE_FS_SANDBOX_TRAVERSAL_BLOCK_OK=1$' >/dev/null || exit 1
WORKSPACE_FS_SANDBOX_TRAVERSAL_BLOCK_OK=1

echo "$OUT" | grep -nE '^WORKSPACE_FS_SANDBOX_ABS_BLOCK_OK=1$' >/dev/null || exit 1
WORKSPACE_FS_SANDBOX_ABS_BLOCK_OK=1

echo "$OUT" | grep -nE '^WORKSPACE_FS_SANDBOX_SYMLINK_BLOCK_OK=1$' >/dev/null || exit 1
WORKSPACE_FS_SANDBOX_SYMLINK_BLOCK_OK=1

echo "$OUT" | grep -nE '^WORKSPACE_FS_SANDBOX_WRITE_NEWFILE_BLOCK_OK=1$' >/dev/null || exit 1
WORKSPACE_FS_SANDBOX_WRITE_NEWFILE_BLOCK_OK=1

echo "$OUT" | grep -nE '^WORKSPACE_FS_SANDBOX_V1_OK=1$' >/dev/null || exit 1
WORKSPACE_FS_SANDBOX_V1_OK=1

exit 0

