#!/usr/bin/env bash
set -euo pipefail
echo "P0_02_KEYS_ONLY_VAL=${REPO_GUARD_KEYS_ONLY:-unset}"

CURRENT_GUARD="NONE"
FAILED_GUARD="NONE"
FAILED_GUARD_EMITTED=0

emit_failed_guard_once() {
  if [ "${FAILED_GUARD_EMITTED}" -eq 0 ]; then
    FAILED_GUARD="${CURRENT_GUARD}"
    echo "REPO_CONTRACTS_FAILED_GUARD=${FAILED_GUARD}"
    FAILED_GUARD_EMITTED=1
  fi
}

REPO_CONTRACTS_HYGIENE_OK=0
PRODUCT_VERIFY_WORKFLOW_TEMPLATE_OK=0
DOCS_NO_BANNED_PHRASES_OK=0
ONPREM_REAL_WORLD_PROOF_OK=0
ONPREM_REAL_WORLD_PROOF_FORMAT_OK=0
ONPREM_PROOF_LATEST_PRESENT_OK=0
ONPREM_PROOF_ARCHIVE_LINKED_OK=0
ONPREM_PROOF_SENSITIVE_SCAN_OK=0
ONPREM_PROOF_LATEST_FRESH_OK=0

OK_CONTAMINATION_REPO_GUARD_OK=0
REQUIRED_CHECK_MERGE_GROUP_COVERAGE_OK=0
SSOT_PLACEHOLDER_GUARD_OK=0
REQUIRED_CHECK_NAME_STABILITY_OK=0
REQUIRED_CHECK_NO_SKIPPED_BYPASS_OK=0
NO_LOG_GREP_VERDICT_OK=0
NO_NPM_INSTALL_FALLBACK_OK=0
CANONICALIZE_SHARED_SINGLE_SOURCE_OK=0
TEST_EVENT_SELECTION_GUARD_OK=0

# New (H3.4-prep)
LOCKFILES_TRACKED_OK=0
REQUIRED_CHECK_CONTEXT_SINGLE_OK=0
AUDIT_APPEND_NO_DRIFT_OK=0
COUNTERS_NO_DRIFT_OK=0
ARTIFACTS_NOT_TRACKED_OK=0
REQUIRED_WORKFLOWS_ALWAYS_REPORTED_OK=0

# P4-P0-02 (Supplychain Permissions + Signer Uniqueness)
SUPPLYCHAIN_PERMISSIONS_SCOPED_V1_OK=0
SLSA_SIGNER_WORKFLOW_UNIQUE_V1_OK=0

# P4-P0-03 (AGENT) Workspace FS sandbox
WORKSPACE_FS_SANDBOX_V1_OK=0
WORKSPACE_FS_SANDBOX_TRAVERSAL_BLOCK_OK=0
WORKSPACE_FS_SANDBOX_ABS_BLOCK_OK=0
WORKSPACE_FS_SANDBOX_SYMLINK_BLOCK_OK=0
WORKSPACE_FS_SANDBOX_WRITE_NEWFILE_BLOCK_OK=0

# P4-P0-04 (AGENT) High-risk approval gate + taint propagation
HIGH_RISK_BLOCK_WITHOUT_APPROVAL_OK=0
HIGH_RISK_TAINT_PROPAGATION_OK=0
HIGH_RISK_APPROVAL_FORMAT_OK=0
HIGH_RISK_TAINT_STRING_BLOCK_OK=0
HIGH_RISK_TAINT_HIGH_SCOPE_ENFORCED_OK=0

# P4-P0-05 (AGENT) Skills runtime manifest + capability gate
SKILLS_MANIFEST_PRESENT_OK=0
SKILLS_CAPABILITY_GATE_BLOCK_OK=0
SKILLS_META_ONLY_PROOF_OK=0
SKILLS_META_ONLY_REQUIRED_OK=0

# P4-P0-06 (AGENT) Task queue idempotency + concurrency + atomic writes
TASK_QUEUE_IDEMPOTENCY_OK=0
TASK_QUEUE_CONCURRENCY_OK=0
TASK_QUEUE_PARTIAL_WRITE_0_OK=0
TASK_QUEUE_LOCK_NO_TIMEOUT_OK=0
TASK_QUEUE_ASYNC_TASK_FN_OK=0
TASK_QUEUE_YIELD_WAIT_OK=0

# P4-P1-01 (AGENT) Instruction layers meta-only (raw=0, hash/scope only)
INSTRUCTION_RAW_0_OK=0
INSTRUCTION_HASH_ONLY_OK=0
INSTRUCTION_LAYER_REGISTRY_OK=0

# P4-P1-02 (AGENT) Reason code registry (unregistered BLOCK, single source)
REASON_CODE_REGISTRY_PRESENT_OK=0
REASON_CODE_NOT_REGISTERED_BLOCK_OK=0

# P4-P1-03 (AGENT) Path scope SSOT (scan drift=0, fail-closed)
PATH_SCOPE_SSOT_PRESENT_OK=0
PATH_SCOPE_NO_PLACEHOLDER_OK=0
PATH_SCOPE_DRIFT_0_OK=0

# P5-P1-03 (PATH_SCOPE) Scanners must reference SSOT v2
PATH_SCOPE_ENFORCED_V2_OK=0

# P5-AI-P2-01 (AI) Feature digest v1 (meta-only allowlist)
AI_FEATURE_DIGEST_V1_PRESENT_OK=0
AI_FEATURE_DIGEST_V1_ALLOWED_KEYS_OK=0
AI_FEATURE_DIGEST_V1_VALUE_LIMITS_OK=0

# P5-AI-P2-02 (AI) Golden vectors v2 diversity v1
AI_GOLDEN_VECTORS_V2_DIVERSITY_OK=0
AI_GOLDEN_VECTORS_NO_RAW_OK=0

# P5-AI-P2-03 (AI) Energy proxy normalized v2
AI_ENERGY_PROXY_NORMALIZED_V2_OK=0
AI_ENERGY_PROXY_STABILITY_V2_OK=0

# P5-PLAT-P0-04 (PLAT) Pack core bypass block v1
PACK_CORE_BYPASS_POLICY_V1_OK=0
PACK_FORBIDDEN_IMPORT_BLOCK_V1_OK=0
PACK_MANIFEST_SCHEMA_LOCK_V1_OK=0

# P5-PLAT-P0-05 (PLAT) No raw in logs/exceptions v1
NO_RAW_IN_LOGS_POLICY_V1_OK=0
NO_RAW_IN_REPORTS_SCAN_V1_OK=0
SENSITIVE_PATTERN_BLOCK_V1_OK=0
LONG_LINE_BLOCK_V1_OK=0

# P5-PLAT-P1-04 (PLAT) MVP package demo harness v1
DEMO_DOC_SEARCH_ALLOW_OK=0
DEMO_DOC_SEARCH_BLOCK_OK=0
DEMO_DOC_SEARCH_META_ONLY_OK=0
DEMO_DOC_SEARCH_REQUEST_ID_JOIN_OK=0
DEMO_WRITE_APPROVE_ALLOW_OK=0
DEMO_WRITE_APPROVE_BLOCK_OK=0
DEMO_WRITE_APPROVE_META_ONLY_OK=0
DEMO_WRITE_APPROVE_REQUEST_ID_JOIN_OK=0
DEMO_HELPDESK_ALLOW_OK=0
DEMO_HELPDESK_BLOCK_OK=0
DEMO_HELPDESK_META_ONLY_OK=0
DEMO_HELPDESK_REQUEST_ID_JOIN_OK=0

# P5-PLAT-P1-05 (PLAT) Assist compute default OFF lock v1
ASSIST_COMPUTE_POLICY_V1_OK=0
ASSIST_COMPUTE_DEFAULT_OFF_LOCK_V1_OK=0

DOD_SINGLE_OUTPUT_GUARD_V1_OK=0

PREFLIGHT_ACTION_CONSUMED_BY_REQUIRED_WORKFLOWS_OK=0
PREFLIGHT_DUPLICATE_PREP_PATH_0_OK=0

ONPREM_LATEST_WHITELIST_ONLY_V2_OK=0
ONPREM_LATEST_LONG_LINE_SCAN_EOF_SAFE_OK=0

AI_ENERGY_PROXY_SSOT_RUNS_CONSUMED_OK=0
AI_ENERGY_PROXY_SSOT_MIN_P50_CONSUMED_OK=0

ONE_COMMAND_VERIFY_V1_OK=0

# P6-P0-04 (OPS) Artifact bundle v1
ARTIFACT_BUNDLE_POLICY_V1_OK=0
ARTIFACT_BUNDLE_PRESENT_OK=0
ARTIFACT_BUNDLE_META_ONLY_OK=0

# PR-P0-DEPLOY-00 (OPS) Build stamp generation SSOT v1 (pre-verify)
BUILD_STAMP_GENERATION_SSOT_V1_OK=0

# PR-P0-DEPLOY-01 probe SSOT (/healthz, /readyz)
PROBES_SSOT_V1_OK=0
PROBES_PATHS_MATCH_APP_V1_OK=0

# PR-P0-DEPLOY-03 docker it-net + postgres16 service name, no host.docker.internal
DOCKER_IT_NET_DB_SVCNAME_V1_OK=0
HOST_DOCKER_INTERNAL_FORBIDDEN_OK=0

# PR-P0-DEPLOY-02 BFF secret schema v1 (meta-only; skip when both env empty)
BFF_SECRET_SCHEMA_V1_OK=0
BFF_SECRET_FORMAT_OK=0
BFF_SECRET_EMPTY_STRING_BLOCK_OK=0
BFF_SECRET_SCHEMA_V1_SKIPPED=0

# P0-01 (OPS) Dockerless repo guard report contract DoD (CI-only verifier emits; here for schema)
DOCKERLESS_REPORT_RUN_OK=0
DOCKERLESS_REPORT_DEGRADED_DOCKER_KEYS_OK=0
DOCKERLESS_REPORT_STATIC_POLICY_ALWAYS_ON_OK=0
EXEC_MODE_PER_LINE_NO_EXCEPTION_TEXT_OK=0
EXEC_MODE_LATENCY_MEASURE_PRESENT_OK=0
EXEC_MODE_LATENCY_MISSING_BLOCK_OK=0
OUTPUT_ROOT_SSOT_V1_OK=0
CI_DOCS_WRITE_BLOCK_V1_OK=0
REPO_GUARD_KEYS_ONLY_MODE_OK=0
META_ONLY_OUTPUT_GUARD_V1_OK=0
PATH_SCOPE_READ_REQUIRED_OK=0

# P6-P0-05 (OPS) Autodecision from nightly v1
AUTODECISION_POLICY_V1_OK=0
AUTODECISION_OUTPUT_PRESENT_OK=0
AUTODECISION_REASON_CODE_ONLY_OK=0

# P6-P1-01 (OPS) Release gate connect v1
RELEASE_GATE_POLICY_V1_OK=0
RELEASE_GATE_WIRING_V1_OK=0
RELEASE_BLOCKED_WITHOUT_GATES_OK=0

# P4-AI-01 (AI) Golden vectors v2 (determinism + fingerprint validation)
AI_GOLDEN_VECTORS_V2_OK=0
AI_DETERMINISM_FINGERPRINT_OK=0

# P5-AI-P0-01 (AI) Golden vectors v2 raw text 0 v1
AI_GOLDEN_VECTORS_V2_RAW_TEXT_0_OK=0
AI_GOLDEN_VECTORS_V2_NO_ARRAY_OK=0
AI_GOLDEN_VECTORS_V2_PRESENT_OK=0

# P5-AI-P0-02 (AI) Canonicalize nested preserve v2
CANONICALIZE_V2_SSOT_OK=0
CANONICALIZE_V2_NO_DUP_OK=0
AI_INPUT_CANON_PRESERVE_NESTED_V1_OK=0

# P4-AI-02 (AI) Variance outlier guard (p50/p95 variance + outlier ratio)
AI_VARIANCE_MEASUREMENTS_SOURCE_OK=0
AI_VARIANCE_OK=0
AI_OUTLIER_RATIO_OK=0

# P4-AI-03 (AI) Energy proxy SSOT + stability gate
AI_ENERGY_PROXY_DEFINITION_SSOT_OK=0
AI_ENERGY_MEASUREMENTS_SOURCE_OK=0
AI_ENERGY_STABILITY_OK=0

# P5-AI-P0-03 (AI) Energy proxy fail-open/close v2
AI_ENERGY_PROXY_MEASUREMENT_WINDOW_SSOT_OK=0
AI_ENERGY_PROXY_NONTRIVIAL_SUM_GT0_OK=0
AI_ENERGY_PROXY_P50_POSITIVE_OK=0
AI_ENERGY_PROXY_EXPECTED_REQUIRED_OK=0

# P5-P0-01 (ONPREM) Latest pass marker v1
ONPREM_LATEST_PASS_MARKER_V1_OK=0
ONPREM_LATEST_NO_FAILURE_TEXT_V1_OK=0
ONPREM_LATEST_SENSITIVE_SCAN_V1_OK=0
ONPREM_LATEST_LONG_LINE_BLOCK_V1_OK=0

# P5-P0-02 (PREFLIGHT) One-shot preflight (single-source)
PREFLIGHT_ONE_SHOT_V1_PRESENT_OK=0
PREFLIGHT_ONE_SHOT_V1_RUNBOOK_OK=0

# P5-P0-03 (EGRESS) Egress deny proof harness v1
EGRESS_DENY_PROOF_HARNESS_V1_OK=0
EGRESS_DENY_RUNBOOK_V1_OK=0
EGRESS_DENY_PROOF_EXECUTES_IN_SANDBOX_OK=0

# P5-P1-01 (AI) Nightly long-run tiered policy v1
AI_NIGHTLY_WORKFLOW_PRESENT_V1_OK=0
AI_AB_BENCH_RUNS_TIERED_V1_OK=0

# P5-P1-02 (OPS) Report pipeline upload v1
OPS_REPORT_PIPELINE_V1_OK=0
OPS_REPORT_ARCHIVE_DATED_V1_OK=0

# P4-P0-02: Onprem strict proof (default: skip in dev/CI PR)
ONPREM_PROOF_STRICT_ENFORCE="${ONPREM_PROOF_STRICT_ENFORCE:-0}"
ONPREM_PROOF_STRICT_SKIPPED=0

# PROD-02
POLICY_HEADERS_REQUIRED_OK=0
POLICY_HEADERS_FAILCLOSED_OK=0

# PR-P0-BFF-01 (POLICY_HEADERS_SCHEMA_V1)
POLICY_HEADERS_SCHEMA_V1_OK=0
POLICY_HEADERS_RULE_DESCRIPTION_PRESENT_OK=0

# PROD-03
META_ONLY_ALLOWLIST_ENFORCED_OK=0
META_ONLY_VALIDATOR_PARITY_OK=0

# Track A-2
META_ONLY_VALIDATOR_SINGLE_SOURCE_OK=0
META_ONLY_VALIDATOR_NO_DUPLICATION_OK=0
META_ONLY_VALIDATOR_V1_CJS_PRESENT_OK=0

# PROD-04
EXPORT_TWO_STEP_OK=0
EXPORT_APPROVAL_AUDITED_OK=0
EXPORT_APPROVAL_AUDIT_EVENT_V2_WRITTEN_OK=0
EXPORT_APPROVE_AUDIT_V2_OK=0

# PROD-05
MOCK_NETWORK_ZERO_OK=0

# PROD-DELIVERED (SSOT)
PROD_DELIVERED_KEYSET_PRESENT_OK=0
PROD_DELIVERED_KEYSET_GUARD_OK=0

# WEB-UX-01
WEB_E2E_MODE_SWITCH_WIRED_OK=0
WEB_E2E_MOCK_NETWORK_ZERO_OK=0
WEB_E2E_LIVE_HEADER_BUNDLE_OK=0

# WEB-UX-03
WEB_E2E_EXPORT_TWO_STEP_OK=0
WEB_E2E_EXPORT_AUDITV2_OK=0
EXPORT_APPROVE_IDEMPOTENT_OK=0
EXPORT_APPROVE_AUDIT_ID_RETURNED_OK=0

# WEB-UX-04
PERF_E2E_EVENT_MARKS_WIRED_OK=0
PERF_E2E_MARKS_PARITY_OK=0

# PERF-REAL-PIPELINE
PERF_REAL_PIPELINE_WIRED_OK=0
PERF_REAL_PIPELINE_REQUEST_ID_JOIN_OK=0
PERF_REAL_PIPELINE_NO_RAW_OK=0
PERF_REAL_PIPELINE_P95_BUDGET_OK=0
PERF_REAL_PIPELINE_MIN_SAMPLES_OK=0
PERF_REAL_PIPELINE_VARIANCE_OK=0

# WEB-UX-08
WEB_META_ONLY_NEGATIVE_SUITE_OK=0

# VERIFY-PURITY
VERIFY_PURITY_NO_INSTALL_OK=0
VERIFY_PURITY_FULL_SCOPE_OK=0
VERIFY_PURITY_ALLOWLIST_SSOT_OK=0

# P3-PREP-00 (Common Hardening)
VERIFY_NO_DEV_TCP_IN_VERIFY_OK=0
VERIFY_RIPGREP_GUARD_PRESENT_V1_OK=0

# P3-PLAT-01 (Workflow Preflight SSOT)
WORKFLOW_PREFLIGHT_PRESENT_OK=0

# P3-PLAT-02 (Runtime Guard Helpers)
RUNTIME_GUARD_HELPERS_V1_ADOPTED_OK=0

# RUNTIME-EGRESS-ENV
RUNTIME_EGRESS_ENV_TEMPLATE_OK=0
RUNTIME_EGRESS_ENV_PROOF_OK=0

# MODEL-PACK-V0
MODEL_PACK_SCHEMA_SSOT_OK=0
MODEL_PACK_SIGNED_MANIFEST_VERIFY_OK=0
MODEL_PACK_MANIFEST_MISSING_FAILCLOSED_OK=0
MODEL_PACK_HASH_MISMATCH_FAILCLOSED_OK=0
MODEL_PACK_SIGNATURE_INVALID_FAILCLOSED_OK=0
MODEL_PACK_V0_ID_FIELDS_REQUIRED_OK=0
MODEL_PACK_V0_EXPIRES_ENFORCED_OK=0
MODEL_PACK_V0_COMPAT_FIELDS_REQUIRED_OK=0
MODEL_PACK_V0_COMPAT_ENFORCED_OK=0

# ONDEVICE-MODEL-EXEC-V0 (Track B-1)
ONDEVICE_MODEL_EXEC_V0_OK=0
MODEL_PACK_VERIFY_REQUIRED_OK=0
ONDEVICE_EGRESS_DENY_PROOF_OK=0
ONDEVICE_NO_RAW_STORAGE_OK=0

# ONDEVICE-REAL-COMPUTE-ONCE (Track B-1.1)
ONDEVICE_REAL_COMPUTE_ONCE_OK=0
ONDEVICE_RESULT_FINGERPRINT_OK=0
ONDEVICE_COMPUTE_PATH_ONDEVICE_OK=0

# P2-AI-01
ONDEVICE_MODEL_PACK_LOADED_OK=0
ONDEVICE_MODEL_PACK_IDENTITY_OK=0
ONDEVICE_INFERENCE_ONCE_OK=0
ONDEVICE_OUTPUT_FINGERPRINT_OK=0
ONDEVICE_INFER_USES_PACK_PARAMS_OK=0

# AI-V1-MODULES
AI_PERF_HARNESS_V1_OK=0
AI_RERANK_NEARTIE_V1_OK=0
AI_CALIB_V1_OK=0
AI_PROPENSITY_IPS_SNIPS_V1_OK=0
AI_DETERMINISM_OK=0
AI_P95_BUDGET_OK=0
AI_NEARTIE_SWAP_BUDGET_OK=0

# P2-AI-02 (Budget Gates)
AI_RESOURCE_BUDGET_LATENCY_OK=0
AI_RESOURCE_BUDGET_MEM_OK=0
AI_RESOURCE_BUDGET_ENERGY_PROXY_OK=0
AI_BUDGET_MEASUREMENTS_PRESENT_OK=0

# ALGO-DETERMINISM-GATE
ALGO_DETERMINISM_VERIFIED_OK=0
ALGO_DETERMINISM_HASH_MATCH_OK=0
ALGO_DETERMINISM_MODE_REPORTED_OK=0

# OPS-HUB-V0
OPS_HUB_META_SCHEMA_SSOT_OK=0
OPS_HUB_NO_RAW_TEXT_GUARD_OK=0
OPS_HUB_REPORT_V0_OK=0
OPS_HUB_REPORT_INPUT_META_ONLY_OK=0
OPS_HUB_TRACEABILITY_OK=0
OPS_HUB_TRACEABILITY_REPORT_OK=0
OPS_HUB_TRACEABILITY_NO_RAW_OK=0
OPS_HUB_TRACE_REALPATH_PERSISTED_OK=0
OPS_HUB_TRACE_REALPATH_JOINABLE_OK=0
OPS_HUB_TRACE_REALPATH_NO_RAW_OK=0
OPS_HUB_TRACE_REALPATH_IDEMPOTENT_OK=0

# OPS-HUB-TRACE-SERVICE-STORE
OPS_HUB_TRACE_SERVICE_PERSIST_OK=0
OPS_HUB_TRACE_IDEMPOTENT_OK=0
OPS_HUB_TRACE_NO_RAW_OK=0
OPS_HUB_TRACE_JOINABLE_OK=0

# A-3.1: Trace Security Lockdown
OPS_HUB_TRACE_LOCAL_ONLY_OR_AUTH_OK=0

# P1-PLAT-01
OPS_HUB_TRACE_DB_SCHEMA_OK=0
OPS_HUB_TRACE_REQUEST_ID_INDEX_OK=0
OPS_HUB_TRACE_IDEMPOTENT_UPSERT_OK=0
OPS_HUB_TRACE_CONCURRENCY_SAFE_OK=0
OPS_HUB_TRACE_EVENT_SCHEMA_V1_OK=0

# REASON-CODES-V1
REASON_CODE_SINGLE_SOURCE_OK=0
REASON_CODE_DRIFT_GUARD_OK=0

# M6-SEALED-RECORD
M6_SEALED_RECORD_PRESENT_OK=0
M6_SEALED_RECORD_NO_PLACEHOLDER_OK=0
M6_SEALED_RECORD_PR_MAP_OK=0

# M7-SEALED-RECORD
M7_SEALED_RECORD_PRESENT_OK=0
M7_SEALED_RECORD_FORMAT_OK=0
M7_SEALED_RECORD_NO_PLACEHOLDER_OK=0

# ALGO-APPLY-E2E
ALGO_APPLY_FAILCLOSED_E2E_OK=0
ALGO_APPLY_STATE_UNCHANGED_OK=0
ALGO_APPLY_REASON_CODE_PRESERVED_OK=0
# BUTLER-RUNTIME-V0
RUNTIME_V0_HTTP_OK=0
RUNTIME_EGRESS_DENY_DEFAULT_OK=0
RUNTIME_SHADOW_ENDPOINT_OK=0
RUNTIME_SHADOW_HEADERS_OK=0
BFF_SHADOW_FIREFORGET_OK=0
RUNTIME_SHADOW_PROOF_OK=0

# BUTLER-SSOT
BUTLER_SSOT_V1_1_OK=0

# ALGO-CORE-GATEWAY-DOC
ALGO_CORE_GATEWAY_DEPLOY_DOC_OK=0

# ALGO-CORE-06
ALGO_CORE_PROD_SSOT_PRESENT_OK=0
ALGO_CORE_PROD_ENV_TEMPLATE_PRESENT_OK=0
ALGO_CORE_KEYGEN_SCRIPT_PRESENT_OK=0
ALGO_CORE_PROD_FAILCLOSED_ENFORCED_OK=0
# ALGO-CORE-04
ALGO_CORE_RUNTIME_ROUTE_PRESENT_OK=0
ALGO_CORE_RUNTIME_PROD_FAILCLOSED_KEYS_OK=0

# ALGO-CORE-01~03
ALGO_META_ONLY_FAILCLOSED_OK=0
ALGO_THREE_BLOCKS_NO_RAW_OK=0
ALGO_SIGNED_MANIFEST_VERIFY_OK=0
ALGO_P95_HOOK_OK=0
ALGO_CORE_DELIVERED_KEYSET_PRESENT_OK=0
ALGO_CORE_DELIVERED_KEYSET_GUARD_OK=0

# PERF-01
PERF_P95_BUDGET_DEFINED_OK=0
PERF_P95_CONTRACT_OK=0
PERF_P95_REGRESSION_BLOCK_OK=0
PERF_P95_BASELINE_PINNED_OK=0

# ONPREM-01
ONPREM_COMPOSE_ASSETS_OK=0

# ONPREM-02
ONPREM_HELM_SKELETON_OK=0
ONPREM_HELM_SECRETS_GUARD_OK=0
ONPREM_HELM_TEMPLATE_SMOKE_OK=0
ONPREM_HELM_TEMPLATE_SECRET_REF_OK=0

# ONPREM-03/04 (Delivered keyset wiring)
ONPREM_SIGNED_BUNDLE_OK=0
ONPREM_INSTALL_VERIFY_OK=0

# ONPREM-06
ONPREM_SIGNING_KEY_REQUIRED_OK=0
ONPREM_EPHEMERAL_KEY_FORBIDDEN_OK=0
ONPREM_KEY_ID_ALLOWLIST_OK=0

# ONPREM-08
ONPREM_DELIVERED_KEYSET_PRESENT_OK=0
ONPREM_DELIVERED_KEYSET_GUARD_OK=0

cleanup(){
  # DoD block 밖: 디버그 키 (LAST=마지막 실행 가드, FAILED=실패한 가드명, 성공 시 NONE)
  echo "REPO_CONTRACTS_LAST_GUARD=${CURRENT_GUARD}"
  echo "REPO_CONTRACTS_FAILED_GUARD=${FAILED_GUARD}"
  echo "REPO_GUARD_KEYS_ONLY_MODE_OK=${REPO_GUARD_KEYS_ONLY_MODE_OK}"
  echo "META_ONLY_OUTPUT_GUARD_V1_OK=${META_ONLY_OUTPUT_GUARD_V1_OK}"
  echo "PATH_SCOPE_READ_REQUIRED_OK=${PATH_SCOPE_READ_REQUIRED_OK}"
  echo "DOD_KV_BLOCK_BEGIN=1"
  echo "REPO_CONTRACTS_HYGIENE_OK=${REPO_CONTRACTS_HYGIENE_OK}"
  echo "PRODUCT_VERIFY_WORKFLOW_TEMPLATE_OK=${PRODUCT_VERIFY_WORKFLOW_TEMPLATE_OK}"
  echo "DOCS_NO_BANNED_PHRASES_OK=${DOCS_NO_BANNED_PHRASES_OK}"
  echo "ONPREM_REAL_WORLD_PROOF_OK=${ONPREM_REAL_WORLD_PROOF_OK}"
  echo "ONPREM_REAL_WORLD_PROOF_FORMAT_OK=${ONPREM_REAL_WORLD_PROOF_FORMAT_OK}"
  echo "ONPREM_PROOF_LATEST_PRESENT_OK=${ONPREM_PROOF_LATEST_PRESENT_OK}"
  echo "ONPREM_PROOF_ARCHIVE_LINKED_OK=${ONPREM_PROOF_ARCHIVE_LINKED_OK}"
  echo "ONPREM_PROOF_SENSITIVE_SCAN_OK=${ONPREM_PROOF_SENSITIVE_SCAN_OK}"
  echo "ONPREM_PROOF_LATEST_FRESH_OK=${ONPREM_PROOF_LATEST_FRESH_OK}"
  echo "OK_CONTAMINATION_REPO_GUARD_OK=${OK_CONTAMINATION_REPO_GUARD_OK}"
  echo "REQUIRED_CHECK_MERGE_GROUP_COVERAGE_OK=${REQUIRED_CHECK_MERGE_GROUP_COVERAGE_OK}"
  echo "SSOT_PLACEHOLDER_GUARD_OK=${SSOT_PLACEHOLDER_GUARD_OK}"
  echo "REQUIRED_CHECK_NAME_STABILITY_OK=${REQUIRED_CHECK_NAME_STABILITY_OK}"
  echo "REQUIRED_CHECK_NO_SKIPPED_BYPASS_OK=${REQUIRED_CHECK_NO_SKIPPED_BYPASS_OK}"
  echo "NO_LOG_GREP_VERDICT_OK=${NO_LOG_GREP_VERDICT_OK}"
  echo "NO_NPM_INSTALL_FALLBACK_OK=${NO_NPM_INSTALL_FALLBACK_OK}"
  echo "CANONICALIZE_SHARED_SINGLE_SOURCE_OK=${CANONICALIZE_SHARED_SINGLE_SOURCE_OK}"

  echo "LOCKFILES_TRACKED_OK=${LOCKFILES_TRACKED_OK}"
  echo "REQUIRED_CHECK_CONTEXT_SINGLE_OK=${REQUIRED_CHECK_CONTEXT_SINGLE_OK}"
  echo "AUDIT_APPEND_NO_DRIFT_OK=${AUDIT_APPEND_NO_DRIFT_OK}"
  echo "COUNTERS_NO_DRIFT_OK=${COUNTERS_NO_DRIFT_OK}"
  echo "ARTIFACTS_NOT_TRACKED_OK=${ARTIFACTS_NOT_TRACKED_OK}"
  echo "REQUIRED_WORKFLOWS_ALWAYS_REPORTED_OK=${REQUIRED_WORKFLOWS_ALWAYS_REPORTED_OK}"

  echo "POLICY_HEADERS_REQUIRED_OK=${POLICY_HEADERS_REQUIRED_OK}"
  echo "POLICY_HEADERS_FAILCLOSED_OK=${POLICY_HEADERS_FAILCLOSED_OK}"
  echo "POLICY_HEADERS_SCHEMA_V1_OK=${POLICY_HEADERS_SCHEMA_V1_OK}"
  echo "POLICY_HEADERS_RULE_DESCRIPTION_PRESENT_OK=${POLICY_HEADERS_RULE_DESCRIPTION_PRESENT_OK}"

  echo "META_ONLY_ALLOWLIST_ENFORCED_OK=${META_ONLY_ALLOWLIST_ENFORCED_OK}"
  echo "META_ONLY_VALIDATOR_PARITY_OK=${META_ONLY_VALIDATOR_PARITY_OK}"
  echo "META_ONLY_VALIDATOR_SINGLE_SOURCE_OK=${META_ONLY_VALIDATOR_SINGLE_SOURCE_OK}"
  echo "META_ONLY_VALIDATOR_NO_DUPLICATION_OK=${META_ONLY_VALIDATOR_NO_DUPLICATION_OK}"
  echo "META_ONLY_VALIDATOR_V1_CJS_PRESENT_OK=${META_ONLY_VALIDATOR_V1_CJS_PRESENT_OK}"

  echo "EXPORT_TWO_STEP_OK=${EXPORT_TWO_STEP_OK}"
  echo "EXPORT_APPROVAL_AUDITED_OK=${EXPORT_APPROVAL_AUDITED_OK}"
  echo "EXPORT_APPROVAL_AUDIT_EVENT_V2_WRITTEN_OK=${EXPORT_APPROVAL_AUDIT_EVENT_V2_WRITTEN_OK}"
  echo "EXPORT_APPROVE_AUDIT_V2_OK=${EXPORT_APPROVE_AUDIT_V2_OK}"

  echo "MOCK_NETWORK_ZERO_OK=${MOCK_NETWORK_ZERO_OK}"

  echo "PROD_DELIVERED_KEYSET_PRESENT_OK=${PROD_DELIVERED_KEYSET_PRESENT_OK}"
  echo "PROD_DELIVERED_KEYSET_GUARD_OK=${PROD_DELIVERED_KEYSET_GUARD_OK}"

  echo "PERF_P95_BUDGET_DEFINED_OK=${PERF_P95_BUDGET_DEFINED_OK}"
  echo "PERF_P95_CONTRACT_OK=${PERF_P95_CONTRACT_OK}"
  echo "PERF_P95_REGRESSION_BLOCK_OK=${PERF_P95_REGRESSION_BLOCK_OK}"
  echo "PERF_P95_BASELINE_PINNED_OK=${PERF_P95_BASELINE_PINNED_OK}"

  echo "ONPREM_COMPOSE_ASSETS_OK=${ONPREM_COMPOSE_ASSETS_OK}"

  echo "ONPREM_HELM_SKELETON_OK=${ONPREM_HELM_SKELETON_OK}"
  echo "ONPREM_HELM_SECRETS_GUARD_OK=${ONPREM_HELM_SECRETS_GUARD_OK}"
  echo "ONPREM_HELM_TEMPLATE_SMOKE_OK=${ONPREM_HELM_TEMPLATE_SMOKE_OK}"
  echo "ONPREM_HELM_TEMPLATE_SECRET_REF_OK=${ONPREM_HELM_TEMPLATE_SECRET_REF_OK}"

  echo "ONPREM_SIGNED_BUNDLE_OK=${ONPREM_SIGNED_BUNDLE_OK}"
  echo "ONPREM_INSTALL_VERIFY_OK=${ONPREM_INSTALL_VERIFY_OK}"

  echo "ONPREM_SIGNING_KEY_REQUIRED_OK=${ONPREM_SIGNING_KEY_REQUIRED_OK}"
  echo "ONPREM_EPHEMERAL_KEY_FORBIDDEN_OK=${ONPREM_EPHEMERAL_KEY_FORBIDDEN_OK}"
  echo "ONPREM_KEY_ID_ALLOWLIST_OK=${ONPREM_KEY_ID_ALLOWLIST_OK}"

  echo "ONPREM_DELIVERED_KEYSET_PRESENT_OK=${ONPREM_DELIVERED_KEYSET_PRESENT_OK}"
  echo "ONPREM_DELIVERED_KEYSET_GUARD_OK=${ONPREM_DELIVERED_KEYSET_GUARD_OK}"

  echo "TEST_EVENT_SELECTION_GUARD_OK=${TEST_EVENT_SELECTION_GUARD_OK}"

  echo "PROD_DELIVERED_KEYSET_PRESENT_OK=${PROD_DELIVERED_KEYSET_PRESENT_OK}"
  echo "PROD_DELIVERED_KEYSET_GUARD_OK=${PROD_DELIVERED_KEYSET_GUARD_OK}"

  echo "WEB_E2E_MODE_SWITCH_WIRED_OK=${WEB_E2E_MODE_SWITCH_WIRED_OK}"
  echo "WEB_E2E_MOCK_NETWORK_ZERO_OK=${WEB_E2E_MOCK_NETWORK_ZERO_OK}"
  echo "WEB_E2E_LIVE_HEADER_BUNDLE_OK=${WEB_E2E_LIVE_HEADER_BUNDLE_OK}"
  echo "WEB_E2E_EXPORT_TWO_STEP_OK=${WEB_E2E_EXPORT_TWO_STEP_OK}"
  echo "WEB_E2E_EXPORT_AUDITV2_OK=${WEB_E2E_EXPORT_AUDITV2_OK}"
  echo "EXPORT_APPROVE_IDEMPOTENT_OK=${EXPORT_APPROVE_IDEMPOTENT_OK}"
  echo "EXPORT_APPROVE_AUDIT_ID_RETURNED_OK=${EXPORT_APPROVE_AUDIT_ID_RETURNED_OK}"
  echo "PERF_E2E_EVENT_MARKS_WIRED_OK=${PERF_E2E_EVENT_MARKS_WIRED_OK}"
  echo "PERF_E2E_MARKS_PARITY_OK=${PERF_E2E_MARKS_PARITY_OK}"
  echo "PERF_REAL_PIPELINE_WIRED_OK=${PERF_REAL_PIPELINE_WIRED_OK}"
  echo "PERF_REAL_PIPELINE_REQUEST_ID_JOIN_OK=${PERF_REAL_PIPELINE_REQUEST_ID_JOIN_OK}"
  echo "PERF_REAL_PIPELINE_NO_RAW_OK=${PERF_REAL_PIPELINE_NO_RAW_OK}"
  echo "PERF_REAL_PIPELINE_P95_BUDGET_OK=${PERF_REAL_PIPELINE_P95_BUDGET_OK}"
  echo "PERF_REAL_PIPELINE_MIN_SAMPLES_OK=${PERF_REAL_PIPELINE_MIN_SAMPLES_OK}"
  echo "PERF_REAL_PIPELINE_VARIANCE_OK=${PERF_REAL_PIPELINE_VARIANCE_OK}"
  echo "WEB_META_ONLY_NEGATIVE_SUITE_OK=${WEB_META_ONLY_NEGATIVE_SUITE_OK}"
  echo "VERIFY_PURITY_NO_INSTALL_OK=${VERIFY_PURITY_NO_INSTALL_OK}"
  echo "VERIFY_PURITY_FULL_SCOPE_OK=${VERIFY_PURITY_FULL_SCOPE_OK}"
  echo "VERIFY_PURITY_ALLOWLIST_SSOT_OK=${VERIFY_PURITY_ALLOWLIST_SSOT_OK}"

  # P3-PREP-00 (Common Hardening)
  echo "VERIFY_NO_DEV_TCP_IN_VERIFY_OK=${VERIFY_NO_DEV_TCP_IN_VERIFY_OK}"
  echo "VERIFY_RIPGREP_GUARD_PRESENT_V1_OK=${VERIFY_RIPGREP_GUARD_PRESENT_V1_OK}"

  # P3-PLAT-01 (Workflow Preflight SSOT)
  echo "WORKFLOW_PREFLIGHT_PRESENT_OK=${WORKFLOW_PREFLIGHT_PRESENT_OK}"

  # P3-PLAT-02 (Runtime Guard Helpers)
  echo "RUNTIME_GUARD_HELPERS_V1_ADOPTED_OK=${RUNTIME_GUARD_HELPERS_V1_ADOPTED_OK}"

  echo "RUNTIME_EGRESS_ENV_TEMPLATE_OK=${RUNTIME_EGRESS_ENV_TEMPLATE_OK}"
  echo "RUNTIME_EGRESS_ENV_PROOF_OK=${RUNTIME_EGRESS_ENV_PROOF_OK}"

  # MODEL-PACK-V0
  echo "MODEL_PACK_SCHEMA_SSOT_OK=${MODEL_PACK_SCHEMA_SSOT_OK}"
  echo "MODEL_PACK_SIGNED_MANIFEST_VERIFY_OK=${MODEL_PACK_SIGNED_MANIFEST_VERIFY_OK}"
  echo "MODEL_PACK_MANIFEST_MISSING_FAILCLOSED_OK=${MODEL_PACK_MANIFEST_MISSING_FAILCLOSED_OK}"
  echo "MODEL_PACK_HASH_MISMATCH_FAILCLOSED_OK=${MODEL_PACK_HASH_MISMATCH_FAILCLOSED_OK}"
  echo "MODEL_PACK_SIGNATURE_INVALID_FAILCLOSED_OK=${MODEL_PACK_SIGNATURE_INVALID_FAILCLOSED_OK}"
  echo "MODEL_PACK_V0_ID_FIELDS_REQUIRED_OK=${MODEL_PACK_V0_ID_FIELDS_REQUIRED_OK}"
  echo "MODEL_PACK_V0_EXPIRES_ENFORCED_OK=${MODEL_PACK_V0_EXPIRES_ENFORCED_OK}"
  echo "MODEL_PACK_V0_COMPAT_FIELDS_REQUIRED_OK=${MODEL_PACK_V0_COMPAT_FIELDS_REQUIRED_OK}"
  echo "MODEL_PACK_V0_COMPAT_ENFORCED_OK=${MODEL_PACK_V0_COMPAT_ENFORCED_OK}"

  # ONDEVICE-MODEL-EXEC-V0 (Track B-1)
  echo "ONDEVICE_MODEL_EXEC_V0_OK=${ONDEVICE_MODEL_EXEC_V0_OK}"
  echo "MODEL_PACK_VERIFY_REQUIRED_OK=${MODEL_PACK_VERIFY_REQUIRED_OK}"
  echo "ONDEVICE_EGRESS_DENY_PROOF_OK=${ONDEVICE_EGRESS_DENY_PROOF_OK}"
  echo "ONDEVICE_NO_RAW_STORAGE_OK=${ONDEVICE_NO_RAW_STORAGE_OK}"

  # ONDEVICE-REAL-COMPUTE-ONCE (Track B-1.1)
  echo "ONDEVICE_REAL_COMPUTE_ONCE_OK=${ONDEVICE_REAL_COMPUTE_ONCE_OK}"
  echo "ONDEVICE_RESULT_FINGERPRINT_OK=${ONDEVICE_RESULT_FINGERPRINT_OK}"
  echo "ONDEVICE_COMPUTE_PATH_ONDEVICE_OK=${ONDEVICE_COMPUTE_PATH_ONDEVICE_OK}"

  # P2-AI-01
  echo "ONDEVICE_MODEL_PACK_LOADED_OK=${ONDEVICE_MODEL_PACK_LOADED_OK}"
  echo "ONDEVICE_MODEL_PACK_IDENTITY_OK=${ONDEVICE_MODEL_PACK_IDENTITY_OK}"
  echo "ONDEVICE_INFERENCE_ONCE_OK=${ONDEVICE_INFERENCE_ONCE_OK}"
  echo "ONDEVICE_OUTPUT_FINGERPRINT_OK=${ONDEVICE_OUTPUT_FINGERPRINT_OK}"
  echo "ONDEVICE_INFER_USES_PACK_PARAMS_OK=${ONDEVICE_INFER_USES_PACK_PARAMS_OK}"

  # AI-V1-MODULES
  echo "AI_PERF_HARNESS_V1_OK=${AI_PERF_HARNESS_V1_OK}"
  echo "AI_RERANK_NEARTIE_V1_OK=${AI_RERANK_NEARTIE_V1_OK}"
  echo "AI_CALIB_V1_OK=${AI_CALIB_V1_OK}"
  echo "AI_PROPENSITY_IPS_SNIPS_V1_OK=${AI_PROPENSITY_IPS_SNIPS_V1_OK}"
  echo "AI_DETERMINISM_OK=${AI_DETERMINISM_OK}"
  echo "AI_P95_BUDGET_OK=${AI_P95_BUDGET_OK}"
  echo "AI_NEARTIE_SWAP_BUDGET_OK=${AI_NEARTIE_SWAP_BUDGET_OK}"

  # P2-AI-02 (Budget Gates)
  echo "AI_RESOURCE_BUDGET_LATENCY_OK=${AI_RESOURCE_BUDGET_LATENCY_OK}"
  echo "AI_RESOURCE_BUDGET_MEM_OK=${AI_RESOURCE_BUDGET_MEM_OK}"
  echo "AI_RESOURCE_BUDGET_ENERGY_PROXY_OK=${AI_RESOURCE_BUDGET_ENERGY_PROXY_OK}"
  echo "AI_BUDGET_MEASUREMENTS_PRESENT_OK=${AI_BUDGET_MEASUREMENTS_PRESENT_OK}"
  echo "AI_ENERGY_PROXY_DEFINITION_SSOT_OK=${AI_ENERGY_PROXY_DEFINITION_SSOT_OK}"

  # ALGO-DETERMINISM-GATE
  echo "ALGO_DETERMINISM_VERIFIED_OK=${ALGO_DETERMINISM_VERIFIED_OK}"
  echo "ALGO_DETERMINISM_HASH_MATCH_OK=${ALGO_DETERMINISM_HASH_MATCH_OK}"
  echo "ALGO_DETERMINISM_MODE_REPORTED_OK=${ALGO_DETERMINISM_MODE_REPORTED_OK}"

  # OPS-HUB-V0
  echo "OPS_HUB_META_SCHEMA_SSOT_OK=${OPS_HUB_META_SCHEMA_SSOT_OK}"
  echo "OPS_HUB_NO_RAW_TEXT_GUARD_OK=${OPS_HUB_NO_RAW_TEXT_GUARD_OK}"
  echo "OPS_HUB_REPORT_V0_OK=${OPS_HUB_REPORT_V0_OK}"
  echo "OPS_HUB_REPORT_INPUT_META_ONLY_OK=${OPS_HUB_REPORT_INPUT_META_ONLY_OK}"
  echo "OPS_HUB_TRACEABILITY_OK=${OPS_HUB_TRACEABILITY_OK}"
  echo "OPS_HUB_TRACEABILITY_REPORT_OK=${OPS_HUB_TRACEABILITY_REPORT_OK}"
  echo "OPS_HUB_TRACEABILITY_NO_RAW_OK=${OPS_HUB_TRACEABILITY_NO_RAW_OK}"
  echo "OPS_HUB_TRACE_REALPATH_PERSISTED_OK=${OPS_HUB_TRACE_REALPATH_PERSISTED_OK}"
  echo "OPS_HUB_TRACE_REALPATH_JOINABLE_OK=${OPS_HUB_TRACE_REALPATH_JOINABLE_OK}"
  echo "OPS_HUB_TRACE_REALPATH_NO_RAW_OK=${OPS_HUB_TRACE_REALPATH_NO_RAW_OK}"
  echo "OPS_HUB_TRACE_REALPATH_IDEMPOTENT_OK=${OPS_HUB_TRACE_REALPATH_IDEMPOTENT_OK}"

  # OPS-HUB-TRACE-SERVICE-STORE
  echo "OPS_HUB_TRACE_SERVICE_PERSIST_OK=${OPS_HUB_TRACE_SERVICE_PERSIST_OK}"
  echo "OPS_HUB_TRACE_IDEMPOTENT_OK=${OPS_HUB_TRACE_IDEMPOTENT_OK}"
  echo "OPS_HUB_TRACE_NO_RAW_OK=${OPS_HUB_TRACE_NO_RAW_OK}"
  echo "OPS_HUB_TRACE_JOINABLE_OK=${OPS_HUB_TRACE_JOINABLE_OK}"

  # A-3.1: Trace Security Lockdown
  echo "OPS_HUB_TRACE_LOCAL_ONLY_OR_AUTH_OK=${OPS_HUB_TRACE_LOCAL_ONLY_OR_AUTH_OK}"

  # P1-PLAT-01: Trace DB Store
  echo "OPS_HUB_TRACE_DB_SCHEMA_OK=${OPS_HUB_TRACE_DB_SCHEMA_OK}"
  echo "OPS_HUB_TRACE_REQUEST_ID_INDEX_OK=${OPS_HUB_TRACE_REQUEST_ID_INDEX_OK}"
  echo "OPS_HUB_TRACE_IDEMPOTENT_UPSERT_OK=${OPS_HUB_TRACE_IDEMPOTENT_UPSERT_OK}"
  echo "OPS_HUB_TRACE_CONCURRENCY_SAFE_OK=${OPS_HUB_TRACE_CONCURRENCY_SAFE_OK}"
  echo "OPS_HUB_TRACE_EVENT_SCHEMA_V1_OK=${OPS_HUB_TRACE_EVENT_SCHEMA_V1_OK}"

  # REASON-CODES-V1
  echo "REASON_CODE_SINGLE_SOURCE_OK=${REASON_CODE_SINGLE_SOURCE_OK}"
  echo "REASON_CODE_DRIFT_GUARD_OK=${REASON_CODE_DRIFT_GUARD_OK}"

  # M6-SEALED-RECORD
  echo "M6_SEALED_RECORD_PRESENT_OK=${M6_SEALED_RECORD_PRESENT_OK}"
  echo "M6_SEALED_RECORD_NO_PLACEHOLDER_OK=${M6_SEALED_RECORD_NO_PLACEHOLDER_OK}"
  echo "M6_SEALED_RECORD_PR_MAP_OK=${M6_SEALED_RECORD_PR_MAP_OK}"

  # M7-SEALED-RECORD
  echo "M7_SEALED_RECORD_PRESENT_OK=${M7_SEALED_RECORD_PRESENT_OK}"
  echo "M7_SEALED_RECORD_FORMAT_OK=${M7_SEALED_RECORD_FORMAT_OK}"
  echo "M7_SEALED_RECORD_NO_PLACEHOLDER_OK=${M7_SEALED_RECORD_NO_PLACEHOLDER_OK}"

  # ALGO-APPLY-E2E
  echo "ALGO_APPLY_FAILCLOSED_E2E_OK=${ALGO_APPLY_FAILCLOSED_E2E_OK}"
  echo "ALGO_APPLY_STATE_UNCHANGED_OK=${ALGO_APPLY_STATE_UNCHANGED_OK}"
  echo "ALGO_APPLY_REASON_CODE_PRESERVED_OK=${ALGO_APPLY_REASON_CODE_PRESERVED_OK}"
  # BUTLER-RUNTIME-V0
  echo "RUNTIME_V0_HTTP_OK=${RUNTIME_V0_HTTP_OK}"
  echo "RUNTIME_EGRESS_DENY_DEFAULT_OK=${RUNTIME_EGRESS_DENY_DEFAULT_OK}"
  echo "RUNTIME_SHADOW_ENDPOINT_OK=${RUNTIME_SHADOW_ENDPOINT_OK}"
  echo "RUNTIME_SHADOW_HEADERS_OK=${RUNTIME_SHADOW_HEADERS_OK}"
  echo "BFF_SHADOW_FIREFORGET_OK=${BFF_SHADOW_FIREFORGET_OK}"
  echo "RUNTIME_SHADOW_PROOF_OK=${RUNTIME_SHADOW_PROOF_OK}"

  # BUTLER-SSOT
  echo "BUTLER_SSOT_V1_1_OK=${BUTLER_SSOT_V1_1_OK}"

  # ALGO-CORE-GATEWAY-DOC
  echo "ALGO_CORE_GATEWAY_DEPLOY_DOC_OK=${ALGO_CORE_GATEWAY_DEPLOY_DOC_OK}"

  echo "ALGO_CORE_PROD_SSOT_PRESENT_OK=${ALGO_CORE_PROD_SSOT_PRESENT_OK}"
  echo "ALGO_CORE_PROD_ENV_TEMPLATE_PRESENT_OK=${ALGO_CORE_PROD_ENV_TEMPLATE_PRESENT_OK}"
  echo "ALGO_CORE_KEYGEN_SCRIPT_PRESENT_OK=${ALGO_CORE_KEYGEN_SCRIPT_PRESENT_OK}"
  echo "ALGO_CORE_PROD_FAILCLOSED_ENFORCED_OK=${ALGO_CORE_PROD_FAILCLOSED_ENFORCED_OK}"
  # ALGO-CORE-04
  echo "ALGO_CORE_RUNTIME_ROUTE_PRESENT_OK=${ALGO_CORE_RUNTIME_ROUTE_PRESENT_OK}"
  echo "ALGO_CORE_RUNTIME_PROD_FAILCLOSED_KEYS_OK=${ALGO_CORE_RUNTIME_PROD_FAILCLOSED_KEYS_OK}"

  # ALGO-CORE-01~03
  echo "ALGO_META_ONLY_FAILCLOSED_OK=${ALGO_META_ONLY_FAILCLOSED_OK}"
  echo "ALGO_THREE_BLOCKS_NO_RAW_OK=${ALGO_THREE_BLOCKS_NO_RAW_OK}"
  echo "ALGO_SIGNED_MANIFEST_VERIFY_OK=${ALGO_SIGNED_MANIFEST_VERIFY_OK}"
  echo "ALGO_P95_HOOK_OK=${ALGO_P95_HOOK_OK}"
  echo "ALGO_CORE_DELIVERED_KEYSET_PRESENT_OK=${ALGO_CORE_DELIVERED_KEYSET_PRESENT_OK}"
  echo "ALGO_CORE_DELIVERED_KEYSET_GUARD_OK=${ALGO_CORE_DELIVERED_KEYSET_GUARD_OK}"

  # P4-P0-02 (Supplychain Permissions + Signer Uniqueness)
  echo "SUPPLYCHAIN_PERMISSIONS_SCOPED_V1_OK=${SUPPLYCHAIN_PERMISSIONS_SCOPED_V1_OK}"
  echo "SLSA_SIGNER_WORKFLOW_UNIQUE_V1_OK=${SLSA_SIGNER_WORKFLOW_UNIQUE_V1_OK}"
  echo "ONPREM_PROOF_STRICT_SKIPPED=${ONPREM_PROOF_STRICT_SKIPPED}"

  # P4-P0-03 (AGENT) Workspace FS sandbox
  echo "WORKSPACE_FS_SANDBOX_V1_OK=${WORKSPACE_FS_SANDBOX_V1_OK}"
  echo "WORKSPACE_FS_SANDBOX_TRAVERSAL_BLOCK_OK=${WORKSPACE_FS_SANDBOX_TRAVERSAL_BLOCK_OK}"
  echo "WORKSPACE_FS_SANDBOX_ABS_BLOCK_OK=${WORKSPACE_FS_SANDBOX_ABS_BLOCK_OK}"
  echo "WORKSPACE_FS_SANDBOX_SYMLINK_BLOCK_OK=${WORKSPACE_FS_SANDBOX_SYMLINK_BLOCK_OK}"
  echo "WORKSPACE_FS_SANDBOX_WRITE_NEWFILE_BLOCK_OK=${WORKSPACE_FS_SANDBOX_WRITE_NEWFILE_BLOCK_OK}"

  # P4-P0-04 (AGENT) High-risk approval gate + taint propagation
  echo "HIGH_RISK_BLOCK_WITHOUT_APPROVAL_OK=${HIGH_RISK_BLOCK_WITHOUT_APPROVAL_OK}"
  echo "HIGH_RISK_TAINT_PROPAGATION_OK=${HIGH_RISK_TAINT_PROPAGATION_OK}"
  echo "HIGH_RISK_APPROVAL_FORMAT_OK=${HIGH_RISK_APPROVAL_FORMAT_OK}"
  echo "HIGH_RISK_TAINT_STRING_BLOCK_OK=${HIGH_RISK_TAINT_STRING_BLOCK_OK}"
  echo "HIGH_RISK_TAINT_HIGH_SCOPE_ENFORCED_OK=${HIGH_RISK_TAINT_HIGH_SCOPE_ENFORCED_OK}"

  # P4-P0-05 (AGENT) Skills runtime manifest + capability gate
  echo "SKILLS_MANIFEST_PRESENT_OK=${SKILLS_MANIFEST_PRESENT_OK}"
  echo "SKILLS_CAPABILITY_GATE_BLOCK_OK=${SKILLS_CAPABILITY_GATE_BLOCK_OK}"
  echo "SKILLS_META_ONLY_PROOF_OK=${SKILLS_META_ONLY_PROOF_OK}"
  echo "SKILLS_META_ONLY_REQUIRED_OK=${SKILLS_META_ONLY_REQUIRED_OK}"

  # P4-P0-06 (AGENT) Task queue idempotency + concurrency + atomic writes
  echo "TASK_QUEUE_IDEMPOTENCY_OK=${TASK_QUEUE_IDEMPOTENCY_OK}"
  echo "TASK_QUEUE_CONCURRENCY_OK=${TASK_QUEUE_CONCURRENCY_OK}"
  echo "TASK_QUEUE_PARTIAL_WRITE_0_OK=${TASK_QUEUE_PARTIAL_WRITE_0_OK}"
  echo "TASK_QUEUE_LOCK_NO_TIMEOUT_OK=${TASK_QUEUE_LOCK_NO_TIMEOUT_OK}"
  echo "TASK_QUEUE_ASYNC_TASK_FN_OK=${TASK_QUEUE_ASYNC_TASK_FN_OK}"
  echo "TASK_QUEUE_YIELD_WAIT_OK=${TASK_QUEUE_YIELD_WAIT_OK}"

  # P4-P1-01 (AGENT) Instruction layers meta-only
  echo "INSTRUCTION_RAW_0_OK=${INSTRUCTION_RAW_0_OK}"
  echo "INSTRUCTION_HASH_ONLY_OK=${INSTRUCTION_HASH_ONLY_OK}"
  echo "INSTRUCTION_LAYER_REGISTRY_OK=${INSTRUCTION_LAYER_REGISTRY_OK}"

  # P4-P1-02 (AGENT) Reason code registry
  echo "REASON_CODE_REGISTRY_PRESENT_OK=${REASON_CODE_REGISTRY_PRESENT_OK}"
  echo "REASON_CODE_NOT_REGISTERED_BLOCK_OK=${REASON_CODE_NOT_REGISTERED_BLOCK_OK}"

  # P4-P1-03 (AGENT) Path scope SSOT
  echo "PATH_SCOPE_SSOT_PRESENT_OK=${PATH_SCOPE_SSOT_PRESENT_OK}"
  echo "PATH_SCOPE_NO_PLACEHOLDER_OK=${PATH_SCOPE_NO_PLACEHOLDER_OK}"
  echo "PATH_SCOPE_DRIFT_0_OK=${PATH_SCOPE_DRIFT_0_OK}"

  # P4-AI-01 (AI) Golden vectors v2
  echo "AI_GOLDEN_VECTORS_V2_OK=${AI_GOLDEN_VECTORS_V2_OK}"
  echo "AI_DETERMINISM_FINGERPRINT_OK=${AI_DETERMINISM_FINGERPRINT_OK}"

  # P5-AI-P0-01 (AI) Golden vectors v2 raw text 0 v1
  echo "AI_GOLDEN_VECTORS_V2_RAW_TEXT_0_OK=${AI_GOLDEN_VECTORS_V2_RAW_TEXT_0_OK}"
  echo "AI_GOLDEN_VECTORS_V2_NO_ARRAY_OK=${AI_GOLDEN_VECTORS_V2_NO_ARRAY_OK}"
  echo "AI_GOLDEN_VECTORS_V2_PRESENT_OK=${AI_GOLDEN_VECTORS_V2_PRESENT_OK}"

  # P5-AI-P0-02 (AI) Canonicalize nested preserve v2
  echo "CANONICALIZE_V2_SSOT_OK=${CANONICALIZE_V2_SSOT_OK}"
  echo "CANONICALIZE_V2_NO_DUP_OK=${CANONICALIZE_V2_NO_DUP_OK}"
  echo "AI_INPUT_CANON_PRESERVE_NESTED_V1_OK=${AI_INPUT_CANON_PRESERVE_NESTED_V1_OK}"

  # P4-AI-02 (AI) Variance outlier guard
  echo "AI_VARIANCE_MEASUREMENTS_SOURCE_OK=${AI_VARIANCE_MEASUREMENTS_SOURCE_OK}"
  echo "AI_VARIANCE_OK=${AI_VARIANCE_OK}"
  echo "AI_OUTLIER_RATIO_OK=${AI_OUTLIER_RATIO_OK}"

  # P4-AI-03 (AI) Energy proxy SSOT + stability gate
  echo "AI_ENERGY_PROXY_DEFINITION_SSOT_OK=${AI_ENERGY_PROXY_DEFINITION_SSOT_OK}"
  echo "AI_ENERGY_MEASUREMENTS_SOURCE_OK=${AI_ENERGY_MEASUREMENTS_SOURCE_OK}"
  echo "AI_ENERGY_STABILITY_OK=${AI_ENERGY_STABILITY_OK}"

  # P5-AI-P0-03 (AI) Energy proxy fail-open/close v2
  echo "AI_ENERGY_PROXY_MEASUREMENT_WINDOW_SSOT_OK=${AI_ENERGY_PROXY_MEASUREMENT_WINDOW_SSOT_OK}"
  echo "AI_ENERGY_PROXY_NONTRIVIAL_SUM_GT0_OK=${AI_ENERGY_PROXY_NONTRIVIAL_SUM_GT0_OK}"
  echo "AI_ENERGY_PROXY_P50_POSITIVE_OK=${AI_ENERGY_PROXY_P50_POSITIVE_OK}"
  echo "AI_ENERGY_PROXY_EXPECTED_REQUIRED_OK=${AI_ENERGY_PROXY_EXPECTED_REQUIRED_OK}"

  # P5-P0-01 (ONPREM) Latest pass marker v1
  echo "ONPREM_LATEST_PASS_MARKER_V1_OK=${ONPREM_LATEST_PASS_MARKER_V1_OK}"
  echo "ONPREM_LATEST_NO_FAILURE_TEXT_V1_OK=${ONPREM_LATEST_NO_FAILURE_TEXT_V1_OK}"
  echo "ONPREM_LATEST_SENSITIVE_SCAN_V1_OK=${ONPREM_LATEST_SENSITIVE_SCAN_V1_OK}"
  echo "ONPREM_LATEST_LONG_LINE_BLOCK_V1_OK=${ONPREM_LATEST_LONG_LINE_BLOCK_V1_OK}"

  # P5-P0-02 (PREFLIGHT) One-shot preflight (single-source)
  echo "PREFLIGHT_ONE_SHOT_V1_PRESENT_OK=${PREFLIGHT_ONE_SHOT_V1_PRESENT_OK}"
  echo "PREFLIGHT_ONE_SHOT_V1_RUNBOOK_OK=${PREFLIGHT_ONE_SHOT_V1_RUNBOOK_OK}"

  # P5-P0-03 (EGRESS) Egress deny proof harness v1
  echo "EGRESS_DENY_PROOF_HARNESS_V1_OK=${EGRESS_DENY_PROOF_HARNESS_V1_OK}"
  echo "EGRESS_DENY_RUNBOOK_V1_OK=${EGRESS_DENY_RUNBOOK_V1_OK}"
  echo "EGRESS_DENY_PROOF_EXECUTES_IN_SANDBOX_OK=${EGRESS_DENY_PROOF_EXECUTES_IN_SANDBOX_OK}"

  # P5-P1-01 (AI) Nightly long-run tiered policy v1
  echo "AI_NIGHTLY_WORKFLOW_PRESENT_V1_OK=${AI_NIGHTLY_WORKFLOW_PRESENT_V1_OK}"
  echo "AI_AB_BENCH_RUNS_TIERED_V1_OK=${AI_AB_BENCH_RUNS_TIERED_V1_OK}"

  # P5-P1-02 (OPS) Report pipeline upload v1
  echo "OPS_REPORT_PIPELINE_V1_OK=${OPS_REPORT_PIPELINE_V1_OK}"
  echo "OPS_REPORT_ARCHIVE_DATED_V1_OK=${OPS_REPORT_ARCHIVE_DATED_V1_OK}"

  # P5-P1-03 (PATH_SCOPE) Scanners must reference SSOT v2
  echo "PATH_SCOPE_ENFORCED_V2_OK=${PATH_SCOPE_ENFORCED_V2_OK}"

  # P5-AI-P2-01 (AI) Feature digest v1
  echo "AI_FEATURE_DIGEST_V1_PRESENT_OK=${AI_FEATURE_DIGEST_V1_PRESENT_OK}"
  echo "AI_FEATURE_DIGEST_V1_ALLOWED_KEYS_OK=${AI_FEATURE_DIGEST_V1_ALLOWED_KEYS_OK}"
  echo "AI_FEATURE_DIGEST_V1_VALUE_LIMITS_OK=${AI_FEATURE_DIGEST_V1_VALUE_LIMITS_OK}"

  # P5-AI-P2-02 (AI) Golden vectors v2 diversity v1
  echo "AI_GOLDEN_VECTORS_V2_DIVERSITY_OK=${AI_GOLDEN_VECTORS_V2_DIVERSITY_OK}"
  echo "AI_GOLDEN_VECTORS_NO_RAW_OK=${AI_GOLDEN_VECTORS_NO_RAW_OK}"

  # P5-AI-P2-03 (AI) Energy proxy normalized v2
  echo "AI_ENERGY_PROXY_NORMALIZED_V2_OK=${AI_ENERGY_PROXY_NORMALIZED_V2_OK}"
  echo "AI_ENERGY_PROXY_STABILITY_V2_OK=${AI_ENERGY_PROXY_STABILITY_V2_OK}"

  # P5-PLAT-P0-04 (PLAT) Pack core bypass block v1
  echo "PACK_CORE_BYPASS_POLICY_V1_OK=${PACK_CORE_BYPASS_POLICY_V1_OK}"
  echo "PACK_FORBIDDEN_IMPORT_BLOCK_V1_OK=${PACK_FORBIDDEN_IMPORT_BLOCK_V1_OK}"
  echo "PACK_MANIFEST_SCHEMA_LOCK_V1_OK=${PACK_MANIFEST_SCHEMA_LOCK_V1_OK}"

  # P5-PLAT-P0-05 (PLAT) No raw in logs/exceptions v1
  echo "NO_RAW_IN_LOGS_POLICY_V1_OK=${NO_RAW_IN_LOGS_POLICY_V1_OK}"
  echo "NO_RAW_IN_REPORTS_SCAN_V1_OK=${NO_RAW_IN_REPORTS_SCAN_V1_OK}"
  echo "SENSITIVE_PATTERN_BLOCK_V1_OK=${SENSITIVE_PATTERN_BLOCK_V1_OK}"
  echo "LONG_LINE_BLOCK_V1_OK=${LONG_LINE_BLOCK_V1_OK}"

  # P5-PLAT-P1-04 (PLAT) MVP package demo harness v1
  echo "DEMO_DOC_SEARCH_ALLOW_OK=${DEMO_DOC_SEARCH_ALLOW_OK}"
  echo "DEMO_DOC_SEARCH_BLOCK_OK=${DEMO_DOC_SEARCH_BLOCK_OK}"
  echo "DEMO_DOC_SEARCH_META_ONLY_OK=${DEMO_DOC_SEARCH_META_ONLY_OK}"
  echo "DEMO_DOC_SEARCH_REQUEST_ID_JOIN_OK=${DEMO_DOC_SEARCH_REQUEST_ID_JOIN_OK}"
  echo "DEMO_WRITE_APPROVE_ALLOW_OK=${DEMO_WRITE_APPROVE_ALLOW_OK}"
  echo "DEMO_WRITE_APPROVE_BLOCK_OK=${DEMO_WRITE_APPROVE_BLOCK_OK}"
  echo "DEMO_WRITE_APPROVE_META_ONLY_OK=${DEMO_WRITE_APPROVE_META_ONLY_OK}"
  echo "DEMO_WRITE_APPROVE_REQUEST_ID_JOIN_OK=${DEMO_WRITE_APPROVE_REQUEST_ID_JOIN_OK}"
  echo "DEMO_HELPDESK_ALLOW_OK=${DEMO_HELPDESK_ALLOW_OK}"
  echo "DEMO_HELPDESK_BLOCK_OK=${DEMO_HELPDESK_BLOCK_OK}"
  echo "DEMO_HELPDESK_META_ONLY_OK=${DEMO_HELPDESK_META_ONLY_OK}"
  echo "DEMO_HELPDESK_REQUEST_ID_JOIN_OK=${DEMO_HELPDESK_REQUEST_ID_JOIN_OK}"

  # P5-PLAT-P1-05 (PLAT) Assist compute default OFF lock v1
  echo "ASSIST_COMPUTE_POLICY_V1_OK=${ASSIST_COMPUTE_POLICY_V1_OK}"
  echo "ASSIST_COMPUTE_DEFAULT_OFF_LOCK_V1_OK=${ASSIST_COMPUTE_DEFAULT_OFF_LOCK_V1_OK}"
  echo "DOD_SINGLE_OUTPUT_GUARD_V1_OK=${DOD_SINGLE_OUTPUT_GUARD_V1_OK}"
  echo "PREFLIGHT_ACTION_CONSUMED_BY_REQUIRED_WORKFLOWS_OK=${PREFLIGHT_ACTION_CONSUMED_BY_REQUIRED_WORKFLOWS_OK}"
  echo "PREFLIGHT_DUPLICATE_PREP_PATH_0_OK=${PREFLIGHT_DUPLICATE_PREP_PATH_0_OK}"
  echo "ONPREM_LATEST_WHITELIST_ONLY_V2_OK=${ONPREM_LATEST_WHITELIST_ONLY_V2_OK}"
  echo "ONPREM_LATEST_LONG_LINE_SCAN_EOF_SAFE_OK=${ONPREM_LATEST_LONG_LINE_SCAN_EOF_SAFE_OK}"
  echo "AI_ENERGY_PROXY_SSOT_RUNS_CONSUMED_OK=${AI_ENERGY_PROXY_SSOT_RUNS_CONSUMED_OK}"
  echo "AI_ENERGY_PROXY_SSOT_MIN_P50_CONSUMED_OK=${AI_ENERGY_PROXY_SSOT_MIN_P50_CONSUMED_OK}"
  echo "ONE_COMMAND_VERIFY_V1_OK=${ONE_COMMAND_VERIFY_V1_OK}"
  echo "ARTIFACT_BUNDLE_POLICY_V1_OK=${ARTIFACT_BUNDLE_POLICY_V1_OK}"
  echo "ARTIFACT_BUNDLE_PRESENT_OK=${ARTIFACT_BUNDLE_PRESENT_OK}"
  echo "ARTIFACT_BUNDLE_META_ONLY_OK=${ARTIFACT_BUNDLE_META_ONLY_OK}"
  echo "BUILD_STAMP_GENERATION_SSOT_V1_OK=${BUILD_STAMP_GENERATION_SSOT_V1_OK}"
  echo "PROBES_SSOT_V1_OK=${PROBES_SSOT_V1_OK}"
  echo "PROBES_PATHS_MATCH_APP_V1_OK=${PROBES_PATHS_MATCH_APP_V1_OK}"
  echo "DOCKER_IT_NET_DB_SVCNAME_V1_OK=${DOCKER_IT_NET_DB_SVCNAME_V1_OK}"
  echo "HOST_DOCKER_INTERNAL_FORBIDDEN_OK=${HOST_DOCKER_INTERNAL_FORBIDDEN_OK}"
  echo "DOCKERLESS_REPORT_RUN_OK=${DOCKERLESS_REPORT_RUN_OK}"
  echo "DOCKERLESS_REPORT_DEGRADED_DOCKER_KEYS_OK=${DOCKERLESS_REPORT_DEGRADED_DOCKER_KEYS_OK}"
  echo "DOCKERLESS_REPORT_STATIC_POLICY_ALWAYS_ON_OK=${DOCKERLESS_REPORT_STATIC_POLICY_ALWAYS_ON_OK}"
  echo "EXEC_MODE_PER_LINE_NO_EXCEPTION_TEXT_OK=${EXEC_MODE_PER_LINE_NO_EXCEPTION_TEXT_OK}"
  echo "EXEC_MODE_LATENCY_MEASURE_PRESENT_OK=${EXEC_MODE_LATENCY_MEASURE_PRESENT_OK}"
  echo "EXEC_MODE_LATENCY_MISSING_BLOCK_OK=${EXEC_MODE_LATENCY_MISSING_BLOCK_OK}"
  echo "OUTPUT_ROOT_SSOT_V1_OK=${OUTPUT_ROOT_SSOT_V1_OK}"
  echo "CI_DOCS_WRITE_BLOCK_V1_OK=${CI_DOCS_WRITE_BLOCK_V1_OK}"
  echo "REPO_GUARD_KEYS_ONLY_MODE_OK=${REPO_GUARD_KEYS_ONLY_MODE_OK}"
  echo "META_ONLY_OUTPUT_GUARD_V1_OK=${META_ONLY_OUTPUT_GUARD_V1_OK}"
  echo "PATH_SCOPE_READ_REQUIRED_OK=${PATH_SCOPE_READ_REQUIRED_OK}"
  echo "BFF_SECRET_SCHEMA_V1_OK=${BFF_SECRET_SCHEMA_V1_OK}"
  echo "BFF_SECRET_FORMAT_OK=${BFF_SECRET_FORMAT_OK}"
  echo "BFF_SECRET_EMPTY_STRING_BLOCK_OK=${BFF_SECRET_EMPTY_STRING_BLOCK_OK}"
  echo "BFF_SECRET_SCHEMA_V1_SKIPPED=${BFF_SECRET_SCHEMA_V1_SKIPPED}"
  echo "AUTODECISION_POLICY_V1_OK=${AUTODECISION_POLICY_V1_OK}"
  echo "AUTODECISION_OUTPUT_PRESENT_OK=${AUTODECISION_OUTPUT_PRESENT_OK}"
  echo "AUTODECISION_REASON_CODE_ONLY_OK=${AUTODECISION_REASON_CODE_ONLY_OK}"
  echo "RELEASE_GATE_POLICY_V1_OK=${RELEASE_GATE_POLICY_V1_OK}"
  echo "RELEASE_GATE_WIRING_V1_OK=${RELEASE_GATE_WIRING_V1_OK}"
  echo "RELEASE_BLOCKED_WITHOUT_GATES_OK=${RELEASE_BLOCKED_WITHOUT_GATES_OK}"
  echo "DOD_KV_BLOCK_END=1"
}
# EXIT: on non-zero exit emit failed guard once then cleanup; success(0) emits nothing extra
trap 'rc=$?; if [ "$rc" -ne 0 ]; then emit_failed_guard_once; fi; cleanup' EXIT
trap 'emit_failed_guard_once' ERR

run_guard() {
  local name="$1"
  shift
  CURRENT_GUARD="$name"
  local script_or_cmd=("$@")

  echo "== guard: ${name} =="

  local tmp_out
  tmp_out="$(mktemp)"

  if "${script_or_cmd[@]}" >"$tmp_out" 2>&1; then
    :
  else
    grep -vE '^[A-Z0-9_]+_OK=[0-9]+$' "$tmp_out" || true
    rm -f "$tmp_out"
    echo "FAIL: ${name}"
    exit 1
  fi

  while IFS= read -r line; do
    case "$line" in
      *_OK=0|*_OK=1)
        key="${line%%=*}"
        val="${line#*=}"
        if echo "$key" | grep -Eq '^[A-Z0-9_]+_OK$' && echo "$val" | grep -Eq '^[01]$'; then
          # shellcheck disable=SC2163
          eval "$key=$val"
        fi
        ;;
    esac
  done < <(grep -E '^[A-Z0-9_]+_OK=[01]$' "$tmp_out" || true)

  grep -vE '^[A-Z0-9_]+_OK=[0-9]+$' "$tmp_out" || true

  rm -f "$tmp_out"
}

# Keys-only mode (P0-01 dockerless proof): minimal guards for report contract only
if [[ "${REPO_GUARD_KEYS_ONLY:-0}" == "1" ]]; then
  REPO_GUARD_KEYS_ONLY_MODE_OK=1
  CURRENT_GUARD="policy headers schema v1"
  echo "== guard: POLICY_HEADERS_SCHEMA_V1 (keys-only) =="
  run_guard "policy headers schema v1" bash scripts/verify/verify_policy_headers_schema_v1.sh
  POLICY_HEADERS_SCHEMA_V1_OK=1
  POLICY_HEADERS_RULE_DESCRIPTION_PRESENT_OK=1

  CURRENT_GUARD="build stamp SSOT v1"
  echo "== guard: Generate build stamp SSOT v1 (keys-only) =="
  run_guard "build stamp SSOT v1" bash scripts/ops/gen_build_stamp_v1.sh
  BUILD_STAMP_GENERATION_SSOT_V1_OK=1

  CURRENT_GUARD="probes SSOT v1"
  run_guard "probes SSOT v1 (PR-P0-DEPLOY-01)" bash scripts/verify/verify_probes_ssot_v1.sh
  PROBES_SSOT_V1_OK=1
  PROBES_PATHS_MATCH_APP_V1_OK=1

  CURRENT_GUARD="host docker internal forbidden v1"
  echo "== guard: host.docker.internal forbidden scan v1 (keys-only) =="
  run_guard "host docker internal forbidden v1" bash scripts/verify/verify_host_docker_internal_forbidden_v1.sh
  HOST_DOCKER_INTERNAL_FORBIDDEN_OK=1

  CURRENT_GUARD="docker it-net db svcname v1"
  echo "== guard: docker it-net db svcname v1 (keys-only) =="
  docker_ok=0
  if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
    docker_ok=1
  fi
  if [ "$docker_ok" -eq 1 ]; then
    run_guard "docker it-net db svcname v1" bash scripts/verify/verify_docker_it_net_db_svcname_v1.sh
    DOCKER_IT_NET_DB_SVCNAME_V1_OK=1
  else
    echo "== guard: docker unavailable -> skip docker it-net verify (emit DOCKER_IT_NET_DB_SVCNAME_V1_OK=0) =="
  fi

  exit 0
fi

# Existing guards
echo "== guard: verify purity (no install in verify) =="
run_guard "verify purity (no install in verify)" bash scripts/verify/verify_verify_purity_no_install.sh
VERIFY_PURITY_NO_INSTALL_OK=1

echo "== guard: verify purity full scope (SSOT allowlist) =="
run_guard "verify purity full scope" bash scripts/verify/verify_verify_purity_full_scope.sh
VERIFY_PURITY_FULL_SCOPE_OK=1
VERIFY_PURITY_ALLOWLIST_SSOT_OK=1
VERIFY_PURITY_FULL_SCOPE_OK=1
VERIFY_PURITY_ALLOWLIST_SSOT_OK=1

echo "== guard: verify no /dev/tcp in verify (P3-PREP-00) =="
run_guard "verify no /dev/tcp in verify" bash scripts/verify/verify_no_dev_tcp_in_verify_v1.sh
VERIFY_NO_DEV_TCP_IN_VERIFY_OK=1

echo "== guard: verify ripgrep guard present v1 (P3-PREP-00, enforcement pending) =="
run_guard "verify ripgrep guard present v1" bash scripts/verify/verify_ripgrep_guard_present_v1.sh
VERIFY_RIPGREP_GUARD_PRESENT_V1_OK=1

echo "== guard: verify workflow preflight present v1 (P3-PLAT-01) =="
run_guard "workflow preflight ssot v1" bash scripts/verify/verify_workflow_preflight_present_v1.sh

echo "== guard: verify runtime guard helpers adopted v1 (P3-PLAT-02) =="
run_guard "verify runtime guard helpers adopted v1" bash scripts/verify/verify_runtime_guard_helpers_adopted_v1.sh
RUNTIME_GUARD_HELPERS_V1_ADOPTED_OK=1

echo "== guard: repo contracts hygiene =="
run_guard "repo contracts hygiene" bash scripts/verify/verify_repo_contracts_hygiene.sh
REPO_CONTRACTS_HYGIENE_OK=1

echo "== guard: product-verify workflow template (SSOT) =="
run_guard "product-verify workflow template" bash scripts/verify/verify_product_verify_workflows.sh
PRODUCT_VERIFY_WORKFLOW_TEMPLATE_OK=1

echo "== guard: docs banned phrases =="
run_guard "docs banned phrases" bash scripts/verify/verify_docs_banned_phrases.sh
DOCS_NO_BANNED_PHRASES_OK=1

echo "== guard: onprem real-world proof (strict) =="
if [ "$ONPREM_PROOF_STRICT_ENFORCE" = "1" ]; then
  run_guard "onprem real-world proof" bash scripts/verify/verify_onprem_real_world_proof.sh
  ONPREM_REAL_WORLD_PROOF_OK=1
  ONPREM_REAL_WORLD_PROOF_FORMAT_OK=1
else
  echo "SKIP: onprem strict proof (ONPREM_PROOF_STRICT_ENFORCE=0, PR/merge_group default)"
  ONPREM_PROOF_STRICT_SKIPPED=1
fi

echo "== guard: onprem proof latest + archive =="
run_guard "onprem proof latest" bash scripts/verify/verify_onprem_proof_latest.sh
ONPREM_PROOF_LATEST_PRESENT_OK=1
ONPREM_PROOF_ARCHIVE_LINKED_OK=1
ONPREM_PROOF_SENSITIVE_SCAN_OK=1

echo "== guard: P5-P0-01 ONPREM_LATEST_PASS_MARKER_V1 (pass marker only, no failure text) =="
run_guard "P5-P0-01 onprem latest pass marker v1" bash scripts/verify/verify_onprem_real_world_proof_latest_v1.sh
ONPREM_LATEST_PASS_MARKER_V1_OK=1
ONPREM_LATEST_NO_FAILURE_TEXT_V1_OK=1
ONPREM_LATEST_SENSITIVE_SCAN_V1_OK=1
ONPREM_LATEST_LONG_LINE_BLOCK_V1_OK=1

echo "== guard: onprem proof freshness =="
run_guard "onprem proof freshness" bash scripts/verify/verify_onprem_proof_freshness.sh
ONPREM_PROOF_LATEST_FRESH_OK=1

echo "== guard: forbid log-grep verdict patterns =="
run_guard "forbid log-grep verdict patterns" bash scripts/verify/verify_no_log_grep_verdict.sh
NO_LOG_GREP_VERDICT_OK=1

echo "== guard: forbid install fallback in verify scripts =="
run_guard "forbid install fallback" bash scripts/verify/verify_no_npm_install_fallback.sh
NO_NPM_INSTALL_FALLBACK_OK=1

echo "== guard: JCS single source =="
run_guard "JCS single source" bash scripts/verify/verify_jcs_single_source.sh
CANONICALIZE_SHARED_SINGLE_SOURCE_OK=1

# SLSA provenance min: product-verify-supplychain 워크플로에서만 실행
# (repo-guards에서는 파일이 생성되지 않으므로 건너뜀)
if [[ "${GITHUB_WORKFLOW:-}" == "product-verify-supplychain" ]]; then
  echo "== guard: SLSA provenance min (CI fail-closed) =="
  run_guard "SLSA provenance min" bash scripts/verify/verify_slsa_provenance_min.sh
else
  echo "== guard: SLSA provenance min (SKIP: not in product-verify-supplychain workflow) =="
fi

run_guard "repo OK contamination guard" bash scripts/verify/verify_repo_no_ok_contamination.sh
OK_CONTAMINATION_REPO_GUARD_OK=1

run_guard "repo merge_group coverage guard" bash scripts/verify/verify_repo_required_checks_have_merge_group.sh
REQUIRED_CHECK_MERGE_GROUP_COVERAGE_OK=1

run_guard "repo SSOT doc gate" bash scripts/verify/verify_repo_ssot_no_placeholders.sh
SSOT_PLACEHOLDER_GUARD_OK=1

run_guard "repo required check name stability" bash scripts/verify/verify_repo_required_check_name_stability.sh
REQUIRED_CHECK_NAME_STABILITY_OK=1

run_guard "repo no skipped bypass" bash scripts/verify/verify_repo_no_skipped_bypass.sh
REQUIRED_CHECK_NO_SKIPPED_BYPASS_OK=1

# New guards (H3.4-prep)
echo "== guard: lockfiles tracked =="
run_guard "lockfiles tracked" bash scripts/verify/verify_lockfiles_tracked.sh
LOCKFILES_TRACKED_OK=1

echo "== guard: required check context single (SSOT) =="
run_guard "required check context single" bash scripts/verify/verify_required_check_context_ssot_single.sh
REQUIRED_CHECK_CONTEXT_SINGLE_OK=1

echo "== guard: dual-impl drift (audit_append) =="
run_guard "audit_append no drift" bash scripts/verify/verify_audit_append_no_drift.sh
AUDIT_APPEND_NO_DRIFT_OK=1

echo "== guard: dual-impl drift (counters) =="
run_guard "counters no drift" bash scripts/verify/verify_counters_no_drift.sh
COUNTERS_NO_DRIFT_OK=1

echo "== guard: .artifacts not tracked =="
run_guard ".artifacts not tracked" bash scripts/verify/verify_no_tracked_artifacts.sh
ARTIFACTS_NOT_TRACKED_OK=1

echo "== guard: required workflows always-reported (SSOT) =="
run_guard "required workflows always-reported" bash scripts/verify/verify_required_workflows_always_reported.sh
REQUIRED_WORKFLOWS_ALWAYS_REPORTED_OK=1

echo "== guard: policy header bundle fail-closed =="
run_guard "policy header bundle" bash scripts/verify/verify_policy_header_bundle_failclosed.sh
POLICY_HEADERS_REQUIRED_OK=1
POLICY_HEADERS_FAILCLOSED_OK=1

echo "== guard: POLICY_HEADERS_SCHEMA_V1 (PR-P0-BFF-01) =="
run_guard "policy headers schema v1" bash scripts/verify/verify_policy_headers_schema_v1.sh
POLICY_HEADERS_SCHEMA_V1_OK=1
POLICY_HEADERS_RULE_DESCRIPTION_PRESENT_OK=1

echo "== guard: meta-only allowlist enforced =="
run_guard "meta-only allowlist enforced" bash scripts/verify/verify_meta_only_allowlist_enforced.sh
META_ONLY_ALLOWLIST_ENFORCED_OK=1

echo "== guard: algo-core 01~03 (meta-only + 3 blocks + signed manifest + p95) =="
run_guard "algo-core 01~03" bash scripts/verify/verify_algo_core_01_03.sh
ALGO_META_ONLY_FAILCLOSED_OK=1
ALGO_THREE_BLOCKS_NO_RAW_OK=1
ALGO_SIGNED_MANIFEST_VERIFY_OK=1
ALGO_P95_HOOK_OK=1

echo "== guard: algo-core-06 prod key management (SSOT + keygen + fail-closed) =="
run_guard "algo-core-06 prod keys" bash scripts/verify/verify_algo_core_06_prod_keys.sh
ALGO_CORE_PROD_SSOT_PRESENT_OK=1
ALGO_CORE_PROD_ENV_TEMPLATE_PRESENT_OK=1
ALGO_CORE_KEYGEN_SCRIPT_PRESENT_OK=1
ALGO_CORE_PROD_FAILCLOSED_ENFORCED_OK=1

echo "== guard: butler runtime v0 skeleton =="
run_guard "butler runtime v0 skeleton" bash scripts/verify/verify_runtime_v0_skeleton.sh
RUNTIME_V0_HTTP_OK=1
RUNTIME_EGRESS_DENY_DEFAULT_OK=1

echo "== guard: butler runtime shadow mode =="
run_guard "butler runtime shadow" bash scripts/verify/verify_runtime_shadow.sh
RUNTIME_SHADOW_ENDPOINT_OK=1
RUNTIME_SHADOW_HEADERS_OK=1
BFF_SHADOW_FIREFORGET_OK=1
RUNTIME_SHADOW_PROOF_OK=1



echo "== guard: runtime egress env proof (compose + k8s) =="
run_guard "runtime egress env proof" bash scripts/verify/verify_runtime_egress_env_proof.sh
RUNTIME_EGRESS_ENV_TEMPLATE_OK=1
RUNTIME_EGRESS_ENV_PROOF_OK=1

echo "== guard: modelpack v0 signed manifest + fail-closed =="
run_guard "modelpack v0 failclosed" bash scripts/verify/verify_modelpack_v0_failclosed.sh
MODEL_PACK_SCHEMA_SSOT_OK=1
MODEL_PACK_SIGNED_MANIFEST_VERIFY_OK=1
MODEL_PACK_MANIFEST_MISSING_FAILCLOSED_OK=1
MODEL_PACK_HASH_MISMATCH_FAILCLOSED_OK=1
MODEL_PACK_SIGNATURE_INVALID_FAILCLOSED_OK=1

echo "== guard: model pack apply fail-closed e2e =="
run_guard "model pack apply fail-closed e2e" bash scripts/verify/verify_model_pack_apply_failclosed_e2e.sh
ALGO_APPLY_FAILCLOSED_E2E_OK=1
ALGO_APPLY_STATE_UNCHANGED_OK=1
ALGO_APPLY_REASON_CODE_PRESERVED_OK=1

echo "== guard: model pack v0 identity + expiry =="
run_guard "model pack v0 identity + expiry" bash scripts/verify/verify_modelpack_v0_identity_expiry.sh
MODEL_PACK_V0_ID_FIELDS_REQUIRED_OK=1
MODEL_PACK_V0_EXPIRES_ENFORCED_OK=1

echo "== guard: model pack v0 compat =="
run_guard "model pack v0 compat" bash scripts/verify/verify_modelpack_v0_compat.sh
MODEL_PACK_V0_COMPAT_FIELDS_REQUIRED_OK=1
MODEL_PACK_V0_COMPAT_ENFORCED_OK=1

echo "== guard: ondevice model exec v0 (Track B-1) =="
run_guard "ondevice model exec v0" bash scripts/verify/verify_ondevice_model_exec_v0.sh
ONDEVICE_MODEL_EXEC_V0_OK=1
MODEL_PACK_VERIFY_REQUIRED_OK=1
ONDEVICE_EGRESS_DENY_PROOF_OK=1
ONDEVICE_NO_RAW_STORAGE_OK=1

echo "== guard: ondevice real compute once (Track B-1.1) =="
run_guard "ondevice real compute once" bash scripts/verify/verify_ondevice_real_compute_once.sh
ONDEVICE_REAL_COMPUTE_ONCE_OK=1
ONDEVICE_RESULT_FINGERPRINT_OK=1
ONDEVICE_COMPUTE_PATH_ONDEVICE_OK=1

echo "== guard: ondevice inference v0 (P2-AI-01) =="
run_guard "ondevice inference v0" bash scripts/verify/verify_ondevice_inference_v0.sh
ONDEVICE_MODEL_PACK_LOADED_OK=1
ONDEVICE_MODEL_PACK_IDENTITY_OK=1
ONDEVICE_INFERENCE_ONCE_OK=1
ONDEVICE_OUTPUT_FINGERPRINT_OK=1
ONDEVICE_INFER_USES_PACK_PARAMS_OK=1

echo "== guard: ai v1 modules (perf/rerank/calib/propensity) =="
run_guard "ai v1 modules" bash scripts/verify/verify_ai_v1_modules.sh
AI_PERF_HARNESS_V1_OK=1
AI_RERANK_NEARTIE_V1_OK=1
AI_CALIB_V1_OK=1
AI_PROPENSITY_IPS_SNIPS_V1_OK=1
AI_DETERMINISM_OK=1
AI_P95_BUDGET_OK=1
AI_NEARTIE_SWAP_BUDGET_OK=1

echo "== guard: ai budget gates (P2-AI-02: latency/mem/energy_proxy) =="
run_guard "ai budget gates" bash scripts/verify/verify_ai_budget_gates_v0.sh

echo "== guard: algo determinism gate (D0) =="
run_guard "algo determinism gate (D0)" bash scripts/verify/verify_algo_determinism_gate.sh
ALGO_DETERMINISM_VERIFIED_OK=1
ALGO_DETERMINISM_HASH_MATCH_OK=1
ALGO_DETERMINISM_MODE_REPORTED_OK=1

echo "== guard: ops hub v0 meta-only =="
run_guard "ops hub v0 meta-only" bash scripts/verify/verify_ops_hub_v0_meta_only.sh
OPS_HUB_META_SCHEMA_SSOT_OK=1
OPS_HUB_NO_RAW_TEXT_GUARD_OK=1
OPS_HUB_REPORT_V0_OK=1
OPS_HUB_REPORT_INPUT_META_ONLY_OK=1

echo "== guard: ops hub traceability (request_id join) =="
run_guard "ops hub traceability" bash scripts/verify/verify_ops_hub_traceability.sh
OPS_HUB_TRACEABILITY_OK=1
OPS_HUB_TRACEABILITY_REPORT_OK=1
OPS_HUB_TRACEABILITY_NO_RAW_OK=1

echo "== guard: ops hub trace realpath (persistence + idempotency) =="
run_guard "ops hub trace realpath" bash scripts/verify/verify_ops_hub_trace_realpath.sh
OPS_HUB_TRACE_REALPATH_PERSISTED_OK=1
OPS_HUB_TRACE_REALPATH_JOINABLE_OK=1
OPS_HUB_TRACE_REALPATH_NO_RAW_OK=1
OPS_HUB_TRACE_REALPATH_IDEMPOTENT_OK=1

echo "== guard: ops hub trace service store =="
run_guard "ops hub trace service store" bash scripts/verify/verify_ops_hub_trace_service_store.sh
OPS_HUB_TRACE_SERVICE_PERSIST_OK=1
OPS_HUB_TRACE_IDEMPOTENT_OK=1
OPS_HUB_TRACE_NO_RAW_OK=1
OPS_HUB_TRACE_JOINABLE_OK=1

echo "== guard: trace security lockdown (A-3.1) =="
run_guard "trace security lockdown (A-3.1)" bash scripts/verify/verify_trace_security_lockdown.sh
OPS_HUB_TRACE_LOCAL_ONLY_OR_AUTH_OK=1

echo "== guard: ops hub trace db store (P1-PLAT-01) =="
run_guard "ops hub trace db store" bash scripts/verify/verify_ops_hub_trace_db_store.sh
OPS_HUB_TRACE_DB_SCHEMA_OK=1
OPS_HUB_TRACE_REQUEST_ID_INDEX_OK=1
OPS_HUB_TRACE_IDEMPOTENT_UPSERT_OK=1
OPS_HUB_TRACE_CONCURRENCY_SAFE_OK=1
OPS_HUB_TRACE_EVENT_SCHEMA_V1_OK=1

echo "== guard: reason codes v1 single source =="
run_guard "reason codes v1 single source" bash scripts/verify/verify_reason_codes_v1_single_source.sh
REASON_CODE_SINGLE_SOURCE_OK=1
REASON_CODE_DRIFT_GUARD_OK=1

echo "== guard: m6 sealed record =="
run_guard "m6 sealed record" bash scripts/verify/verify_m6_sealed_record.sh
M6_SEALED_RECORD_PRESENT_OK=1
M6_SEALED_RECORD_NO_PLACEHOLDER_OK=1
M6_SEALED_RECORD_PR_MAP_OK=1

echo "== guard: m7 sealed record =="
run_guard "m7 sealed record" bash scripts/verify/verify_m7_sealed_record.sh
M7_SEALED_RECORD_PRESENT_OK=1
M7_SEALED_RECORD_FORMAT_OK=1
M7_SEALED_RECORD_NO_PLACEHOLDER_OK=1

echo "== guard: butler ssot v1.1 =="
run_guard "butler ssot v1.1" bash scripts/verify/verify_butler_ssot_v1_1.sh
BUTLER_SSOT_V1_1_OK=1

echo "== guard: algo-core gateway deployment doc =="
run_guard "algo-core gateway deploy doc" bash scripts/verify/verify_algo_core_gateway_deploy_doc.sh
ALGO_CORE_GATEWAY_DEPLOY_DOC_OK=1

echo "== guard: meta-only validator parity (client/server single source) =="
run_guard "meta-only validator parity" bash scripts/verify/verify_meta_only_validator_parity.sh
META_ONLY_VALIDATOR_PARITY_OK=1

run_guard "meta-only validator single source (Track A-2)" bash scripts/verify/verify_meta_only_validator_single_source.sh
META_ONLY_VALIDATOR_SINGLE_SOURCE_OK=1
META_ONLY_VALIDATOR_NO_DUPLICATION_OK=1
META_ONLY_VALIDATOR_V1_CJS_PRESENT_OK=1

echo "== guard: algo-core-04 runtime wiring assets =="
run_guard "algo-core-04 runtime wiring assets" bash scripts/verify/verify_algo_core_04_runtime_wiring.sh
ALGO_CORE_RUNTIME_ROUTE_PRESENT_OK=1
ALGO_CORE_RUNTIME_PROD_FAILCLOSED_KEYS_OK=1

echo "== guard: export two-step + auditv2 =="
run_guard "export two-step + auditv2" bash scripts/verify/verify_export_two_step_auditv2.sh
EXPORT_TWO_STEP_OK=1
EXPORT_APPROVAL_AUDITED_OK=1
EXPORT_APPROVAL_AUDIT_EVENT_V2_WRITTEN_OK=1
EXPORT_APPROVE_AUDIT_V2_OK=1

echo "== guard: mock network zero =="
run_guard "mock network zero" bash scripts/verify/verify_mock_network_zero.sh
MOCK_NETWORK_ZERO_OK=1

echo "== guard: perf p95 budget gate =="
run_guard "perf p95 budget gate" bash scripts/verify/verify_perf_p95_budget.sh
PERF_P95_BUDGET_DEFINED_OK=1
PERF_P95_CONTRACT_OK=1
PERF_P95_REGRESSION_BLOCK_OK=1

echo "== guard: perf p95 baseline pinned (SSOT) =="
run_guard "perf p95 baseline pinned" bash scripts/verify/verify_perf_p95_baseline_pinned.sh
PERF_P95_BASELINE_PINNED_OK=1

echo "== guard: onprem compose quickstart assets =="
run_guard "onprem compose quickstart assets" bash scripts/verify/verify_onprem_compose_quickstart_assets.sh
ONPREM_COMPOSE_ASSETS_OK=1

echo "== guard: onprem helm skeleton assets =="
run_guard "onprem helm skeleton assets" bash scripts/verify/verify_onprem_helm_skeleton_assets.sh
ONPREM_HELM_SKELETON_OK=1

echo "== guard: helm secrets enabled guard =="
run_guard "helm secrets enabled guard" bash scripts/verify/verify_onprem_helm_secrets_guard.sh
ONPREM_HELM_SECRETS_GUARD_OK=1

echo "== guard: onprem helm template smoke ==" 
run_guard "onprem helm template smoke" bash scripts/verify/verify_onprem_helm_template_smoke.sh
ONPREM_HELM_TEMPLATE_SMOKE_OK=1
ONPREM_HELM_TEMPLATE_SECRET_REF_OK=1

echo "== guard: onprem signing key policy (prod fail-closed) =="
run_guard "onprem signing key policy" bash scripts/verify/verify_onprem_signing_key_policy.sh
ONPREM_SIGNING_KEY_REQUIRED_OK=1
ONPREM_EPHEMERAL_KEY_FORBIDDEN_OK=1
ONPREM_KEY_ID_ALLOWLIST_OK=1

echo "== guard: onprem signed bundle verify (manifest+sig) =="
run_guard "onprem signed bundle verify" bash scripts/verify/verify_onprem_signed_bundle.sh
ONPREM_SIGNED_BUNDLE_OK=1

echo "== guard: onprem install/verify assets == "
run_guard "onprem install/verify assets" bash scripts/verify/verify_onprem_install_verify_assets.sh
ONPREM_INSTALL_VERIFY_OK=1

echo "== guard: onprem delivered keyset (SSOT) =="
SSOT_FILE="docs/ops/contracts/ONPREM_DELIVERED_KEYS_SSOT.md"
test -s "$SSOT_FILE" || { echo "BLOCK: missing SSOT file: $SSOT_FILE"; exit 1; }
ONPREM_DELIVERED_KEYSET_PRESENT_OK=1

# Parse required keys from SSOT and ensure each variable is exactly 1
REQ_KEYS="$(sed -n 's/^- //p' "$SSOT_FILE" | tr -d '\r' | sed '/^$/d')"
test -n "$REQ_KEYS" || { echo "BLOCK: SSOT has no required keys"; exit 1; }
while IFS= read -r k; do
  v="${!k:-}"
  if [[ "$v" != "1" ]]; then
    echo "BLOCK: delivered key not satisfied: ${k}=${v:-<unset>}"
    exit 1
  fi
done <<< "$REQ_KEYS"
ONPREM_DELIVERED_KEYSET_GUARD_OK=1

echo "== guard: test event selection (reason_code requires action) =="
run_guard "test event selection" bash scripts/verify/verify_test_event_selection_guard.sh
TEST_EVENT_SELECTION_GUARD_OK=1

echo "== guard: prod delivered keyset (SSOT) =="
SSOT_FILE="docs/ops/contracts/PROD_DELIVERED_KEYS_SSOT.md"
test -s "$SSOT_FILE" || { echo "BLOCK: missing SSOT file: $SSOT_FILE"; exit 1; }
PROD_DELIVERED_KEYSET_PRESENT_OK=1

REQ_KEYS="$(sed -n 's/^- //p' "$SSOT_FILE" | tr -d '\r' | sed '/^$/d')"
test -n "$REQ_KEYS" || { echo "BLOCK: SSOT has no required keys"; exit 1; }

# Each required key must be exactly 1 in this script's variables (no recursion)
while IFS= read -r k; do
  v="${!k:-}"
  if [[ "$v" != "1" ]]; then
    echo "BLOCK: delivered key not satisfied: ${k}=${v:-<unset>}"
    exit 1
  fi
done <<< "$REQ_KEYS"

PROD_DELIVERED_KEYSET_GUARD_OK=1

echo "== guard: algo-core delivered keyset (SSOT) =="
SSOT_FILE="docs/ops/contracts/ALGO_CORE_DELIVERED_KEYS_SSOT.md"
test -s "$SSOT_FILE" || { echo "BLOCK: missing SSOT file: $SSOT_FILE"; exit 1; }
ALGO_CORE_DELIVERED_KEYSET_PRESENT_OK=1

REQ_KEYS="$(sed -n 's/^- //p' "$SSOT_FILE" | tr -d '\r' | sed '/^$/d')"
test -n "$REQ_KEYS" || { echo "BLOCK: SSOT has no required keys"; exit 1; }

while IFS= read -r k; do
  v="${!k:-}"
  if [[ "$v" != "1" ]]; then
    echo "BLOCK: delivered key not satisfied: ${k}=${v:-<unset>}"
    exit 1
  fi
done <<< "$REQ_KEYS"

ALGO_CORE_DELIVERED_KEYSET_GUARD_OK=1

echo "== guard: web ux-01 assets (E2E fixture) =="
run_guard "web ux-01 assets" bash scripts/verify/verify_web_ux_01_assets.sh
WEB_E2E_MODE_SWITCH_WIRED_OK=1
WEB_E2E_MOCK_NETWORK_ZERO_OK=1
WEB_E2E_LIVE_HEADER_BUNDLE_OK=1

echo "== guard: web ux-03 assets (export approve auditv2 e2e) =="
run_guard "web ux-03 assets" bash scripts/verify/verify_web_ux_03_assets.sh
WEB_E2E_EXPORT_TWO_STEP_OK=1
WEB_E2E_EXPORT_AUDITV2_OK=1
EXPORT_APPROVE_IDEMPOTENT_OK=1
EXPORT_APPROVE_AUDIT_ID_RETURNED_OK=1

echo "== guard: web ux-04 assets (p95 marks parity e2e) =="
run_guard "web ux-04 assets" bash scripts/verify/verify_web_ux_04_assets.sh
PERF_E2E_EVENT_MARKS_WIRED_OK=1
PERF_E2E_MARKS_PARITY_OK=1

echo "== guard: perf real pipeline p95 (wired + ops hub join + budget) =="
run_guard "perf real pipeline p95" bash scripts/verify/verify_perf_real_pipeline_p95.sh
PERF_REAL_PIPELINE_WIRED_OK=1
PERF_REAL_PIPELINE_REQUEST_ID_JOIN_OK=1
PERF_REAL_PIPELINE_NO_RAW_OK=1
PERF_REAL_PIPELINE_P95_BUDGET_OK=1
PERF_REAL_PIPELINE_MIN_SAMPLES_OK=1
PERF_REAL_PIPELINE_VARIANCE_OK=1

echo "== guard: web ux-08 assets (meta-only negative suite) =="
run_guard "web ux-08 assets" bash scripts/verify/verify_web_ux_08_assets.sh
WEB_META_ONLY_NEGATIVE_SUITE_OK=1

echo "== guard: workflow-lint sealed (no attestation) =="
FILE=".github/workflows/workflow-lint.yml"

# P2) fail-closed: 파일이 없거나 못 읽으면 즉시 차단
if [ ! -r "$FILE" ]; then
  echo "BLOCK: $FILE missing or unreadable"
  exit 1
fi

# P1) YAML-safe matching: 공백/따옴표 변형 허용 + 대소문자 변형 허용
WRITE_RE='["'"'"']?[Ww][Rr][Ii][Tt][Ee]["'"'"']?'

# permissions: write-all (job/top-level 어디든)도 차단
if grep -Eq "^[[:space:]]*permissions[[:space:]]*:[[:space:]]*$WRITE_RE-all[[:space:]]*$" "$FILE"; then
  echo "BLOCK: workflow-lint permissions write-all"
  exit 1
fi

# 금지 키가 write면 차단 (공백/따옴표 변형 포함, 들여쓰기 허용)
if grep -Eq "^[[:space:]]+(id-token|attestations|artifact-metadata)[[:space:]]*:[[:space:]]*.*[Ww][Rr][Ii][Tt][Ee]" "$FILE"; then
  echo "BLOCK: workflow-lint has forbidden attestation permissions"
  exit 1
fi

# attest-build-provenance 스텝이 있으면 차단(버전 무관)
if grep -Eq "attest-build-provenance" "$FILE"; then
  echo "BLOCK: workflow-lint must not run attest-build-provenance"
  exit 1
fi

echo "WORKFLOW_LINT_SEALED_OK=1"

echo "== guard: P3-AI-01 fingerprint canonical v1 =="
run_guard "P3-AI-01 fingerprint canonical v1" bash scripts/verify/verify_fingerprint_canonical_v1.sh

echo "== guard: P3-AI-01 canonicalize single source v1 =="
run_guard "P3-AI-01 canonicalize single source v1" bash scripts/verify/verify_canonicalize_single_source_v1.sh

echo "== guard: P5-AI-P0-02 canonicalize nested preserve v2 (single source + nested effect) =="
run_guard "P5-AI-P0-02 canonicalize single source no dup v2" bash scripts/verify/verify_canonicalize_single_source_no_dup_v2.sh
CANONICALIZE_V2_SSOT_OK=1
CANONICALIZE_V2_NO_DUP_OK=1
run_guard "P5-AI-P0-02 fingerprint nested effect v1" bash scripts/verify/verify_fingerprint_nested_effect_v1.sh
AI_INPUT_CANON_PRESERVE_NESTED_V1_OK=1

echo "== guard: P3-AI-02 fingerprint input policy v1 =="
run_guard "P3-AI-02 fingerprint input policy v1" bash scripts/verify/verify_fingerprint_input_policy_v1.sh

echo "== guard: P3-AI-03 golden vectors meta-only v1 =="
run_guard "P3-AI-03 golden vectors meta-only v1" bash scripts/verify/verify_golden_vectors_v1.sh

echo "== guard: P3-AI-04 energy proxy cpu_time_ms v1 =="
run_guard "P3-AI-04 energy proxy cpu_time_ms v1" bash scripts/verify/verify_energy_proxy_nontrivial_v1.sh

echo "== guard: P3-PLAT-03 trace bind/auth policy v1 =="
run_guard "P3-PLAT-03 trace bind/auth policy v1" bash scripts/verify/verify_trace_bind_auth_policy_v1.sh

# P3-PLAT-04 track manifest v1 (gated: only enforce when manifest file exists)
if [ -f docs/ops/contracts/TRACK_MANIFEST_V1.txt ]; then
  run_guard "P3-PLAT-04 track manifest v1" bash scripts/verify/verify_track_manifest_v1.sh
else
  echo "== guard: P3-PLAT-04 track manifest v1 =="
  echo "SKIP: TRACK_MANIFEST_V1.txt not present yet (gated)"
  echo "TRACK_MANIFEST_V1_OK=0"
  echo "TRACK_MANIFEST_KEYS_EXIST_OK=0"
fi

echo "== guard: Generate build stamp SSOT v1 (PR-P0-DEPLOY-00) =="
run_guard "build stamp SSOT v1" bash scripts/ops/gen_build_stamp_v1.sh
BUILD_STAMP_GENERATION_SSOT_V1_OK=1

run_guard "probes SSOT v1 (PR-P0-DEPLOY-01)" bash scripts/verify/verify_probes_ssot_v1.sh
PROBES_SSOT_V1_OK=1
PROBES_PATHS_MATCH_APP_V1_OK=1

# 1) 정적 가드: Docker 유무와 무관하게 항상 실행
echo "== guard: host.docker.internal forbidden scan v1 =="
run_guard "host docker internal forbidden v1" bash scripts/verify/verify_host_docker_internal_forbidden_v1.sh
HOST_DOCKER_INTERNAL_FORBIDDEN_OK=1

# 2) Docker 의존 가드: Docker 가능할 때만 실행
echo "== guard: docker it-net db svcname v1 (PR-P0-DEPLOY-03) =="
docker_ok=0
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  docker_ok=1
fi

if [ "$docker_ok" -eq 1 ]; then
  run_guard "docker it-net db svcname v1" bash scripts/verify/verify_docker_it_net_db_svcname_v1.sh
  DOCKER_IT_NET_DB_SVCNAME_V1_OK=1
else
  echo "== guard: docker unavailable -> skip docker it-net verify (emit DOCKER_IT_NET_DB_SVCNAME_V1_OK=0) =="
fi

if [[ -z "${DATABASE_URL:-}" ]] && [[ -z "${EXPORT_SIGN_SECRET:-}" ]]; then
  echo "== guard: bff secret schema v1 (PR-P0-DEPLOY-02) =="
  echo "SKIP: BFF secret schema (DATABASE_URL and EXPORT_SIGN_SECRET not set)"
  BFF_SECRET_SCHEMA_V1_SKIPPED=1
else
  run_guard "bff secret schema v1 (PR-P0-DEPLOY-02)" bash scripts/verify/verify_bff_secret_schema_v1.sh
  BFF_SECRET_SCHEMA_V1_OK=1
  BFF_SECRET_FORMAT_OK=1
  BFF_SECRET_EMPTY_STRING_BLOCK_OK=1
fi

run_guard "DIST_FRESHNESS_POLICY_V1" bash scripts/verify/verify_dist_freshness_v1.sh

run_guard "P4-P0-01 required workflows merge_group v1" bash scripts/verify/verify_required_workflows_merge_group_v1.sh

echo "== guard: P4-P0-02 supplychain permissions scoped v1 =="
run_guard "P4-P0-02 supplychain permissions scoped v1" bash scripts/verify/verify_attestation_permissions_scoped_v1.sh
SUPPLYCHAIN_PERMISSIONS_SCOPED_V1_OK=1

echo "== guard: P4-P0-02 supplychain signer unique v1 =="
run_guard "P4-P0-02 supplychain signer unique v1" bash scripts/verify/verify_attestation_signer_unique_v1.sh
SLSA_SIGNER_WORKFLOW_UNIQUE_V1_OK=1

echo "== guard: P4-P0-03 workspace fs sandbox v1 =="
run_guard "P4-P0-03 workspace fs sandbox v1" bash scripts/verify/verify_workspace_fs_sandbox_v1.sh
WORKSPACE_FS_SANDBOX_V1_OK=1
WORKSPACE_FS_SANDBOX_TRAVERSAL_BLOCK_OK=1
WORKSPACE_FS_SANDBOX_ABS_BLOCK_OK=1
WORKSPACE_FS_SANDBOX_SYMLINK_BLOCK_OK=1
WORKSPACE_FS_SANDBOX_WRITE_NEWFILE_BLOCK_OK=1

echo "== guard: P4-P0-04 high-risk approval gate + taint propagation v1 =="
run_guard "P4-P0-04 high-risk approval gate v1" bash scripts/verify/verify_high_risk_gate_v1.sh
HIGH_RISK_BLOCK_WITHOUT_APPROVAL_OK=1
HIGH_RISK_TAINT_PROPAGATION_OK=1
HIGH_RISK_APPROVAL_FORMAT_OK=1
HIGH_RISK_TAINT_STRING_BLOCK_OK=1
HIGH_RISK_TAINT_HIGH_SCOPE_ENFORCED_OK=1

echo "== guard: P4-P0-05 skills runtime manifest + capability gate v1 =="
run_guard "P4-P0-05 skills runtime v1" bash scripts/verify/verify_skills_runtime_v1.sh
SKILLS_MANIFEST_PRESENT_OK=1
SKILLS_CAPABILITY_GATE_BLOCK_OK=1
SKILLS_META_ONLY_PROOF_OK=1
SKILLS_META_ONLY_REQUIRED_OK=1

echo "== guard: P4-P0-06 task queue idempotency + concurrency + atomic writes v1 =="
run_guard "P4-P0-06 task queue v1" bash scripts/verify/verify_task_queue_v1.sh
TASK_QUEUE_IDEMPOTENCY_OK=1
TASK_QUEUE_CONCURRENCY_OK=1
TASK_QUEUE_PARTIAL_WRITE_0_OK=1
TASK_QUEUE_LOCK_NO_TIMEOUT_OK=1
TASK_QUEUE_ASYNC_TASK_FN_OK=1
TASK_QUEUE_YIELD_WAIT_OK=1

echo "== guard: P4-P1-01 instruction layers meta-only (raw=0, hash/scope only, fail-closed) =="
run_guard "P4-P1-01 instruction layers v1" bash scripts/verify/verify_instruction_layers_v1.sh
INSTRUCTION_RAW_0_OK=1
INSTRUCTION_HASH_ONLY_OK=1
INSTRUCTION_LAYER_REGISTRY_OK=1

echo "== guard: P4-P1-02 reason_code registry (unregistered BLOCK, single source) =="
run_guard "P4-P1-02 reason_code registry v1" bash scripts/verify/verify_reason_code_registry_v1.sh
REASON_CODE_REGISTRY_PRESENT_OK=1
REASON_CODE_NOT_REGISTERED_BLOCK_OK=1
REASON_CODE_SINGLE_SOURCE_OK=1

echo "== guard: P4-P1-03 path scope SSOT (scan drift=0, fail-closed) =="
run_guard "P4-P1-03 path scope SSOT v1" bash scripts/verify/verify_path_scope_ssot_v1.sh
PATH_SCOPE_SSOT_PRESENT_OK=1
PATH_SCOPE_NO_PLACEHOLDER_OK=1
PATH_SCOPE_DRIFT_0_OK=1

echo "== guard: P4-AI-01 golden vectors v2 (determinism + fingerprint validation) =="
run_guard "P4-AI-01 golden vectors v2" bash scripts/verify/verify_ai_golden_vectors_v2.sh
AI_GOLDEN_VECTORS_V2_OK=1
AI_DETERMINISM_FINGERPRINT_OK=1

echo "== guard: P5-AI-P0-01 golden vectors v2 raw text 0 v1 (meta-only, no raw text fields) =="
run_guard "P5-AI-P0-01 golden vectors v2 raw text 0 v1" bash scripts/verify/verify_ai_golden_vectors_v2_raw_text_0_v1.sh
AI_GOLDEN_VECTORS_V2_RAW_TEXT_0_OK=1
AI_GOLDEN_VECTORS_V2_NO_ARRAY_OK=1
AI_GOLDEN_VECTORS_V2_PRESENT_OK=1

echo "== guard: P4-AI-02 variance outlier guard (p50/p95 variance + outlier ratio) =="
run_guard "P4-AI-02 variance outlier v1" bash scripts/verify/verify_ai_variance_outlier_v1.sh
AI_VARIANCE_MEASUREMENTS_SOURCE_OK=1
AI_VARIANCE_OK=1
AI_OUTLIER_RATIO_OK=1

echo "== guard: P4-AI-03 energy proxy SSOT + stability gate (measurements required, fail-closed) =="
run_guard "P4-AI-03 energy proxy v1" bash scripts/verify/verify_ai_energy_proxy_v1.sh
AI_ENERGY_PROXY_DEFINITION_SSOT_OK=1

echo "== guard: P5-AI-P0-03 energy proxy fail-open/close v2 (p50>0, sum>0, expected required, no skip branch) =="
run_guard "P5-AI-P0-03 energy proxy v2" bash scripts/verify/verify_energy_proxy_v2.sh
AI_ENERGY_PROXY_MEASUREMENT_WINDOW_SSOT_OK=1
AI_ENERGY_PROXY_NONTRIVIAL_SUM_GT0_OK=1
AI_ENERGY_PROXY_P50_POSITIVE_OK=1
AI_ENERGY_PROXY_EXPECTED_REQUIRED_OK=1
AI_ENERGY_MEASUREMENTS_SOURCE_OK=1
AI_ENERGY_STABILITY_OK=1

echo "== guard: P5-P0-02 PREFLIGHT_ONE_SHOT_V1 presence (verify=판정만) =="
run_guard "PREFLIGHT_ONE_SHOT_V1" bash scripts/verify/verify_preflight_one_shot_v1_presence.sh
PREFLIGHT_ONE_SHOT_V1_PRESENT_OK=1
PREFLIGHT_ONE_SHOT_V1_RUNBOOK_OK=1

echo "== guard: P5-P0-03 EGRESS_DENY_PROOF_HARNESS_V1 (harness + runbook + decision-only verify) =="
run_guard "EGRESS_DENY_PROOF_HARNESS_V1" bash scripts/verify/verify_egress_deny_proof_harness_v1.sh
EGRESS_DENY_PROOF_HARNESS_V1_OK=1
EGRESS_DENY_RUNBOOK_V1_OK=1
EGRESS_DENY_PROOF_EXECUTES_IN_SANDBOX_OK=1

echo "== guard: P5-P1-01 NIGHTLY_LONG_RUN_V1 (tiered runs policy + nightly workflow) =="
run_guard "P5-P1-01 NIGHTLY_LONG_RUN_V1" bash scripts/verify/verify_ai_ab_bench_policy_v1.sh
AI_NIGHTLY_WORKFLOW_PRESENT_V1_OK=1
AI_AB_BENCH_RUNS_TIERED_V1_OK=1

echo "== guard: P5-P1-02 OPS_REPORT_PIPELINE_UPLOAD_V1 =="
run_guard "P5-P1-02 OPS_REPORT_PIPELINE_UPLOAD_V1" bash scripts/verify/verify_ops_report_pipeline_v1.sh
OPS_REPORT_PIPELINE_V1_OK=1
OPS_REPORT_ARCHIVE_DATED_V1_OK=1

echo "== guard: P5-P1-03 PATH_SCOPE_ENFORCED_V2 =="
run_guard "P5-P1-03 PATH_SCOPE_ENFORCED_V2" bash scripts/verify/verify_path_scope_enforced_v2.sh
PATH_SCOPE_ENFORCED_V2_OK=1

echo "== guard: P5-AI-P2-01 FEATURE_DIGEST_V1 =="
run_guard "P5-AI-P2-01 FEATURE_DIGEST_V1" bash scripts/verify/verify_feature_digest_v1.sh
AI_FEATURE_DIGEST_V1_PRESENT_OK=1
AI_FEATURE_DIGEST_V1_ALLOWED_KEYS_OK=1
AI_FEATURE_DIGEST_V1_VALUE_LIMITS_OK=1

echo "== guard: P5-AI-P2-02 GOLDEN_VECTORS_V2_DIVERSITY_V1 =="
run_guard "P5-AI-P2-02 GOLDEN_VECTORS_V2_DIVERSITY_V1" bash scripts/verify/verify_ai_golden_vectors_v2_diversity_v1.sh
AI_GOLDEN_VECTORS_V2_DIVERSITY_OK=1
AI_GOLDEN_VECTORS_NO_RAW_OK=1

echo "== guard: P5-AI-P2-03 ENERGY_PROXY_NORMALIZED_V2 =="
run_guard "P5-AI-P2-03 ENERGY_PROXY_NORMALIZED_V2" bash scripts/verify/verify_energy_proxy_normalized_v2.sh
AI_ENERGY_PROXY_NORMALIZED_V2_OK=1
AI_ENERGY_PROXY_STABILITY_V2_OK=1

echo "== guard: P5-PLAT-P0-04 PACK_CORE_BYPASS_BLOCK_V1 =="
run_guard "P5-PLAT-P0-04 PACK_CORE_BYPASS_BLOCK_V1" bash scripts/verify/verify_pack_core_bypass_block_v1.sh
PACK_CORE_BYPASS_POLICY_V1_OK=1
PACK_FORBIDDEN_IMPORT_BLOCK_V1_OK=1
PACK_MANIFEST_SCHEMA_LOCK_V1_OK=1

echo "== guard: P5-PLAT-P0-05 NO_RAW_IN_LOGS_EXCEPTIONS_V1 =="
run_guard "P5-PLAT-P0-05 NO_RAW_IN_LOGS_EXCEPTIONS_V1" bash scripts/verify/verify_no_raw_in_logs_exceptions_v1.sh
NO_RAW_IN_LOGS_POLICY_V1_OK=1
NO_RAW_IN_REPORTS_SCAN_V1_OK=1
SENSITIVE_PATTERN_BLOCK_V1_OK=1
LONG_LINE_BLOCK_V1_OK=1

echo "== guard: P5-PLAT-P1-04 MVP_PACKAGE_DEMO_HARNESS_V1 =="
run_guard "P5-PLAT-P1-04 MVP_PACKAGE_DEMO_HARNESS_V1" bash scripts/verify/verify_mvp_package_demo_harness_v1.sh
DEMO_DOC_SEARCH_ALLOW_OK=1
DEMO_DOC_SEARCH_BLOCK_OK=1
DEMO_DOC_SEARCH_META_ONLY_OK=1
DEMO_DOC_SEARCH_REQUEST_ID_JOIN_OK=1
DEMO_WRITE_APPROVE_ALLOW_OK=1
DEMO_WRITE_APPROVE_BLOCK_OK=1
DEMO_WRITE_APPROVE_META_ONLY_OK=1
DEMO_WRITE_APPROVE_REQUEST_ID_JOIN_OK=1
DEMO_HELPDESK_ALLOW_OK=1
DEMO_HELPDESK_BLOCK_OK=1
DEMO_HELPDESK_META_ONLY_OK=1
DEMO_HELPDESK_REQUEST_ID_JOIN_OK=1

echo "== guard: P5-PLAT-P1-05 ASSIST_COMPUTE_DEFAULT_OFF_LOCK_V1 =="
run_guard "P5-PLAT-P1-05 ASSIST_COMPUTE_DEFAULT_OFF_LOCK_V1" bash scripts/verify/verify_assist_compute_default_off_lock_v1.sh
ASSIST_COMPUTE_POLICY_V1_OK=1
ASSIST_COMPUTE_DEFAULT_OFF_LOCK_V1_OK=1

run_guard "P5-PLAT-P1-06 DOD_SINGLE_OUTPUT_GUARD_V1" bash scripts/verify/verify_dod_single_output_guard_v1.sh

echo "== guard: P6-P0-01 PREFLIGHT_CONSUMED_EVERYWHERE_V1 (decision-only) =="
run_guard "P6-P0-01 preflight consumed everywhere v1" bash scripts/verify/verify_preflight_consumed_everywhere_v1.sh
PREFLIGHT_ACTION_CONSUMED_BY_REQUIRED_WORKFLOWS_OK=1
PREFLIGHT_DUPLICATE_PREP_PATH_0_OK=1

echo "== guard: P6-P0-02 ONPREM_LATEST_WHITELIST_ONLY_V2 (decision-only) =="
run_guard "P6-P0-02 onprem latest whitelist-only v2" bash scripts/verify/verify_onprem_latest_whitelist_only_v2.sh
ONPREM_LATEST_WHITELIST_ONLY_V2_OK=1
ONPREM_LATEST_LONG_LINE_SCAN_EOF_SAFE_OK=1

echo "== guard: P6-AI-P0-01 ENERGY_PROXY_SSOT_CONSUMED_V3 (decision-only) =="
run_guard "P6-AI-P0-01 energy proxy ssot consumed v3" bash scripts/verify/verify_energy_proxy_ssot_consumed_v3.sh
AI_ENERGY_PROXY_SSOT_RUNS_CONSUMED_OK=1
AI_ENERGY_PROXY_SSOT_MIN_P50_CONSUMED_OK=1

echo "== guard: P6-P0-03 ONE_COMMAND_VERIFY_V1 (decision-only) =="
run_guard "P6-P0-03 one command verify v1" bash scripts/verify/verify_one_command_verify_v1.sh
ONE_COMMAND_VERIFY_V1_OK=1

echo "== guard: P6-P0-04 ARTIFACT_BUNDLE_V1 (decision-only) =="
run_guard "P6-P0-04 artifact bundle v1" bash scripts/verify/verify_artifact_bundle_v1.sh
ARTIFACT_BUNDLE_POLICY_V1_OK=1
ARTIFACT_BUNDLE_PRESENT_OK=1
ARTIFACT_BUNDLE_META_ONLY_OK=1

echo "== guard: P6-P0-05 AUTODECISION_FROM_NIGHTLY_V1 (decision-only) =="
run_guard "P6-P0-05 autodecision from reports v1" bash scripts/verify/verify_autodecision_from_reports_v1.sh
AUTODECISION_POLICY_V1_OK=1
AUTODECISION_OUTPUT_PRESENT_OK=1
AUTODECISION_REASON_CODE_ONLY_OK=1

echo "== guard: P6-P1-01 RELEASE_GATE_CONNECT_V1 (decision-only) =="
run_guard "P6-P1-01 release gate connect v1" bash scripts/verify/verify_release_gate_connect_v1.sh
RELEASE_GATE_POLICY_V1_OK=1
RELEASE_GATE_WIRING_V1_OK=1
RELEASE_BLOCKED_WITHOUT_GATES_OK=1

# P17-P0-01 dockerless report proof
run_guard "dockerless report contract v1" bash scripts/verify/verify_dockerless_report_contract_v1.sh

run_guard "exec-mode no exception text v1" bash scripts/verify/verify_exec_mode_no_exception_text_v1.sh

run_guard "exec-mode latency present v1" bash scripts/verify/run_exec_mode_latency_present_v1.sh

run_guard "exec-mode schema ssot consumed v1" bash scripts/verify/verify_exec_mode_schema_ssot_consumed_v1.sh

run_guard "output root ssot v1" bash scripts/verify/verify_output_root_ssot_v1.sh

run_guard "ssot change contract v1" bash scripts/verify/verify_ssot_change_contract_v1.sh

run_guard "meta-only output guard v1" bash scripts/verify/verify_meta_only_output_guard_v1.sh
exit 0

run_guard "path scope read required v1" bash scripts/verify/verify_path_scope_read_required_v1.sh
