#!/usr/bin/env bash
set -euo pipefail

DEMO_DOC_SEARCH_ALLOW_OK=0
DEMO_DOC_SEARCH_BLOCK_OK=0
DEMO_DOC_SEARCH_META_ONLY_OK=0
DEMO_DOC_SEARCH_REQUEST_ID_JOIN_OK=0

DEMO_WRITE_APPROVE_ALLOW_OK=0
DEMO_WRITE_APPROVE_BLOCK_OK=0
DEMO_WRITE_APPROVE_META_ONLY_OK=0
DEMO_WRITE_APPROVE_REQUEST_ID_JOIN_OK=0

DEMO_HELPDESK_ALLOW_OK=0
DEMO_HELPDESK_BLOCK_OK=0
DEMO_HELPDESK_META_ONLY_OK=0
DEMO_HELPDESK_REQUEST_ID_JOIN_OK=0

trap 'echo "DEMO_DOC_SEARCH_ALLOW_OK=${DEMO_DOC_SEARCH_ALLOW_OK}";
      echo "DEMO_DOC_SEARCH_BLOCK_OK=${DEMO_DOC_SEARCH_BLOCK_OK}";
      echo "DEMO_DOC_SEARCH_META_ONLY_OK=${DEMO_DOC_SEARCH_META_ONLY_OK}";
      echo "DEMO_DOC_SEARCH_REQUEST_ID_JOIN_OK=${DEMO_DOC_SEARCH_REQUEST_ID_JOIN_OK}";
      echo "DEMO_WRITE_APPROVE_ALLOW_OK=${DEMO_WRITE_APPROVE_ALLOW_OK}";
      echo "DEMO_WRITE_APPROVE_BLOCK_OK=${DEMO_WRITE_APPROVE_BLOCK_OK}";
      echo "DEMO_WRITE_APPROVE_META_ONLY_OK=${DEMO_WRITE_APPROVE_META_ONLY_OK}";
      echo "DEMO_WRITE_APPROVE_REQUEST_ID_JOIN_OK=${DEMO_WRITE_APPROVE_REQUEST_ID_JOIN_OK}";
      echo "DEMO_HELPDESK_ALLOW_OK=${DEMO_HELPDESK_ALLOW_OK}";
      echo "DEMO_HELPDESK_BLOCK_OK=${DEMO_HELPDESK_BLOCK_OK}";
      echo "DEMO_HELPDESK_META_ONLY_OK=${DEMO_HELPDESK_META_ONLY_OK}";
      echo "DEMO_HELPDESK_REQUEST_ID_JOIN_OK=${DEMO_HELPDESK_REQUEST_ID_JOIN_OK}"' EXIT

# Ensure reports exist (generated by scripts/demo/run_demo_harness_v1.sh)
f1="docs/ops/reports/demo_doc_search_latest.json"
f2="docs/ops/reports/demo_write_approve_latest.json"
f3="docs/ops/reports/demo_helpdesk_ticket_latest.json"
test -f "$f1" || { echo "BLOCK: missing $f1"; exit 1; }
test -f "$f2" || { echo "BLOCK: missing $f2"; exit 1; }
test -f "$f3" || { echo "BLOCK: missing $f3"; exit 1; }

# Basic no-raw protections: long-line > 2000
for f in "$f1" "$f2" "$f3"; do
  if awk 'length($0) > 2000 { exit 10 }' "$f"; then :; else
    echo "BLOCK: long line detected in $f"; exit 1
  fi
done

# Banned key declarations (reuse SSOT if present; fail-closed if missing)
banned="docs/ops/contracts/META_ONLY_BANNED_KEYS_V1.txt"
test -f "$banned" || { echo "BLOCK: missing banned keys SSOT ($banned)"; exit 1; }
keys_re="$(paste -sd'|' "$banned")"
[ -n "$keys_re" ] || { echo "BLOCK: empty banned keys SSOT"; exit 1; }
if grep -EIn "\"(${keys_re})\"[[:space:]]*:" "$f1" "$f2" "$f3" >/dev/null 2>&1; then
  echo "BLOCK: banned key declaration detected in demo outputs"
  exit 1
fi

python3 - <<'PY'
import json, sys
files = [
  ("doc_search", "docs/ops/reports/demo_doc_search_latest.json",
   ["DOC_SEARCH_ALLOW_OK","DOC_SEARCH_BLOCK_OK","DOC_SEARCH_META_ONLY_OK","DOC_SEARCH_REQUEST_ID_JOIN_OK"]),
  ("write_approve", "docs/ops/reports/demo_write_approve_latest.json",
   ["WRITE_APPROVE_ALLOW_OK","WRITE_APPROVE_BLOCK_OK","WRITE_APPROVE_META_ONLY_OK","WRITE_APPROVE_REQUEST_ID_JOIN_OK"]),
  ("helpdesk", "docs/ops/reports/demo_helpdesk_ticket_latest.json",
   ["HELPDESK_ALLOW_OK","HELPDESK_BLOCK_OK","HELPDESK_META_ONLY_OK","HELPDESK_REQUEST_ID_JOIN_OK"]),
]
for name, path, keys in files:
  d = json.load(open(path,"r",encoding="utf-8"))
  chk = d.get("checks")
  if not isinstance(chk, dict):
    print("BLOCK: missing checks object in", path); sys.exit(1)
  for k in keys:
    if chk.get(k) != 1:
      print("BLOCK:", path, "missing/invalid", k); sys.exit(1)
print("OK")
PY

DEMO_DOC_SEARCH_ALLOW_OK=1
DEMO_DOC_SEARCH_BLOCK_OK=1
DEMO_DOC_SEARCH_META_ONLY_OK=1
DEMO_DOC_SEARCH_REQUEST_ID_JOIN_OK=1

DEMO_WRITE_APPROVE_ALLOW_OK=1
DEMO_WRITE_APPROVE_BLOCK_OK=1
DEMO_WRITE_APPROVE_META_ONLY_OK=1
DEMO_WRITE_APPROVE_REQUEST_ID_JOIN_OK=1

DEMO_HELPDESK_ALLOW_OK=1
DEMO_HELPDESK_BLOCK_OK=1
DEMO_HELPDESK_META_ONLY_OK=1
DEMO_HELPDESK_REQUEST_ID_JOIN_OK=1

exit 0
