"""Canonical machine-readable Helper1 v6.1 failure codes."""
from __future__ import annotations

from enum import Enum


class Helper1FailureCode(str, Enum):
    START_TREE_MISSING = "START_TREE_MISSING"
    START_TREE_MISMATCH = "START_TREE_MISMATCH"
    START_TREE_DIRTY = "START_TREE_DIRTY"
    START_TREE_CLOSURE_INCOMPLETE = "START_TREE_CLOSURE_INCOMPLETE"

    NO_EXPLICIT_PRODUCER = "NO_EXPLICIT_PRODUCER"
    PRODUCER_SUBJECT_MISMATCH = "PRODUCER_SUBJECT_MISMATCH"
    PRODUCER_RUN_MISMATCH = "PRODUCER_RUN_MISMATCH"
    ARTIFACT_DIGEST_MISMATCH = "ARTIFACT_DIGEST_MISMATCH"
    INVENTORY_INCOMPLETE = "INVENTORY_INCOMPLETE"
    UNSAFE_ARCHIVE = "UNSAFE_ARCHIVE"

    EMBEDDING_SPACE_MISMATCH = "EMBEDDING_SPACE_MISMATCH"
    ENCODER_ASSET_CLOSURE_INVALID = "ENCODER_ASSET_CLOSURE_INVALID"
    ENCODER_FALLBACK_FORBIDDEN = "ENCODER_FALLBACK_FORBIDDEN"

    EVALUATION_INPUT_UNAVAILABLE = "EVALUATION_INPUT_UNAVAILABLE"
    EVALUATION_GROUP_LEAKAGE = "EVALUATION_GROUP_LEAKAGE"
    EVALUATION_SOURCE_FAMILY_LEAKAGE = "EVALUATION_SOURCE_FAMILY_LEAKAGE"
    SEALED_TEST_REUSED_AFTER_TUNING = "SEALED_TEST_REUSED_AFTER_TUNING"
    RANKING_NONDETERMINISTIC = "RANKING_NONDETERMINISTIC"
    WRONG_WORKSPACE_LEAKAGE = "WRONG_WORKSPACE_LEAKAGE"
    STALE_GENERATION_LEAKAGE = "STALE_GENERATION_LEAKAGE"

    MEASUREMENT_RECOMPUTE_MISMATCH = "MEASUREMENT_RECOMPUTE_MISMATCH"
    METRIC_DENOMINATOR_ZERO = "METRIC_DENOMINATOR_ZERO"
    METRIC_COUNT_INVALID = "METRIC_COUNT_INVALID"
    THRESHOLD_POLICY_UNAPPROVED = "THRESHOLD_POLICY_UNAPPROVED"
    GROUNDING_BELOW_THRESHOLD = "GROUNDING_BELOW_THRESHOLD"
    REQUIRED_FACT_COVERAGE_BELOW_THRESHOLD = "REQUIRED_FACT_COVERAGE_BELOW_THRESHOLD"
    ABSTENTION_BELOW_THRESHOLD = "ABSTENTION_BELOW_THRESHOLD"
    FALSE_ABSTENTION_ABOVE_THRESHOLD = "FALSE_ABSTENTION_ABOVE_THRESHOLD"
    CANARY_LEAKAGE_DETECTED = "CANARY_LEAKAGE_DETECTED"
    RETRIEVAL_DEPENDENCE_NOT_PROVEN = "RETRIEVAL_DEPENDENCE_NOT_PROVEN"

    DEVICE_MEASUREMENT_MISSING = "DEVICE_MEASUREMENT_MISSING"
    DEVICE_RECEIPT_INVALID = "DEVICE_RECEIPT_INVALID"
    OBSERVATION_PROVENANCE_MISSING = "OBSERVATION_PROVENANCE_MISSING"
    NETWORK_EGRESS_NONZERO = "NETWORK_EGRESS_NONZERO"
    RAW_SAMPLE_MISMATCH = "RAW_SAMPLE_MISMATCH"


class Helper1V61Error(RuntimeError):
    """Typed failure that never carries raw user or artifact content."""

    def __init__(self, code: Helper1FailureCode) -> None:
        self.code = code
        super().__init__(code.value)
