#!/usr/bin/env bash
set -euo pipefail

# new_verifier_from_template_v1.sh
# Creates a new verifier script from the standard template.
# Usage: bash scripts/ops/new_verifier_from_template_v1.sh <FEATURE_NAME> [--enforce]
#
# FEATURE_NAME: e.g. "MY_FEATURE" → creates scripts/verify/verify_my_feature_v1.sh
# --enforce: include enforce_spec_v1.sh gating (default: always-on)

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

POLICY="docs/ops/contracts/VERIFIER_AUTHORING_POLICY_V1.txt"
[[ -f "$POLICY" ]] || { echo "BLOCK: missing $POLICY"; exit 1; }
grep -q '^VERIFIER_AUTHORING_POLICY_V1_TOKEN=1' "$POLICY" || { echo "BLOCK: missing token in $POLICY"; exit 1; }

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <FEATURE_NAME> [--enforce]" >&2
  echo "Example: $0 MY_FEATURE --enforce" >&2
  exit 1
fi

FEATURE_RAW="$1"
# Normalize: uppercase, replace spaces/dashes with underscores
FEATURE="$(echo "$FEATURE_RAW" | tr '[:lower:]' '[:upper:]' | tr ' -' '_')"
ENFORCE_GATED=0
if [[ "${2:-}" == "--enforce" ]]; then
  ENFORCE_GATED=1
fi

SCRIPT_NAME="verify_$(echo "$FEATURE" | tr '[:upper:]' '[:lower:]')_v1.sh"
OUT="scripts/verify/${SCRIPT_NAME}"

[[ -f "$OUT" ]] && { echo "BLOCK: $OUT already exists"; exit 1; }

if [[ "$ENFORCE_GATED" -eq 1 ]]; then
cat > "$OUT" << TMPL
#!/usr/bin/env bash
set -euo pipefail

# P22-P2-06: generated by new_verifier_from_template_v1.sh
# ENFORCE_SPEC_V1 compliant (enforce-gated)
. scripts/verify/lib/enforce_spec_v1.sh

${FEATURE}_OK=0
trap 'echo "${FEATURE}_OK=\${${FEATURE}_OK}"' EXIT

if ! enforce_spec_should_enforce "${FEATURE}"; then
  enforce_spec_emit_skip "${FEATURE}"
  exit 0
fi

ROOT="\$(git rev-parse --show-toplevel)"
cd "\$ROOT"

# TODO: implement ${FEATURE} verification logic here

${FEATURE}_OK=1
exit 0
TMPL
else
cat > "$OUT" << TMPL
#!/usr/bin/env bash
set -euo pipefail

# P22-P2-06: generated by new_verifier_from_template_v1.sh
${FEATURE}_OK=0
trap 'echo "${FEATURE}_OK=\${${FEATURE}_OK}"' EXIT

ROOT="\$(git rev-parse --show-toplevel)"
cd "\$ROOT"

# TODO: implement ${FEATURE} verification logic here

${FEATURE}_OK=1
exit 0
TMPL
fi

chmod +x "$OUT"
echo "OK: created $OUT"
echo "OK: feature=${FEATURE} enforce_gated=${ENFORCE_GATED}"
echo ""
echo "Next steps:"
echo "  1. Implement logic in $OUT"
echo "  2. Add DoD key init in scripts/verify/verify_repo_contracts.sh"
echo "  3. Add cleanup echo in verify_repo_contracts.sh cleanup() block"
echo "  4. Add run_guard call in verify_repo_contracts.sh"
echo "  5. Register SSOT in docs/ops/contracts/SSOT_REGISTRY_V1.txt (if applicable)"
