/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/accounting/postings/suggest": {
    /**
     * Suggest ledger postings from extracted items
     * @description 추출된 라인아이템으로부터 분개 추천
     * 신뢰도와 근거를 포함하여 반환
     */
    post: operations["suggestPostings"];
  };
  "/v1/accounting/postings": {
    /**
     * Create ledger posting
     * @description 분개 생성 및 확정
     * 멱등성 보장: Idempotency-Key 헤더 또는 client_request_id 필드 사용
     */
    post: operations["createPosting"];
  };
  "/v1/accounting/approvals/{id}": {
    /**
     * Get approval status
     * @description 승인 상태 조회
     */
    get: operations["getApproval"];
  };
  "/v1/accounting/approvals": {
    /**
     * Request approval
     * @description 승인 요청 생성
     */
    post: operations["requestApproval"];
  };
  "/v1/accounting/reconcile": {
    /**
     * Reconcile transactions
     * @description 거래 대사 (거래 매칭/중복 탐지)
     */
    post: operations["reconcile"];
  };
  "/v1/accounting/vat": {
    /**
     * Get VAT information
     * @description 부가세 정보 조회
     */
    get: operations["getVAT"];
  };
  "/v1/accounting/exports": {
    /**
     * Export accounting data
     * @description 회계 데이터 Export (감사용)
     * manifest 서명 및 만료 URL 포함
     */
    post: operations["exportAccounting"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    LineItem: {
      /** @description 항목 설명 */
      desc: string;
      /**
       * @description 금액 (부동소수점 오류 방지를 위해 string으로 표현)
       * 형식: 정수 또는 소수점 이하 2자리
       * 예: "1234.56", "-100.00"
       */
      amount: string;
      /**
       * @description 통화 코드 (ISO-4217)
       * 예: "KRW", "USD", "EUR"
       */
      currency: string;
    };
    SuggestRequest: {
      /** @description 추출된 라인아이템 목록 */
      items: components["schemas"]["LineItem"][];
      /**
       * @description 정책 버전
       * @example v1.0.0
       */
      policy_version?: string;
    };
    Posting: {
      /**
       * @description 계정 코드
       * @example 1010
       */
      account: string;
      /**
       * @description 차변 금액 (string, 최소값 0)
       * @example 1000.00
       */
      debit: string;
      /**
       * @description 대변 금액 (string, 최소값 0)
       * @example 0.00
       */
      credit: string;
      /** @description 비고 */
      note?: string;
    };
    SuggestResponse: {
      /** @description 추천된 분개 목록 */
      postings?: components["schemas"]["Posting"][];
      /**
       * Format: float
       * @description 신뢰도 (0.0 ~ 1.0)
       */
      confidence?: number;
      /** @description 추천 근거 */
      rationale?: string;
    };
    CreatePostingRequest: {
      /** @description 분개 항목 (최소 2개) */
      entries: components["schemas"]["Posting"][];
      /** @description 통화 코드 (ISO-4217) */
      currency: string;
      /**
       * @description 멱등성 보장을 위한 클라이언트 요청 ID
       * @example req-20250120-001
       */
      client_request_id?: string;
    };
    Approval: {
      /** @description Approval ID */
      id?: string;
      /**
       * @description 승인 상태
       * @enum {string}
       */
      status?: "pending" | "approved" | "rejected" | "needs_review";
      /** @description 승인 단계 목록 */
      steps?: string[];
      /**
       * Format: date-time
       * @description 요청 시각 (UTC ISO8601)
       */
      requested_at?: string;
      /**
       * Format: date-time
       * @description 승인 시각 (UTC ISO8601)
       */
      approved_at?: string | null;
    };
    ApprovalRequest: {
      /** @description 분개 ID */
      posting_id: string;
      /** @description 승인자 ID */
      approver_id?: string;
    };
    ReconcileRequest: {
      /** @description 대사할 거래 목록 */
      transactions: Record<string, never>[];
      /**
       * Format: date-time
       * @description 기간 시작 (UTC ISO8601)
       */
      period_start?: string;
      /**
       * Format: date-time
       * @description 기간 종료 (UTC ISO8601)
       */
      period_end?: string;
    };
    ReconcileResponse: {
      /** @description 매칭된 거래 */
      matched?: Record<string, never>[];
      /** @description 매칭되지 않은 거래 */
      unmatched?: Record<string, never>[];
      /** @description 중복 거래 */
      duplicates?: Record<string, never>[];
    };
    VATInfo: {
      /**
       * Format: date
       * @description 기간 (YYYY-MM-DD)
       */
      period?: string;
      /** @description 총 매출액 */
      total_sales?: string;
      /** @description 총 부가세 */
      total_vat?: string;
    };
    ExportRequest: {
      /**
       * @description Export 형식
       * @enum {string}
       */
      format: "csv" | "json";
      /**
       * Format: date-time
       * @description 기간 시작 (UTC ISO8601)
       */
      period_start: string;
      /**
       * Format: date-time
       * @description 기간 종료 (UTC ISO8601)
       */
      period_end: string;
      /**
       * @description 최대 레코드 수 (상한)
       * @default 1000
       */
      max_records?: number;
    };
    ExportResponse: {
      /** @description Export Job ID */
      job_id?: string;
      /**
       * @description Job 상태
       * @enum {string}
       */
      status?: "pending" | "processing" | "completed" | "failed";
      /**
       * Format: uri
       * @description Manifest 다운로드 URL (서명 포함)
       */
      manifest_url?: string;
      /**
       * Format: date-time
       * @description URL 만료 시각 (UTC ISO8601)
       */
      expires_at?: string;
    };
    Error: {
      /** @description 에러 메시지 */
      error: string;
      /** @description 에러 코드 */
      code?: string;
    };
    ValidationError: {
      /** @description 검증 실패 메시지 */
      error: string;
      details: {
          /** @description 검증 실패 필드 경로 */
          path?: string;
          /** @description 검증 실패 메시지 */
          message?: string;
        }[];
    };
  };
  responses: {
    /** @description Bad Request */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Unauthorized */
    Unauthorized: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Forbidden */
    Forbidden: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Suggest ledger postings from extracted items
   * @description 추출된 라인아이템으로부터 분개 추천
   * 신뢰도와 근거를 포함하여 반환
   */
  suggestPostings: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SuggestRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuggestResponse"];
        };
      };
      /** @description Bad Request - Invalid input */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Forbidden - Insufficient permissions */
      403: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Validation Error - Ajv schema validation failed */
      422: {
        content: {
          "application/json": components["schemas"]["ValidationError"];
        };
      };
      /** @description Too Many Requests - Rate limit exceeded */
      429: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Create ledger posting
   * @description 분개 생성 및 확정
   * 멱등성 보장: Idempotency-Key 헤더 또는 client_request_id 필드 사용
   */
  createPosting: {
    parameters: {
      header?: {
        /** @description 멱등성 보장을 위한 클라이언트 요청 ID */
        "Idempotency-Key"?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePostingRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Posting"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      /** @description Conflict - Duplicate request (idempotency) */
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Get approval status
   * @description 승인 상태 조회
   */
  getApproval: {
    parameters: {
      path: {
        /** @description Approval ID */
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Approval"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Request approval
   * @description 승인 요청 생성
   */
  requestApproval: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApprovalRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Approval"];
        };
      };
    };
  };
  /**
   * Reconcile transactions
   * @description 거래 대사 (거래 매칭/중복 탐지)
   */
  reconcile: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReconcileRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ReconcileResponse"];
        };
      };
    };
  };
  /**
   * Get VAT information
   * @description 부가세 정보 조회
   */
  getVAT: {
    parameters: {
      query?: {
        /** @description 기간 (YYYY-MM-DD) */
        period?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["VATInfo"];
        };
      };
    };
  };
  /**
   * Export accounting data
   * @description 회계 데이터 Export (감사용)
   * manifest 서명 및 만료 URL 포함
   */
  exportAccounting: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportRequest"];
      };
    };
    responses: {
      /** @description Accepted - Export job created */
      202: {
        content: {
          "application/json": components["schemas"]["ExportResponse"];
        };
      };
    };
  };
}
