"""Stable fail-closed error codes for the Box5 A4 v5.3 boundary."""

from __future__ import annotations

from enum import StrEnum
import re


class A4AuthorityError(StrEnum):
    PROCESS_HARDENING = "BLOCK_PROCESS_HARDENING"
    PROTOCOL_VERSION = "BLOCK_PROTOCOL_VERSION"
    CALLER_IDENTITY = "BLOCK_CALLER_IDENTITY"
    AUTHORITY_IDENTITY = "BLOCK_AUTHORITY_IDENTITY"
    VERIFIER_IDENTITY = "BLOCK_VERIFIER_IDENTITY"
    BUNDLE_CONTAINMENT = "BLOCK_BUNDLE_CONTAINMENT"
    CODE_CLOSURE = "BLOCK_CODE_CLOSURE"
    UNSAFE_VOLUME = "BLOCK_UNSAFE_VOLUME"
    KEY_UNAVAILABLE = "BLOCK_KEY_UNAVAILABLE"
    KEY_EPOCH = "BLOCK_KEY_EPOCH"
    TRUST_POLICY = "BLOCK_TRUST_POLICY"
    TRUST_ROLLBACK = "BLOCK_TRUST_ROLLBACK"
    TRUST_EXPIRED = "BLOCK_TRUST_EXPIRED"
    SIGNATURE = "BLOCK_SIGNATURE"
    REQUEST_SCHEMA = "BLOCK_REQUEST_SCHEMA"
    REQUEST_SIZE = "BLOCK_REQUEST_SIZE"
    REQUEST_DEADLINE = "BLOCK_REQUEST_DEADLINE"
    NONCE_BINDING = "BLOCK_NONCE_BINDING"
    REPLAY_OR_EQUIVOCATION = "BLOCK_REPLAY_OR_EQUIVOCATION"
    SOURCE_FD = "BLOCK_SOURCE_FD"
    SOURCE_DIGEST = "BLOCK_SOURCE_DIGEST"
    AUTHORITY_SATURATED = "BLOCK_AUTHORITY_SATURATED"
    AUTHORITY_TIMEOUT = "BLOCK_AUTHORITY_TIMEOUT"
    STORAGE_ATOMICITY = "BLOCK_STORAGE_ATOMICITY"
    DLP = "BLOCK_DLP"
    AUTHORITY_UNAVAILABLE = "UNVERIFIED_AUTHORITY_UNAVAILABLE"
    INTERNAL = "UNVERIFIED_INTERNAL"


PUBLIC_ERROR_CODES = frozenset(code.value for code in A4AuthorityError)


def public_error_code(value: object) -> str:
    """Collapse unknown internal failures to a stable, non-sensitive code."""

    text = str(value)
    if text in PUBLIC_ERROR_CODES or re.fullmatch(r"BLOCK_[A-Z0-9_]+", text):
        return text
    return A4AuthorityError.INTERNAL.value
