import CryptoKit
import Darwin
import Foundation
import Security

@_silgen_name("butler_secure_zero")
private func secureZero(_ pointer: UnsafeMutableRawPointer?, _ length: Int)

@_silgen_name("butler_deny_debugger")
private func denyDebugger() -> Int32

// a4KeychainAccessGroup is generated by the production build from the
// provisioning-profile-authorized access group. It is never accepted from the
// product process or its environment.

private let keychainService = "com.butler.a4.verifier-authority"
private let keychainAccount = "ed25519.production.v1"

private func fail(_ code: String) -> Never {
    FileHandle.standardError.write(Data("A4_AUTHORITY_LAUNCH_OK=0 ERROR_CODE=\(code)\n".utf8))
    exit(EXIT_FAILURE)
}

private func argument(_ name: String) -> String {
    guard let index = CommandLine.arguments.firstIndex(of: name),
          index + 1 < CommandLine.arguments.count else {
        fail("BLOCK_LAUNCH_ARGUMENT")
    }
    let value = CommandLine.arguments[index + 1]
    guard !value.isEmpty, value.first == "/" else {
        fail("BLOCK_LAUNCH_ARGUMENT")
    }
    return value
}

private func sha256Hex(_ data: Data) -> String {
    SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
}

private func verifyBuildBinding(buildInfoPath: String) {
    guard let executable = CommandLine.arguments.first,
          let executableData = try? Data(contentsOf: URL(fileURLWithPath: executable)),
          let buildInfoData = try? Data(contentsOf: URL(fileURLWithPath: buildInfoPath)),
          let object = try? JSONSerialization.jsonObject(with: buildInfoData) as? [String: Any],
          let helper = object["a4_authority_helper"] as? [String: Any],
          helper["bundled"] as? Bool == true,
          helper["sha256"] as? String == sha256Hex(executableData) else {
        fail("BLOCK_BUILD_BINDING")
    }
}

private func loadSigningSeed() -> [UInt8] {
    let query: [CFString: Any] = [
        kSecClass: kSecClassGenericPassword,
        kSecAttrService: keychainService,
        kSecAttrAccount: keychainAccount,
        kSecAttrAccessGroup: a4KeychainAccessGroup,
        kSecUseDataProtectionKeychain: true,
        kSecReturnData: true,
        kSecMatchLimit: kSecMatchLimitOne,
    ]
    var result: CFTypeRef?
    let status = SecItemCopyMatching(query as CFDictionary, &result)
    guard status == errSecSuccess, var data = result as? Data, data.count == 32 else {
        fail("BLOCK_KEYCHAIN_UNAVAILABLE")
    }
    defer {
        data.withUnsafeMutableBytes { secureZero($0.baseAddress, $0.count) }
    }
    return [UInt8](data)
}

private func writeAll(_ descriptor: Int32, bytes: UnsafeRawBufferPointer) -> Bool {
    var offset = 0
    while offset < bytes.count {
        let written = Darwin.write(
            descriptor,
            bytes.baseAddress!.advanced(by: offset),
            bytes.count - offset
        )
        if written <= 0 { return false }
        offset += written
    }
    return true
}

private func run() -> Never {
    guard denyDebugger() == 0 else {
        fail("BLOCK_PROCESS_HARDENING")
    }
    var coreLimit = rlimit(rlim_cur: 0, rlim_max: 0)
    guard setrlimit(RLIMIT_CORE, &coreLimit) == 0 else {
        fail("BLOCK_PROCESS_HARDENING")
    }
    _ = umask(0o077)

    let socketPath = argument("--socket")
    let trustPath = argument("--authority-trust")
    let pythonPath = argument("--python")
    let verifierPath = argument("--verifier")
    let buildInfoPath = argument("--build-info")
    verifyBuildBinding(buildInfoPath: buildInfoPath)

    var seed = loadSigningSeed()
    let input = Pipe()
    let process = Process()
    process.executableURL = URL(fileURLWithPath: pythonPath)
    process.arguments = [
        "-I", verifierPath,
        "--serve-authority",
        "--socket", socketPath,
        "--authority-trust", trustPath,
        "--signing-key-fd", "0",
        "--require-bundled-build-stamp",
    ]
    process.standardInput = input
    process.standardOutput = FileHandle.standardOutput
    process.standardError = FileHandle.standardError
    var childEnvironment: [String: String] = [
        "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
        "LANG": "C.UTF-8",
        "LC_ALL": "C.UTF-8",
    ]
    for name in ["HOME", "TMPDIR"] {
        if let value = ProcessInfo.processInfo.environment[name], !value.isEmpty {
            childEnvironment[name] = value
        }
    }
    process.environment = childEnvironment

    do {
        try process.run()
    } catch {
        seed.withUnsafeMutableBytes { secureZero($0.baseAddress, $0.count) }
        fail("BLOCK_AUTHORITY_PROCESS")
    }
    input.fileHandleForReading.closeFile()
    let written = seed.withUnsafeMutableBytes { buffer -> Bool in
        guard let base = buffer.baseAddress, mlock(base, buffer.count) == 0 else {
            return false
        }
        defer {
            secureZero(base, buffer.count)
            _ = munlock(base, buffer.count)
        }
        return writeAll(input.fileHandleForWriting.fileDescriptor, bytes: UnsafeRawBufferPointer(buffer))
    }
    input.fileHandleForWriting.closeFile()
    guard written else {
        process.terminate()
        fail("BLOCK_SECRET_TRANSFER")
    }
    process.waitUntilExit()
    exit(process.terminationStatus)
}

@main
private struct A4VerifierAuthorityLauncher {
    static func main() {
        run()
    }
}
