from __future__ import annotations

SCHEMA_VERSION_DIAGNOSIS = "box3.helper35_lora_fusion.diagnosis.v1"
SCHEMA_VERSION_MANIFEST = "box3.lora_fusion_manifest.v1"
SCHEMA_VERSION_METRIC_COMPARISON = "box3.helper35_lora_fusion.metric_comparison.v1"

HELPER3_FORMAT_SHA256 = "92e8454fdc01d9bb002a510b2fdaecabcc9b9cbf964b6e48e5d61c23b5ace4b0"
HELPER5_TOOL_CALL_SHA256 = "ad852bbb79aee63cc68750eac3ebe02de372d4eb9529659ae065490c78c933ca"

MODEL_ADAPTER_HELPERS = {
    "helper3_format": HELPER3_FORMAT_SHA256,
    "helper5_tool_call": HELPER5_TOOL_CALL_SHA256,
}

SDK_HELPERS_FORBIDDEN_IN_STACK = {
    "helper4_grounding",
    "helper7_table_figure",
    "helper8_company_style",
}

ALLOWED_FUSION_METHODS = {"runtime_lora", "merge_to_gguf", "already_fused", "inconclusive"}
ALLOWED_SHA_SCOPE = {"file", "directory_manifest"}
ALLOWED_DIAGNOSIS_STATUS = {
    "DIAGNOSIS_PENDING",
    "ALREADY_FUSED_CONFIRMED",
    "NOT_FUSED_CONFIRMED",
    "INCONCLUSIVE",
    "BLOCKED",
}

PASS_DIAGNOSIS_ONLY = "PASS_DIAGNOSIS_ONLY"
PASS_FUSION_EVAL = "PASS_FUSION_EVAL"
PARTIAL = "PARTIAL"
BLOCK = "BLOCK"

FAIL_BLOCK_DIAGNOSIS_REQUIRED = "BLOCK_DIAGNOSIS_REQUIRED"
FAIL_BLOCK_DOUBLE_FUSION = "BLOCK_DOUBLE_FUSION"
FAIL_BLOCK_SDK_HELPER_STACK_ATTEMPT = "BLOCK_SDK_HELPER_STACK_ATTEMPT"
FAIL_BLOCK_RAW_EVIDENCE_LEAK = "BLOCK_RAW_EVIDENCE_LEAK"
FAIL_BLOCK_MANIFEST_INVALID = "BLOCK_LORA_FUSION_MANIFEST_INVALID"
FAIL_BLOCK_INPUT_SHA_MISMATCH = "BLOCK_FUSION_INPUT_SHA_MISMATCH"
FAIL_BLOCK_QUANT_CONFIG_MISMATCH = "BLOCK_QUANT_CONFIG_MISMATCH"
FAIL_BLOCK_GENERAL_PC_BUDGET_EXCEEDED = "BLOCK_GENERAL_PC_BUDGET_EXCEEDED"
FAIL_PARTIAL_DIAGNOSIS_INSUFFICIENT = "PARTIAL_DIAGNOSIS_INSUFFICIENT"
FAIL_PARTIAL_MULTI_LORA_UNPROVEN = "PARTIAL_MULTI_LORA_UNPROVEN"
FAIL_PARTIAL_RUNTIME_LORA_UNSUPPORTED = "PARTIAL_RUNTIME_LORA_UNSUPPORTED"
FAIL_PARTIAL_MERGE_SOURCE_MISSING = "PARTIAL_MERGE_SOURCE_MISSING"
FAIL_PARTIAL_FUSION_NO_GAIN = "PARTIAL_FUSION_NO_GAIN"

GENERAL_PC_LIMITS = {
    "max_model_size_bytes": 6_000_000_000,
    "max_peak_rss_mb": 12_000,
    "max_latency_ms": 30_000,
}
