from __future__ import annotations

# Box3 actual-operation v1.2 fail_class SSOT.
BLOCK_BASELINE_DRIFT = "BLOCK_BASELINE_DRIFT"
PARTIAL_REAL_ASSET_VOLUME_MISSING = "PARTIAL_REAL_ASSET_VOLUME_MISSING"
PARTIAL_REAL_RUNNER_RUNTIME_UNAVAILABLE = "PARTIAL_REAL_RUNNER_RUNTIME_UNAVAILABLE"
PARTIAL_HELPER_STACK_UNSUPPORTED = "PARTIAL_HELPER_STACK_UNSUPPORTED"
PARTIAL_PEAK_MEMORY_UNMEASURED = "PARTIAL_PEAK_MEMORY_UNMEASURED"
BLOCK_MODEL_ASSET_MISSING = "BLOCK_MODEL_ASSET_MISSING"
BLOCK_MODEL_ASSET_SHA_MISMATCH = "BLOCK_MODEL_ASSET_SHA_MISMATCH"
BLOCK_MODEL_ASSET_SHA_SCOPE_INVALID = "BLOCK_MODEL_ASSET_SHA_SCOPE_INVALID"
BLOCK_HELPER_REAL_USE_GUARD_PENDING = "BLOCK_HELPER_REAL_USE_GUARD_PENDING"
BLOCK_HELPER_ASSET_DRIFT = "BLOCK_HELPER_ASSET_DRIFT"
BLOCK_HELPER_STACK_CAPABILITY_FAILED = "BLOCK_HELPER_STACK_CAPABILITY_FAILED"
BLOCK_MOCK_RUNNER_FOR_REAL = "BLOCK_MOCK_RUNNER_FOR_REAL"
BLOCK_RUNNER_TIMEOUT = "BLOCK_RUNNER_TIMEOUT"
BLOCK_RUNNER_ERROR = "BLOCK_RUNNER_ERROR"
BLOCK_POLICY_GATE = "BLOCK_POLICY_GATE"
BLOCK_HUMAN_APPROVAL_KILL_SWITCH = "BLOCK_HUMAN_APPROVAL_KILL_SWITCH"
BLOCK_HUMAN_APPROVAL_REVOKED = "BLOCK_HUMAN_APPROVAL_REVOKED"
BLOCK_HUMAN_APPROVAL_EXPIRED = "BLOCK_HUMAN_APPROVAL_EXPIRED"
BLOCK_HUMAN_APPROVAL_SCOPE_MISMATCH = "BLOCK_HUMAN_APPROVAL_SCOPE_MISMATCH"
BLOCK_UNSUPPORTED_CLAIM = "BLOCK_UNSUPPORTED_CLAIM"
NEEDS_REVIEW_UNSUPPORTED_CLAIM = "NEEDS_REVIEW_UNSUPPORTED_CLAIM"
NEEDS_REVIEW_UNSUPPORTED_CLAIM_LABEL_COVERAGE_PARTIAL = "NEEDS_REVIEW_UNSUPPORTED_CLAIM_LABEL_COVERAGE_PARTIAL"
NEEDS_REVIEW_NO_EVIDENCE_CLAIM = "NEEDS_REVIEW_NO_EVIDENCE_CLAIM"
FIXED_EVAL_PENDING = "FIXED_EVAL_PENDING"
BLOCK_RAW_OR_PATH_LEAK = "BLOCK_RAW_OR_PATH_LEAK"
BLOCK_DLP_OUTBOUND_DRAFT = "BLOCK_DLP_OUTBOUND_DRAFT"
# real_grounding 이 사실 문장 0건일 때 내는 판정. 지금까지 문자열 리터럴로만 존재해
# FAIL_CLASS_SEVERITY 미등록(unknown→보수적 block)이었다. SSOT 상수로 승격.
BLOCK_NO_FACTUAL_CLAIMS = "BLOCK_NO_FACTUAL_CLAIMS"

PASS_STATUS = "PASS_BOX3_REAL_LOCAL_AFTER_HUMAN_APPROVAL"
REAL_CANDIDATE = "REAL_CANDIDATE"
CONTRACT_ONLY = "CONTRACT_ONLY"
ASSET_INVENTORY_PASS = "ASSET_INVENTORY_PASS"
BLOCKED = "BLOCKED"

# 박스 3 helper SDK 통합 v1.3 (2026-06-04, PR #779) — 신규 fail_class SSOT.
# 본진 v1.2 보존, append-only 확장 (약화 0).
PARTIAL_MODEL_ADAPTER_STACK_UNSUPPORTED = "PARTIAL_MODEL_ADAPTER_STACK_UNSUPPORTED"
PARTIAL_HELPER_SDK_UNAVAILABLE = "PARTIAL_HELPER_SDK_UNAVAILABLE"
PARTIAL_EMBEDDER_UNAVAILABLE = "PARTIAL_EMBEDDER_UNAVAILABLE"
PARTIAL_BGE_M3_FALLBACK_USED = "PARTIAL_BGE_M3_FALLBACK_USED"
BLOCK_HELPER_SDK_STACK_ATTEMPT = "BLOCK_HELPER_SDK_STACK_ATTEMPT"
BLOCK_HELPER8_NON_CANONICAL_SHA = "BLOCK_HELPER8_NON_CANONICAL_SHA"
BLOCK_GROUNDING_EMBEDDER_MISSING = "BLOCK_GROUNDING_EMBEDDER_MISSING"

# 박스 3 v5 canonical apply v1.2 (2026-06-05, PR #783) — 신규 fail_class.
# append-only, 본진 v1.2/v1.3 보존 (약화 0).
BLOCK_HELPER35_DOUBLE_STACK_RISK = "BLOCK_HELPER35_DOUBLE_STACK_RISK"
BLOCK_V4_DEFAULT_REFERENCE = "BLOCK_V4_DEFAULT_REFERENCE"
BLOCK_DEGENERATION = "BLOCK_DEGENERATION"
PASS_BOX3_V5_CANONICAL_APPLY = "PASS_BOX3_V5_CANONICAL_APPLY"

ALLOWED_ACTUAL_OPERATION_STATUSES = {
    CONTRACT_ONLY,
    ASSET_INVENTORY_PASS,
    PARTIAL_REAL_ASSET_VOLUME_MISSING,
    PARTIAL_REAL_RUNNER_RUNTIME_UNAVAILABLE,
    PARTIAL_HELPER_STACK_UNSUPPORTED,
    PARTIAL_MODEL_ADAPTER_STACK_UNSUPPORTED,
    PARTIAL_HELPER_SDK_UNAVAILABLE,
    PARTIAL_EMBEDDER_UNAVAILABLE,
    PARTIAL_BGE_M3_FALLBACK_USED,
    REAL_CANDIDATE,
    PASS_STATUS,
    BLOCKED,
}

# Box3 unsupported-claim label demotion B-plan (2026-07-09).
# Explicit severity prevents future non-BLOCK blocking names from silently
# passing, while preserving selected existing candidate/review fail classes.
FAIL_CLASS_SEVERITY: dict[str, str] = {
    BLOCK_BASELINE_DRIFT: "block",
    BLOCK_MODEL_ASSET_MISSING: "block",
    BLOCK_MODEL_ASSET_SHA_MISMATCH: "block",
    BLOCK_MODEL_ASSET_SHA_SCOPE_INVALID: "block",
    BLOCK_HELPER_REAL_USE_GUARD_PENDING: "block",
    BLOCK_HELPER_ASSET_DRIFT: "block",
    BLOCK_HELPER_STACK_CAPABILITY_FAILED: "block",
    BLOCK_MOCK_RUNNER_FOR_REAL: "block",
    BLOCK_RUNNER_TIMEOUT: "block",
    BLOCK_RUNNER_ERROR: "block",
    BLOCK_POLICY_GATE: "block",
    BLOCK_HUMAN_APPROVAL_KILL_SWITCH: "block",
    BLOCK_HUMAN_APPROVAL_REVOKED: "block",
    BLOCK_HUMAN_APPROVAL_EXPIRED: "block",
    BLOCK_HUMAN_APPROVAL_SCOPE_MISMATCH: "block",
    BLOCK_UNSUPPORTED_CLAIM: "block",
    BLOCK_RAW_OR_PATH_LEAK: "block",
    BLOCK_DLP_OUTBOUND_DRAFT: "block",
    # 잠정 block — 현행 동작(unknown→보수적 block)을 명시화해 보존만 한다.
    # 최종 severity(block vs needs_review)는 §3/§4 계측 결과 확인 후 별도 지시로 확정.
    BLOCK_NO_FACTUAL_CLAIMS: "block",
    BLOCK_HELPER_SDK_STACK_ATTEMPT: "block",
    BLOCK_HELPER8_NON_CANONICAL_SHA: "block",
    BLOCK_GROUNDING_EMBEDDER_MISSING: "block",
    BLOCK_HELPER35_DOUBLE_STACK_RISK: "block",
    BLOCK_V4_DEFAULT_REFERENCE: "block",
    BLOCK_DEGENERATION: "block",
    NEEDS_REVIEW_UNSUPPORTED_CLAIM: "needs_review",
    NEEDS_REVIEW_UNSUPPORTED_CLAIM_LABEL_COVERAGE_PARTIAL: "needs_review",
    NEEDS_REVIEW_NO_EVIDENCE_CLAIM: "needs_review",
    "NEEDS_REVIEW_NO_EVIDENCE": "needs_review",
    "NEEDS_REVIEW_NO_EVIDENCE_CLAIMS": "needs_review",
    "NEEDS_REVIEW_FORMAT_STYLE_GATE": "needs_review",
    "CITATION_ACCURACY_BELOW_GATE": "needs_review",
    "FORMAT_MATCH_BELOW_GATE": "needs_review",
    "STYLE_MATCH_BELOW_GATE": "needs_review",
    "TABLE_FIGURE_COVERAGE_BELOW_GATE": "needs_review",
    "PARTIAL_SUPPORTED_CLAIM_COUNT_LOW": "needs_review",
    "PARTIAL_SECTION_COMPLETENESS_LOW": "needs_review",
    "PARTIAL_ABSTAIN_OVERUSE": "needs_review",
    "TEST_ONLY_RUNNER_NOT_REAL_APPROVAL": "needs_review",
    FIXED_EVAL_PENDING: "needs_review",
    PARTIAL_REAL_ASSET_VOLUME_MISSING: "nonblocking",
    PARTIAL_REAL_RUNNER_RUNTIME_UNAVAILABLE: "nonblocking",
    PARTIAL_HELPER_STACK_UNSUPPORTED: "nonblocking",
    PARTIAL_PEAK_MEMORY_UNMEASURED: "nonblocking",
    PARTIAL_MODEL_ADAPTER_STACK_UNSUPPORTED: "nonblocking",
    PARTIAL_HELPER_SDK_UNAVAILABLE: "nonblocking",
    PARTIAL_EMBEDDER_UNAVAILABLE: "nonblocking",
    PARTIAL_BGE_M3_FALLBACK_USED: "nonblocking",
    "BLOCK_FINAL_GATE_UNSUPPORTED": "needs_review",
}


def is_blocking_actual_fail_class(fail_class: str | None) -> bool:
    value = str(fail_class or "").strip()
    if not value:
        return False
    if value in FAIL_CLASS_SEVERITY:
        return FAIL_CLASS_SEVERITY[value] == "block"
    if value.startswith("BLOCK_"):
        return True
    return True

# ── Box3 model-scope approval P0 TOCTOU 하드닝 v1.2 (보완팀4) — reason enum SSOT ──
# append-only, 본진 보존(약화 0). verify/generate 스크립트와 approval/identity 경로가
# 이 고정 코드만 출력·raise 한다(원문·경로·사용자명 0).
APP_MODEL_SCOPE_REQUIRED = "APP_MODEL_SCOPE_REQUIRED"
MODEL_DIGEST_UNAVAILABLE = "MODEL_DIGEST_UNAVAILABLE"
EVAL_REQUEST_SCOPE_REQUIRED = "EVAL_REQUEST_SCOPE_REQUIRED"
APPROVAL_CONTEXT_INVALID = "APPROVAL_CONTEXT_INVALID"
APPROVED_MODEL_RUNTIME_MISMATCH = "APPROVED_MODEL_RUNTIME_MISMATCH"
MODEL_PATH_SYMLINK_DENIED = "MODEL_PATH_SYMLINK_DENIED"
MODEL_FILE_CHANGED_DURING_HASH = "MODEL_FILE_CHANGED_DURING_HASH"
MODEL_PATH_SWAPPED_AFTER_HASH = "MODEL_PATH_SWAPPED_AFTER_HASH"
DEVICE_DIGEST_UNAVAILABLE = "DEVICE_DIGEST_UNAVAILABLE"
DEVICE_DIGEST_MISMATCH = "DEVICE_DIGEST_MISMATCH"
DEVICE_DIGEST_INVALID = "DEVICE_DIGEST_INVALID"
APPROVAL_FILE_PERMISSION_INVALID = "APPROVAL_FILE_PERMISSION_INVALID"
APPROVAL_SCHEMA_INVALID = "APPROVAL_SCHEMA_INVALID"
APPROVAL_MODE_INVALID = "APPROVAL_MODE_INVALID"
APPROVAL_SCOPE_DIGEST_MISMATCH = "APPROVAL_SCOPE_DIGEST_MISMATCH"
MANIFEST_SCHEMA_INVALID = "MANIFEST_SCHEMA_INVALID"
MANIFEST_DIGEST_MISMATCH = "MANIFEST_DIGEST_MISMATCH"
PHYSICAL_MODEL_DIGEST_MISMATCH = "PHYSICAL_MODEL_DIGEST_MISMATCH"
EVAL_SUMMARY_DIGEST_MISMATCH = "EVAL_SUMMARY_DIGEST_MISMATCH"


class Box3ApprovalError(Exception):
    """Box3 approval/identity 경로의 고정 reason 코드 예외의 상위 타입."""


class HumanApprovalError(Box3ApprovalError):
    """승인 컨텍스트/모드/scope 해석 실패(고정 reason 코드만 메시지로 사용)."""


class Box3SecurityError(Box3ApprovalError):
    """모델 identity/TOCTOU 위반 등 보안 결속 실패(고정 reason 코드만 메시지로 사용)."""
