from __future__ import annotations

# Box3 actual-operation v1.2 fail_class SSOT.
BLOCK_BASELINE_DRIFT = "BLOCK_BASELINE_DRIFT"
PARTIAL_REAL_ASSET_VOLUME_MISSING = "PARTIAL_REAL_ASSET_VOLUME_MISSING"
PARTIAL_REAL_RUNNER_RUNTIME_UNAVAILABLE = "PARTIAL_REAL_RUNNER_RUNTIME_UNAVAILABLE"
PARTIAL_HELPER_STACK_UNSUPPORTED = "PARTIAL_HELPER_STACK_UNSUPPORTED"
PARTIAL_PEAK_MEMORY_UNMEASURED = "PARTIAL_PEAK_MEMORY_UNMEASURED"
BLOCK_MODEL_ASSET_MISSING = "BLOCK_MODEL_ASSET_MISSING"
BLOCK_MODEL_ASSET_SHA_MISMATCH = "BLOCK_MODEL_ASSET_SHA_MISMATCH"
BLOCK_MODEL_ASSET_SHA_SCOPE_INVALID = "BLOCK_MODEL_ASSET_SHA_SCOPE_INVALID"
BLOCK_HELPER_REAL_USE_GUARD_PENDING = "BLOCK_HELPER_REAL_USE_GUARD_PENDING"
BLOCK_HELPER_ASSET_DRIFT = "BLOCK_HELPER_ASSET_DRIFT"
BLOCK_HELPER_STACK_CAPABILITY_FAILED = "BLOCK_HELPER_STACK_CAPABILITY_FAILED"
BLOCK_MOCK_RUNNER_FOR_REAL = "BLOCK_MOCK_RUNNER_FOR_REAL"
BLOCK_RUNNER_TIMEOUT = "BLOCK_RUNNER_TIMEOUT"
BLOCK_RUNNER_ERROR = "BLOCK_RUNNER_ERROR"
BLOCK_POLICY_GATE = "BLOCK_POLICY_GATE"
BLOCK_HUMAN_APPROVAL_KILL_SWITCH = "BLOCK_HUMAN_APPROVAL_KILL_SWITCH"
BLOCK_HUMAN_APPROVAL_REVOKED = "BLOCK_HUMAN_APPROVAL_REVOKED"
BLOCK_HUMAN_APPROVAL_EXPIRED = "BLOCK_HUMAN_APPROVAL_EXPIRED"
BLOCK_HUMAN_APPROVAL_SCOPE_MISMATCH = "BLOCK_HUMAN_APPROVAL_SCOPE_MISMATCH"
BLOCK_UNSUPPORTED_CLAIM = "BLOCK_UNSUPPORTED_CLAIM"
NEEDS_REVIEW_NO_EVIDENCE_CLAIM = "NEEDS_REVIEW_NO_EVIDENCE_CLAIM"
FIXED_EVAL_PENDING = "FIXED_EVAL_PENDING"
BLOCK_RAW_OR_PATH_LEAK = "BLOCK_RAW_OR_PATH_LEAK"

PASS_STATUS = "PASS_BOX3_REAL_LOCAL_AFTER_HUMAN_APPROVAL"
REAL_CANDIDATE = "REAL_CANDIDATE"
CONTRACT_ONLY = "CONTRACT_ONLY"
ASSET_INVENTORY_PASS = "ASSET_INVENTORY_PASS"
BLOCKED = "BLOCKED"

ALLOWED_ACTUAL_OPERATION_STATUSES = {
    CONTRACT_ONLY,
    ASSET_INVENTORY_PASS,
    PARTIAL_REAL_ASSET_VOLUME_MISSING,
    PARTIAL_REAL_RUNNER_RUNTIME_UNAVAILABLE,
    PARTIAL_HELPER_STACK_UNSUPPORTED,
    REAL_CANDIDATE,
    PASS_STATUS,
    BLOCKED,
}
