"""Box3 real 융합 — fail-closed fail_class 상수(단일 정의).

베이스: maindev real_fail_class. 모든 차단/보류 사유는 reason code 로만 노출하며
원문·경로·토큰을 담지 않는다.
"""
from __future__ import annotations

from typing import Final

BLOCK_ASSET_MANIFEST_INVALID: Final = "BLOCK_ASSET_MANIFEST_INVALID"
BLOCK_ASSET_MANIFEST_CONTRADICTORY_ROWS: Final = "BLOCK_ASSET_MANIFEST_CONTRADICTORY_ROWS"
BLOCK_ASSET_INVENTORY_PENDING: Final = "BLOCK_ASSET_INVENTORY_PENDING"
ASSET_INTERFACE_PENDING: Final = "ASSET_INTERFACE_PENDING"
BLOCK_EVIDENCE_EXTRACTION_FAILED: Final = "BLOCK_EVIDENCE_EXTRACTION_FAILED"
BLOCK_BOX3_REAL_RUNNER_MISSING: Final = "BLOCK_BOX3_REAL_RUNNER_MISSING"
BLOCK_BOX3_REAL_RUNNER_TIMEOUT: Final = "BLOCK_BOX3_REAL_RUNNER_TIMEOUT"
BLOCK_BOX3_REAL_RUNNER_ERROR: Final = "BLOCK_BOX3_REAL_RUNNER_ERROR"
BLOCK_BOX3_REAL_SECURITY_RISK: Final = "BLOCK_BOX3_REAL_SECURITY_RISK"
BLOCK_CLAIM_EXTRACTION_EMPTY: Final = "BLOCK_CLAIM_EXTRACTION_EMPTY"
BLOCK_FINAL_GATE_UNSUPPORTED: Final = "BLOCK_FINAL_GATE_UNSUPPORTED"
NEEDS_REVIEW_NO_EVIDENCE: Final = "NEEDS_REVIEW_NO_EVIDENCE"
CITATION_ACCURACY_BELOW_GATE: Final = "CITATION_ACCURACY_BELOW_GATE"
FORMAT_MATCH_BELOW_GATE: Final = "FORMAT_MATCH_BELOW_GATE"
STYLE_MATCH_BELOW_GATE: Final = "STYLE_MATCH_BELOW_GATE"
TABLE_FIGURE_COVERAGE_BELOW_GATE: Final = "TABLE_FIGURE_COVERAGE_BELOW_GATE"
FIXED_EVAL_INSUFFICIENT: Final = "FIXED_EVAL_INSUFFICIENT"
FIXED_EVAL_BELOW_GATE: Final = "FIXED_EVAL_BELOW_GATE"
BLOCK_RAW_OR_PATH_LEAK: Final = "BLOCK_RAW_OR_PATH_LEAK"

# 박스 3 real 실제 켜기 v1.3 (2026-06-03) — 신규 fail_class·상태명·정직 라벨.
# 베이스(real 융합 v1.0)와 동일 SSOT 모듈에서 단일 정의(봉인 0). MAINDEV 의 enablement
# 5 신규 모듈(final_gate · human_approval · local_real_runner · real_pipeline_enablement
# · real_runner_assets)이 본 상수들을 import 한다. Codex 보완 5 의 상태명
# (PASS_BOX3_REAL_LOCAL_AFTER_HUMAN_APPROVAL) 포함.
BLOCK_HUMAN_APPROVAL_MISSING: Final = "BLOCK_HUMAN_APPROVAL_MISSING"
BLOCK_HUMAN_APPROVAL_INVALID: Final = "BLOCK_HUMAN_APPROVAL_INVALID"
BLOCK_HUMAN_APPROVAL_EXPIRED: Final = "BLOCK_HUMAN_APPROVAL_EXPIRED"
BLOCK_HUMAN_APPROVAL_REVOKED: Final = "BLOCK_HUMAN_APPROVAL_REVOKED"
BLOCK_HUMAN_APPROVAL_SCOPE_MISMATCH: Final = "BLOCK_HUMAN_APPROVAL_SCOPE_MISMATCH"
BLOCK_HUMAN_APPROVAL_KILL_SWITCH: Final = "BLOCK_HUMAN_APPROVAL_KILL_SWITCH"
BLOCK_BASE_MODEL_FULL_SHA_NOT_CONFIGURED: Final = "BLOCK_BASE_MODEL_FULL_SHA_NOT_CONFIGURED"
BLOCK_MODEL_ASSET_MISSING: Final = "BLOCK_MODEL_ASSET_MISSING"
BLOCK_MODEL_ASSET_SHA_MISMATCH: Final = "BLOCK_MODEL_ASSET_SHA_MISMATCH"
BLOCK_MODEL_ASSET_SHA_SCOPE_INVALID: Final = "BLOCK_MODEL_ASSET_SHA_SCOPE_INVALID"
BLOCK_HELPER_ASSET_DRIFT: Final = "BLOCK_HELPER_ASSET_DRIFT"
BLOCK_HELPER_REAL_USE_GUARD_PENDING: Final = "BLOCK_HELPER_REAL_USE_GUARD_PENDING"
BLOCK_MOCK_RUNNER_FOR_REAL: Final = "BLOCK_MOCK_RUNNER_FOR_REAL"
BLOCK_RUNNER_ERROR: Final = "BLOCK_RUNNER_ERROR"
BLOCK_RUNNER_TIMEOUT: Final = "BLOCK_RUNNER_TIMEOUT"
BLOCK_POLICY_GATE: Final = "BLOCK_POLICY_GATE"
BLOCK_ASSET_INVENTORY_NOT_PASS: Final = "BLOCK_ASSET_INVENTORY_NOT_PASS"
BLOCK_EVIDENCE_MISSING: Final = "BLOCK_EVIDENCE_MISSING"
BLOCK_BASELINE_DRIFT: Final = "BLOCK_BASELINE_DRIFT"
NEEDS_REVIEW_NO_EVIDENCE_CLAIMS: Final = "NEEDS_REVIEW_NO_EVIDENCE_CLAIMS"
NEEDS_REVIEW_FORMAT_STYLE_GATE: Final = "NEEDS_REVIEW_FORMAT_STYLE_GATE"
FIXED_EVAL_PENDING: Final = "FIXED_EVAL_PENDING"
# 정직 상태 라벨 (출력 status). 박스 3 real candidate vs 인간 승인 후 PASS 구분.
CONTRACT_ONLY: Final = "CONTRACT_ONLY"
REAL_CANDIDATE: Final = "REAL_CANDIDATE"
RUNNER_SMOKE_PASS: Final = "RUNNER_SMOKE_PASS"
ASSET_INVENTORY_PASS: Final = "ASSET_INVENTORY_PASS"
PARTIAL_REAL_RUNNER_RUNTIME_UNAVAILABLE: Final = "PARTIAL_REAL_RUNNER_RUNTIME_UNAVAILABLE"
# Codex 보완 5 정합: 상태명 PASS_BOX3_REAL_LOCAL_AFTER_HUMAN_APPROVAL (sealed config flag
# 무시·proxy eval ↔ real_runner_eval 분리·prompt/output digest only·HELPER_REAL_USE_GUARD
# PENDING 가드 충족 시).
PASS_BOX3_REAL_LOCAL_AFTER_HUMAN_APPROVAL: Final = "PASS_BOX3_REAL_LOCAL_AFTER_HUMAN_APPROVAL"
# Codex HOLD 정정 (2026-06-03, PR #775): 이전 임시 alias 제거 — Box3RealStatus Literal 정합
# 위해 단일 SSOT 라벨만 사용 (drift 0). 이전 라벨 문자열은 코드·테스트·evidence 어디에도
# 등장하지 않음을 grep 0 으로 검증.


ALL_BOX3_REAL_FAIL_CLASSES: Final = frozenset(
    {
        BLOCK_ASSET_MANIFEST_INVALID,
        BLOCK_ASSET_MANIFEST_CONTRADICTORY_ROWS,
        BLOCK_ASSET_INVENTORY_PENDING,
        ASSET_INTERFACE_PENDING,
        BLOCK_EVIDENCE_EXTRACTION_FAILED,
        BLOCK_BOX3_REAL_RUNNER_MISSING,
        BLOCK_BOX3_REAL_RUNNER_TIMEOUT,
        BLOCK_BOX3_REAL_RUNNER_ERROR,
        BLOCK_BOX3_REAL_SECURITY_RISK,
        BLOCK_CLAIM_EXTRACTION_EMPTY,
        BLOCK_FINAL_GATE_UNSUPPORTED,
        NEEDS_REVIEW_NO_EVIDENCE,
        CITATION_ACCURACY_BELOW_GATE,
        FORMAT_MATCH_BELOW_GATE,
        STYLE_MATCH_BELOW_GATE,
        TABLE_FIGURE_COVERAGE_BELOW_GATE,
        FIXED_EVAL_INSUFFICIENT,
        FIXED_EVAL_BELOW_GATE,
        BLOCK_RAW_OR_PATH_LEAK,
        BLOCK_HUMAN_APPROVAL_MISSING,
        BLOCK_HUMAN_APPROVAL_INVALID,
        BLOCK_HUMAN_APPROVAL_EXPIRED,
        BLOCK_HUMAN_APPROVAL_REVOKED,
        BLOCK_HUMAN_APPROVAL_SCOPE_MISMATCH,
        BLOCK_HUMAN_APPROVAL_KILL_SWITCH,
        BLOCK_BASE_MODEL_FULL_SHA_NOT_CONFIGURED,
        BLOCK_MODEL_ASSET_MISSING,
        BLOCK_MODEL_ASSET_SHA_MISMATCH,
        BLOCK_MODEL_ASSET_SHA_SCOPE_INVALID,
        BLOCK_HELPER_ASSET_DRIFT,
        BLOCK_HELPER_REAL_USE_GUARD_PENDING,
        BLOCK_MOCK_RUNNER_FOR_REAL,
        BLOCK_RUNNER_ERROR,
        BLOCK_RUNNER_TIMEOUT,
        BLOCK_POLICY_GATE,
        BLOCK_ASSET_INVENTORY_NOT_PASS,
        BLOCK_EVIDENCE_MISSING,
        BLOCK_BASELINE_DRIFT,
        NEEDS_REVIEW_NO_EVIDENCE_CLAIMS,
        NEEDS_REVIEW_FORMAT_STYLE_GATE,
        FIXED_EVAL_PENDING,
    }
)
