"""Box3 real 융합 — fail-closed fail_class 상수(단일 정의).

베이스: maindev real_fail_class. 모든 차단/보류 사유는 reason code 로만 노출하며
원문·경로·토큰을 담지 않는다.
"""
from __future__ import annotations

from typing import Final

BLOCK_ASSET_MANIFEST_INVALID: Final = "BLOCK_ASSET_MANIFEST_INVALID"
BLOCK_ASSET_MANIFEST_CONTRADICTORY_ROWS: Final = "BLOCK_ASSET_MANIFEST_CONTRADICTORY_ROWS"
BLOCK_ASSET_INVENTORY_PENDING: Final = "BLOCK_ASSET_INVENTORY_PENDING"
ASSET_INTERFACE_PENDING: Final = "ASSET_INTERFACE_PENDING"
BLOCK_EVIDENCE_EXTRACTION_FAILED: Final = "BLOCK_EVIDENCE_EXTRACTION_FAILED"
BLOCK_BOX3_REAL_RUNNER_MISSING: Final = "BLOCK_BOX3_REAL_RUNNER_MISSING"
BLOCK_BOX3_REAL_RUNNER_TIMEOUT: Final = "BLOCK_BOX3_REAL_RUNNER_TIMEOUT"
BLOCK_BOX3_REAL_SECURITY_RISK: Final = "BLOCK_BOX3_REAL_SECURITY_RISK"
BLOCK_CLAIM_EXTRACTION_EMPTY: Final = "BLOCK_CLAIM_EXTRACTION_EMPTY"
BLOCK_FINAL_GATE_UNSUPPORTED: Final = "BLOCK_FINAL_GATE_UNSUPPORTED"
NEEDS_REVIEW_NO_EVIDENCE: Final = "NEEDS_REVIEW_NO_EVIDENCE"
CITATION_ACCURACY_BELOW_GATE: Final = "CITATION_ACCURACY_BELOW_GATE"
FORMAT_MATCH_BELOW_GATE: Final = "FORMAT_MATCH_BELOW_GATE"
STYLE_MATCH_BELOW_GATE: Final = "STYLE_MATCH_BELOW_GATE"
TABLE_FIGURE_COVERAGE_BELOW_GATE: Final = "TABLE_FIGURE_COVERAGE_BELOW_GATE"
FIXED_EVAL_INSUFFICIENT: Final = "FIXED_EVAL_INSUFFICIENT"
FIXED_EVAL_BELOW_GATE: Final = "FIXED_EVAL_BELOW_GATE"
BLOCK_RAW_OR_PATH_LEAK: Final = "BLOCK_RAW_OR_PATH_LEAK"

ALL_BOX3_REAL_FAIL_CLASSES: Final = frozenset(
    {
        BLOCK_ASSET_MANIFEST_INVALID,
        BLOCK_ASSET_MANIFEST_CONTRADICTORY_ROWS,
        BLOCK_ASSET_INVENTORY_PENDING,
        ASSET_INTERFACE_PENDING,
        BLOCK_EVIDENCE_EXTRACTION_FAILED,
        BLOCK_BOX3_REAL_RUNNER_MISSING,
        BLOCK_BOX3_REAL_RUNNER_TIMEOUT,
        BLOCK_BOX3_REAL_SECURITY_RISK,
        BLOCK_CLAIM_EXTRACTION_EMPTY,
        BLOCK_FINAL_GATE_UNSUPPORTED,
        NEEDS_REVIEW_NO_EVIDENCE,
        CITATION_ACCURACY_BELOW_GATE,
        FORMAT_MATCH_BELOW_GATE,
        STYLE_MATCH_BELOW_GATE,
        TABLE_FIGURE_COVERAGE_BELOW_GATE,
        FIXED_EVAL_INSUFFICIENT,
        FIXED_EVAL_BELOW_GATE,
        BLOCK_RAW_OR_PATH_LEAK,
    }
)
