from __future__ import annotations

# Box3 v7 canonical apply v1.2 fail/status SSOT.
PASS_BOX3_REAL_LOCAL_AFTER_HUMAN_APPROVAL = "PASS_BOX3_REAL_LOCAL_AFTER_HUMAN_APPROVAL"
PARTIAL_BOX3_V7_ABSTAIN_OVERUSE = "PARTIAL_BOX3_V7_ABSTAIN_OVERUSE"
PARTIAL_BOX3_V7_CITATION_LOW = "PARTIAL_BOX3_V7_CITATION_LOW"
PARTIAL_BOX3_V7_F16_NOT_MEASURED = "PARTIAL_BOX3_V7_F16_NOT_MEASURED"
PARTIAL_REAL_ASSET_VOLUME_MISSING = "PARTIAL_REAL_ASSET_VOLUME_MISSING"
PARTIAL_REAL_RUNNER_RUNTIME_UNAVAILABLE = "PARTIAL_REAL_RUNNER_RUNTIME_UNAVAILABLE"
BLOCK_PRECONDITION_PR785_NOT_MERGED = "BLOCK_PRECONDITION_PR785_NOT_MERGED"
BLOCK_BASELINE_DRIFT = "BLOCK_BASELINE_DRIFT"
BLOCK_V7_SHA_MISMATCH = "BLOCK_V7_SHA_MISMATCH"
BLOCK_V5_DEFAULT_RESIDUE = "BLOCK_V5_DEFAULT_RESIDUE"
BLOCK_V4_DEFAULT_REFERENCE = "BLOCK_V4_DEFAULT_REFERENCE"
BLOCK_HELPER35_DOUBLE_STACK_RISK = "BLOCK_HELPER35_DOUBLE_STACK_RISK"
BLOCK_UNSUPPORTED_CLAIM = "BLOCK_UNSUPPORTED_CLAIM"
BLOCK_DEGENERATION_DETECTED = "BLOCK_DEGENERATION_DETECTED"
BLOCK_ABSTAIN_MARKER_INVALID = "BLOCK_ABSTAIN_MARKER_INVALID"
BLOCK_RAW_OR_PATH_EVIDENCE_LEAK = "BLOCK_RAW_OR_PATH_EVIDENCE_LEAK"
BLOCK_CONNECT_LOOP_MODIFIED = "BLOCK_CONNECT_LOOP_MODIFIED"
BLOCK_GROUNDING_OR_JSON_SUPPRESSION_DRIFT = "BLOCK_GROUNDING_OR_JSON_SUPPRESSION_DRIFT"
BLOCK_MODEL_ASSET_SHA_SCOPE_INVALID = "BLOCK_MODEL_ASSET_SHA_SCOPE_INVALID"
CONTRACT_ONLY = "CONTRACT_ONLY"
REAL_CANDIDATE = "REAL_CANDIDATE"
BLOCKED = "BLOCKED"
PARTIAL = "PARTIAL"

ALLOWED_V7_STATUSES = {
    PASS_BOX3_REAL_LOCAL_AFTER_HUMAN_APPROVAL,
    PARTIAL_BOX3_V7_ABSTAIN_OVERUSE,
    PARTIAL_BOX3_V7_CITATION_LOW,
    PARTIAL_BOX3_V7_F16_NOT_MEASURED,
    PARTIAL_REAL_ASSET_VOLUME_MISSING,
    PARTIAL_REAL_RUNNER_RUNTIME_UNAVAILABLE,
    BLOCK_PRECONDITION_PR785_NOT_MERGED,
    BLOCK_BASELINE_DRIFT,
    BLOCK_V7_SHA_MISMATCH,
    BLOCK_V5_DEFAULT_RESIDUE,
    BLOCK_V4_DEFAULT_REFERENCE,
    BLOCK_HELPER35_DOUBLE_STACK_RISK,
    BLOCK_UNSUPPORTED_CLAIM,
    BLOCK_DEGENERATION_DETECTED,
    BLOCK_ABSTAIN_MARKER_INVALID,
    BLOCK_RAW_OR_PATH_EVIDENCE_LEAK,
    BLOCK_CONNECT_LOOP_MODIFIED,
    BLOCK_GROUNDING_OR_JSON_SUPPRESSION_DRIFT,
    CONTRACT_ONLY,
    REAL_CANDIDATE,
    BLOCKED,
    PARTIAL,
}
